### ISSUE TITLE
Manuscript, SermonDescription: add Literature

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#102]
The details section of Sermon and Manuscript (see issue #36) need to be added with a Literature part that show the abbreviations of the literature used.

**Comment by ThijsRU** [comment]
- A Zotero database will be the central storage of all references of the editions and literature used for the Gold Sermons (editions), Sermons (editions and literature) and Manuscripts (literature.

- The team will enter the abbreviations by hand (or copy pasted out of the Zotero database) and they will be separated by an semicolon.

- Discuss with the PI in what way the editions and the literature should be separated from each other, Bibliography _editions_ and Bibliography _literature_? 

- There should be a direct link (maybe on _editions_ and _literature_?) to the central Bibliography page and if clicked upon, that page should be opened in a new tab.

- Place Bibliography literature under **External** (Manuscript) and under **Bibliography editions** (Sermon).

**Comment by ErwinKomen** [comment]
Note: do make use of `Litref.sync_zotero()` to synchronize the Zotero database with the Django one

**Comment by ThijsRU** [comment]
- It is already possible to add literature reference to a Manuscript. Each unique reference is automatically added to the Bibliography section.
