### ISSUE TITLE
SermonDescription: add Editions

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#103]
In SermonDescription the same editions used for the linked Gold Sermon should be made visible.

**Comment by ThijsRU** [comment]
- The editions used that were entered into the database for the Gold Sermon should be copied to each of the linked Sermons.

**Comment by ErwinKomen** [comment]
Update 12/sep/2019 (see issue #115 and email):
- The _editions_ of a SermonDescr should **not** be separately linked with or copied to the `SermonDescr` instance
- Instead, all editions that are part of the SermonGold instances associated with a `SermonDescr` are to be automatically 'viewable' at the `SermonDescr` details view (they are not editable, only viewable)

**Comment by ErwinKomen** [comment]
Remaining TODO for this issue:
- Add a link from each [view-only] Edition to the Editions part of the Bibliography page
