### ISSUE TITLE
Tab page: add sparsely

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#148]
New tab pages should be opened (automatically) sparsely.

Right now new tab pages are opened in these circumstances:
1. Library listview: user clicks on "Go to these manuscripts"
1. Manuscript 
    1. listview: user clicks on "external link" button
    1. details: user clicks on "Origins" ('open a list of origins in a separate tab')
    1. details: user clicks on "Locations" ('open a list of locations in a separate tab')
    1. details / external urls: user clicks on an external URL
1. Sermon 
    1. details: user clicks on a 'Gold sermon' link
    1. details / equality set: user clicks on gold-sermon in the equality set
1. Sermon Gold
    1. details: user clicks on a 'Gold sermon' link
    1. details / equality set: user clicks on gold-sermon in the equality set

Two options:
1. Change all of the above to _remain on the same tab page_ in the browser
1. Change all of the above to only open a new tab page when the user clicks something like CTRL + click (standard behaviour for going to a new tab page)

Which one is the better @shariboodts ?

**Comment by shariboodts** [comment]
Beste Erwin,

Ik denk dat optie 2 het beste is, maar ik zet Iris nog even in Cc voor een bevestiging.

Beste groeten,
Shari

Shari Boodts
Senior Researcher
Departement of History
Radboud University Nijmegen



On 11 Nov 2019, at 16:03, ErwinKomen <notifications@github.com<mailto:notifications@github.com>> wrote:


New tab pages should be opened (automatically) sparsely.

Right now new tab pages are opened in these circumstances:

  1.  Library listview: user clicks on "Go to these manuscripts"
  2.  Manuscript
     *   listview: user clicks on "external link" button
     *   details: user clicks on "Origins" ('open a list of origins in a separate tab')
     *   details: user clicks on "Locations" ('open a list of locations in a separate tab')
     *   details / external urls: user clicks on an external URL
  3.  Sermon
     *   details: user clicks on a 'Gold sermon' link
     *   details / equality set: user clicks on gold-sermon in the equality set
  4.  Sermon Gold
     *   details: user clicks on a 'Gold sermon' link
     *   details / equality set: user clicks on gold-sermon in the equality set

Two options:

  1.  Change all of the above to remain on the same tab page in the browser
  2.  Change all of the above to only open a new tab page when the user clicks something like CTRL + click (standard behaviour for going to a new tab page)

Which one is the better @shariboodts<https://github.com/shariboodts> ?

**Comment by shariboodts** [comment]
Beste allen,

Ik denk inderdaad dat optie 2 het beste is. Mocht dat niet intuïtief zijn voor de gebruiker, zouden we er wellicht nog een ‘reminder’ bij kunnen zetten ergens (‘CTRL+click to open a new web browser’ o.i.d.).

Groeten,
Iris

Van: Boodts, S. (Shari) <S.Boodts@let.ru.nl>
Verzonden: dinsdag 12 november 2019 11:06
Aan: ErwinKomen/RU-passim <reply@reply.github.com>
CC: Denis, I.A.T. (Iris) <I.Denis@let.ru.nl>
Onderwerp: Re: [ErwinKomen/RU-passim] Tab page: add sparsely (#148)

Beste Erwin,

Ik denk dat optie 2 het beste is, maar ik zet Iris nog even in Cc voor een bevestiging.

Beste groeten,
Shari

Shari Boodts
Senior Researcher
Departement of History
Radboud University Nijmegen




On 11 Nov 2019, at 16:03, ErwinKomen <notifications@github.com<mailto:notifications@github.com>> wrote:

New tab pages should be opened (automatically) sparsely.
Right now new tab pages are opened in these circumstances:

  1.  Library listview: user clicks on "Go to these manuscripts"
  2.  Manuscript

     *   listview: user clicks on "external link" button
     *   details: user clicks on "Origins" ('open a list of origins in a separate tab')
     *   details: user clicks on "Locations" ('open a list of locations in a separate tab')
     *   details / external urls: user clicks on an external URL

  1.  Sermon

     *   details: user clicks on a 'Gold sermon' link
     *   details / equality set: user clicks on gold-sermon in the equality set

  1.  Sermon Gold

     *   details: user clicks on a 'Gold sermon' link
     *   details / equality set: user clicks on gold-sermon in the equality set
Two options:

  1.  Change all of the above to remain on the same tab page in the browser
  2.  Change all of the above to only open a new tab page when the user clicks something like CTRL + click (standard behaviour for going to a new tab page)
Which one is the better @shariboodts<https://github.com/shariboodts> ?

**Comment by shariboodts** [comment]
Beste collega’s,

Ik heb zonet de twee Clavis-volumes in de werkgroepmap gezet. Zullen we aanstaande donderdag afspreken, bv. om 10u, om verder te spreken over het voorstel van Brepols?

Fijne werkweek,
Shari

Shari Boodts
Senior Researcher
Departement of History
Radboud University Nijmegen

**Comment by ErwinKomen** [comment]
Progress:

1. Library listview: user clicks on "Go to these manuscripts" - _done (href)_
1. Manuscript 
    1. listview: user clicks on "external link" button - _done (href)_
    1. details: user clicks on "Origins" ('open a list of origins in a separate tab') - _done (href)_
    1. details: user clicks on "Locations" ('open a list of locations in a separate tab') - _done (href)_
    1. details / external urls: user clicks on an external URL - _done (href)_
1. Sermon 
    1. details: user clicks on a 'Gold sermon' link - _done (href)_
    1. details / equality set: user clicks on gold-sermon in the equality set - _done (href)_
1. Sermon Gold
    1. details: user clicks on a 'Gold sermon' link - _done (href)_
    1. details / equality set: user clicks on gold-sermon in the equality set - _done (href)_
