### ISSUE TITLE
SermonGold: author take-over

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#157]
Nov 2019:
> Het automatisch ingevulde veld ‘SermonGold author’ neemt nu bij een equals link aan een equality set alleen de eerste naam van de auteur over. Willen we dat? Ik zou gewoon alle auteurs overnemen van de equals gelinkte equality set; dat geeft het meest complete beeld

**Comment by MennaRempt** [comment]
Beter nog even on-hold.

**Comment by ErwinKomen** [comment]
Menna wrote on Feb/2:
> a.	Maar: als we met SuperSermonGolds gaan werken hoeft alleen de auteur van de SuperSermonGold overgenomen te worden. -> Dus on hold!
> b.	Op de pagina van een SSG moet een lijstje zichtbaar zijn van alle SG’s die in de equality set zitten, met hun auteursnamen. (zie ook bestand ‘Features SuperSermonGold’)

Conclusion: this issue has been solved
