### ISSUE TITLE
SermonGold: link behaviour for signatures

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#158]
Nov 2019:
> Bij het linken van SermonGolds worden de Gryson en CPPM codes alleen maar gekopieerd na drukken op de ‘sermon details’ knop. Het zou fijn zijn als dit automatisch kon, en dat de codes ‘verbonden’ blijven aan de sermon gold in kwestie; d.w.z. als ik iets aan de Gryson code van de SermonGold zou veranderen, zouden alle gelinkte manifestaties mee moeten veranderen (zoals dat nu wel al gebeurt met edities). De Gryson- en CPPM codes bij manifestaties moeten echter ook nog handmatig aangepast kunnen worden. Kan dat?

**Comment by ErwinKomen** [comment]
Summing up the above in terms of the application:
1. A manifestation (=`SermonDescr` instance) will have two kinds of Gryson/CPPM codes (=signatures):
    1. The `goldsignature` instances linked to it through all the linked `SermonGold` instances
    1. The `sermonsignature` instances specified by the user manually

**Comment by Irisdenis** [comment]
Een kleine rectificatie in mijn bericht uit november (waarvoor excuses!):

"Bij het linken van SermonGolds worden de Gryson en CPPM codes alleen maar gekopieerd na drukken op de **'copy information from this Sermon Gold'** knop. Het zou fijn zijn als dit automatisch kon..."

**Comment by ErwinKomen** [comment]
Menna wrote on Feb/4:
> 4.	Automatisch updaten van de Gryson en Clavis codes bij een sermon manifestatie als de gelinkte SuperSermonGold wordt aangepast -> Issue #158 (over SermonGold, moet dus aan de SuperSermonGold worden aangepast)
> a.	En automatisch importeren: momenteel worden de Gryson en Clavis codes alleen gekopiëerd na het drukken of ‘informatie kopiëren’. Betere situatie is zoals bij ‘edities’: volledig automatisch na het aanmaken van een ‘equals’-link

**Comment by ErwinKomen** [comment]
All of this boils down to a slight adaptation of what I wrote earlier:

1. A manifestation (=`SermonDescr` instance) will have two kinds of Gryson/CPPM codes (=signatures):
    1. The `goldsignature` instances **automatically** linked to it through all the `SermonGold` instances that are part of the same _equality set_ (SSG) connected with me
    1. Optionally `sermonsignature` instances specified by the user **manually**

**Comment by ErwinKomen** [comment]
Okay, step #1: 
- the new Sermon Details view is working, and all elements are there. 
- The links to the Gold Sermons are working: add, remove, inline as well as below.
- The Gold signatures are show automatically correctly

TODO: make the manual addition of SermonSignature work correctly
1. Editing Gryson should disable editing other boxes 
1. Double check:
    1. Adding a new Gryson / Clavis / Other
    1. Removing an existing manual Gryson / Clavis / Other

**Comment by ErwinKomen** [comment]
Well, the above is working okay now. Can close.
