### ISSUE TITLE
SermonGold: new list view

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#164]
This view should contain the following fields: 

1. SuperSermonGold
1. SermonGolds linked to SuperSermonGold

**Comment by ErwinKomen** [comment]
Interpreting the above, add _Columns_ in the SermonGold listview:
1. SuperSermonGold: the Passim code + a link to that SSG
1. The _number_ (count) of SGs that are part of the SSG (=equality set) to which this SG belongs??
