### ISSUE TITLE
SuperSermonGold migration

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#165]
As for the initial step of creating `SuperSermonGold` instances based on `SermonGold` ones currently in the database:
1. author by default undecided except when equality set has only one SermonGold
1. Generate PASSIM-code according to instructions (16-01-2020 4 - see #170)
1. new field: preek-nummer per auteur
1. new field: doorverwijzingsnummer (voor als een preek een nieuw nummer krijgt) (default: leeg)

**Comment by ErwinKomen** [comment]
The above has been dealt with in issues #170 and #171 
Note: the actual _migration_ will be done by the developers in two steps:
1. Bring up the new release of the **Passim** application
1. Run a special SuperSermonGold migration utility at Developers >> SSG migration

**Comment by ErwinKomen** [comment]
One thing not done yet: author default must be **undecided**

**Comment by ErwinKomen** [comment]
One error/bug: each new 'save' action creates an SSG with a new sermon number.
Cause: the field `number` is not processed correctly...

**Comment by ErwinKomen** [comment]
Okay, fixed that.
Also: double checked migration to go to author "undecided" >> repaired code

Okay, all working fine now!
