### ISSUE TITLE
Author: numbering

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#166]
Author krijgt nieuw veld 'nummer', default = none. 
Auteur krijgt nummer als een SuperSermonGold toegewezen is aan deze auteur.

**Comment by MennaRempt** [comment]
Pas geïmplementeerd als de database voor een breed publiek toegankelijk wordt.

**Comment by ErwinKomen** [comment]
This is working **now**, since it relates to the SSGs
