### ISSUE TITLE
Basket: store queries as a collection

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#168]
The Basket functionalities need to be extended in order to store certain queries in the list view of Super Sermon Gold / Sermon / Manuscript / (Sermon Gold) as Collections.

**Comment by ErwinKomen** [comment]
This consists of two steps:
1. The user should be able to **Create** a collection from the basket contents - _done (2/apr/20)_
1. When a user has collected material in a basket, it should be possible to **Add** this to a specifiable collection

**Comment by ErwinKomen** [comment]
Okay, I worked on (2).
Need to check whether this works for all **four** of the types:
1. **gold**: works
1. **sermo**: ??
1. **manu**: ??
1. **super**: ??

**Comment by ErwinKomen** [comment]
1. Basket
    - empty  **sermo**
    - create **sermo**
1. Collection 
    - create new **sermo**
    - add to existing
