### ISSUE TITLE
SuperSermonGold: view

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#171]
(See "Features van de SuperSermonGold", 23/jan/2020)

The view of a `SuperSermonGold` (SSG) is based on the view of the `GoldSermon` (SG) these fields need to be visible and editable:

Title: "Super Sermon Gold details"

1. PASSIM code (relatively large) - _ok_
1. Author - _ok_
1. Incipit - _ok_
1. Explicit - _ok_
1. Is equal to Gold Sermon
    1. This field should show the Gold Sermons that are part of the equality set that is symbolized by the SSG.  - _ok_
    1. A button should be added with which a new GoldSermon can be added to the SSG.  - _ok, implemented_
        1. The current possibility to add a new GS is to be deleted from the GS list view (issue #173)  - _ok, done_
    1. **A button** (`elevate to SuperSermonGold`) should be added after each GS. When clicking on that button the information from that SG is copied to the SSG. This should work the same way when copying information from GS to Sermon Descr. Is the name of the author part of this? - _Done: what is copied is the **author**, **incipit** and **explicit**_
    1. A **pop-up message** "Are you sure you want to do this?" - _Done: this works_
1. Links to other SuperSermonGolds (partially linked)
    1. Show:  - _Ok, these fields show fine_
        1.  PASSIM code - _ok_
        1.  Gryson/Clavis codes (associated with the SSG) - _ok_
        1.  Author - _ok_
        1.  Incipit - _ok_
        1.  Explicit - _ok_
    1. Implement the following abilities for these 'partial' links:
        1. Note: make sure link choices are (a) shown fully, (b) abbreviated upon selection - _ok_
        1. Add a new link, restricted to the partial link types - _ok_
        1. Remove a partial link - _ok_
        1. Change the current link - _ok_
    1. Points of attention:
        1. The user must *see* that process is going on. Show a waiting symbol (after pressing add, change or delete).
        1. Double check: are the super_linkset and the super_eqset independent, or does one lead to refreshing the other?
        1. Add validation:
            1. The same link may only be added once
            1. Don't allow adding a link that is already in the equality set
1. **List of manuscripts** linked to the SSG (via Sermon Descr)

Further more: View issue #170

**Comment by ErwinKomen** [comment]
As for (6.ii.a) above:
- Make sure only non-equal options are shown

**Comment by ErwinKomen** [comment]
As for (6.iii) above:

    1. Points of attention:
        1. The user must *see* that process is going on. Show a waiting symbol (after pressing add, change or delete).
        1. Double check: are the super_linkset and the super_eqset independent, or does one lead to refreshing the other?
        1. Add validation:
            1. The same link may only be added once
            1. Don't allow adding a link that is already in the equality set

**Comment by ErwinKomen** [comment]
As for point (5.iii), the elevation:

1. Added an `Elevate` button in `super_eqset.html`. 
    1. This button opens the `equalgold_details` with the current id, and adds a (GET) parameter `golcopy`, which is equal to the id of the gold sermon whose information needs to be copied
    1. As per (5.iv), a confirmation dialog should appear - _ok_


TODO: implement the reaction on ?goldcopy in `EqualGoldDetails`, GET

**Comment by ErwinKomen** [comment]
Now working on point (7):
**List of manuscripts** linked to the SSG (via Sermon Descr)
