### ISSUE TITLE
Gold Sermon: view

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#172]
(See "Features van de SuperSermonGold", 23/jan/2020)

The view of a `GoldSermon` (GS) needs to be changed due to the introduction of the `SuperSermonGold` (SSG) (view issue #170 and #171).

After the title of the view ("Gold Sermon details") these three fields need to be added _to_ or deleted _from_ the current view: 

1. Belongs to the **equality set of SuperSermonGold** (show the PASSIM-`code`)
    1. Here, the editors need to be able to transfer the Gold Sermon from one SSG/equality set to another by clicking on the edit button. This should open up a select2 list with all existing SSGs. After the selection is confirmed the view is changed: the members of the new SSG/equality set should be visible. Please view part 2. The information on the SSG is not to be changed from the GS view.
1. Other **members of the equality** set are:
    1. This should show a list of the other Gold Sermons in the equality set, preferably in one row.
1. The **partially equal** links section is to be deleted. - _**EK**: done (19/mar)_

Further more, in the GoldSermon view
1. the editors should be able to elevate the GoldSermon to a SuperSermonGold and overwrite the existing information of the SSG of which that GS is a part.  - _**EK**: the elevation can only be done from the details view of SSG (23/mar). I think this should be enough?_

The editors should be able to edit the new SSG afterward, of course without making changes to the original source (the GS). - _**EK**: sure, no problem: just click on the SSG link and the editor gets there_

Please view issue #171 .

**Comment by ErwinKomen** [comment]
Point number (1) is working mostly, except for the part that strictly belongs to (2).

(2) - show a list of the other Gold Sermons in the equality set, preferably in one row
