### ISSUE TITLE
Gold Sermon: list view, delete button "add new GS"

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#173]
The button "Add a gold sermon" in the Gold Sermon list view is to be deleted. The creation of a new GoldSermon should only be possible in the SuperSermonGold list view.

**Comment by ErwinKomen** [comment]
Right, but issue #171 was not completely done. THere is no button for a completely **new** Sermon Gold to be added

**Comment by ErwinKomen** [comment]
Okay, I've now extended `BasicDetails` and `basic_details.hml` to include a `new_button` with all kinds of possibilities.
I've added the correct parameters to `EqualGoldEdit`, `add_to_context()`.
Now it's working: 
- there is a button to add a new Gold sermon
- this Gold sermon is initialized with the current EqualGold (so becomes part of the equality set)
- once created, it is possible to return to the EqualGold item by pressing the Passim Code
