### ISSUE TITLE
SuperSermonGold: list view

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#174]
- The list view of `SuperSermonGold` (SSG) should show an ordered list of all SSGs (basically just like the `GoldSermon` view. - **_EK**: done_

- The user should be able to access the SSG list view via the 'Search-option in the menu of the webapplication. - **_EK**: done. Search >> Super sermon gold_

- These fields need to be added to the list view: 
   1. Author
   2. PASSIM code
   3. Incipit..Explicit
   more?? - **_EK**: we have `Author`, `Number`, Passim `Code`, `Gryson/Clavis`, `Incipit...Explicit`, `Size`_

- In the list view of the `SuperSermonGold` a button needs to be added with which an editor can add a new `SuperSermonGold`to the database.   - **_EK**: done. This works correctly. A new SSG is added. No gold sermons are part of it initially. It gets a Passim Code as soon as the Author is chosen._

The default settings are: 
   1. `author`: undecided
   2.  all other fields: empty

**Comment by ErwinKomen** [comment]
1. When _editing_ a SSG, and changing its `author`, the following happens:
    1. A new SSG is made with the original author and a `moved` pointer to the current SSG
    1. The current SSG gets the new author and receives a new Passim code (according to the code principles)

TODO: check with user if this works to satisfaction

**Comment by ErwinKomen** [comment]
One minor bug: no author typeahead updating after edit + save of SSG
1. Resolution: change author _typeahead_ into author _select2_

**Comment by ErwinKomen** [comment]
One more feature: SSG links
1. The **Moved to** field should contain a link to the SSG to which it has been moved
1. Any SSG that is a newer 'version' (i.e. different author) of an other one, should have a viewable field with a link to the SSG it results from
