### ISSUE TITLE
Collection: specify sharing collections

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#178]
The creators (editors) of a collection should be able to specify whether a collection is to be shared or not (and thus private) and to which group (editors, read and write) or all users (read only). 

The shared collections need a lock-out functionality so that only one editor can make changes.

The current "read only"-option is to be changed.

**Comment by ErwinKomen** [comment]
So these are the possibilities:

----------------------------------------
Option | Editors may: | All users may:
----------------------------------------
private | (nothing) | (nothing)
--------------------------------

**Comment by ErwinKomen** [comment]
What the different scope levels mean for the application
1. No permission
    1. No one except the user may _see_ it
1. **read**: 
    1. For people in the same group (editors or users):
        1. Visible in listview (with statement of who the owner is)
        1. Visible in details view, but not editable (flag `permission` is `read`)
        1. Can be used in searching in a listview
1. **write**: 
    1. As above for **read**, plus:
    1. For people in the same group (editors):
        1. Editable in details vew (flag `permission` is `write`)

**Comment by ErwinKomen** [comment]
Actions:
1. Add flag `permission` to the context of the details view of `CollAny`

**Comment by ErwinKomen** [comment]
Okay, the above seems to be working.

TODO: adapt the **filtering** possibilities in the **Listviews** of `manu`, `super`, `gold`, `sermo`. These too must incorporate the `scope` value and the ownership...

**Comment by ErwinKomen** [comment]
As for the **filtering** possibilities in the listviews above:
1. Restrict select2 options to `Collection.get_scoped_queryset()`, as in `SermonGoldForm`
1. Do this for the corresponding forms for all four listviews

**Comment by ErwinKomen** [comment]
Implent method `get_scoped_queryset()` in the relevant **forms** and **models**:
1. **gold**
    1. List and Edit form `SermonGoldForm` - _done_
1. **manu**
    1. List form `SearchManuForm`
    1. Edit form `ManuscriptForm`
1. **sermo**
    1. List and Edit form `SermonForm`
1. **super**
    1. List and Edit form `SuperSermonGoldForm`

**Comment by ErwinKomen** [comment]
Problems:
- manuscript collection list also shows collections of other types
- manuscript collection listview doesn't contain column 'type'
