### ISSUE TITLE
Search: different letters

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#203]
Menna:

> Zoeksysteem: is het mogelijk dat voor het zoeken a=ae, j=i, u=v?

**Comment by ErwinKomen** [comment]
This needs more information, @Menna: searching **where** and for **what** exactly?
I'm guessing: searching for `incipit` and `explicit` wherever they occur? Is that right??

**Comment by MennaRempt** [comment]
> I'm guessing: searching for `incipit` and `explicit` wherever they occur? Is that right??
Yes, exactly right.

correction to the issue: **e=ae**

**Comment by shariboodts** [comment]
Can you also include k = c? Thanks!

**Comment by ErwinKomen** [comment]
Okay, implementation:
1. Write a separate function for the Inc/Exp searches
1. Change e.g. 'k' into '[kc]', so that these are equal

**Comment by ErwinKomen** [comment]
Okay, works
