### ISSUE TITLE
SSG and SG listview: show Gryson codes first

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#208]
In the SSG and SG listviews the Gryson codes should be the first ID codes listed for each SSG and SG. In case a sermon has 3-7 CPPM codes the current situation is confusing.

**Comment by ErwinKomen** [comment]
1. `SermonGoldListView`: 
    1. Currently no sort order, just `instance.goldsignatures.all()`
    1. Changed into: `instance.goldsignatures.all().order_by('-editype')`
