### ISSUE TITLE
SSG listview: sort by Gryson/Clavis code

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#209]
In the SSG listview sorting on the Gryson/Clavis codes should be made possible, alphabetically on the first code.

**Comment by ErwinKomen** [comment]
Actions:
1. Add a field `firstsig` to `EqualGold` - this contains the _first_ signature (Gryson/Clavis/Other)

**Comment by ErwinKomen** [comment]
Okay, works. Note that preference is: **ot** >> **gr** >> **cl**
THat is:
> Other >> Gryson >> Clavis

This means that the 'other' codes are shown _before_ the Gryson and the Clavis
