### ISSUE TITLE
SSG and SG listview: PASSIM code search with digits

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#210]
In the SSG and SG listviews the user should be able to search for the PASSIM code with only the digits of the code, the text part of the code ('PASSIM ' ) should not be mandatory when filling in the code. 

Possibly 'PASSIM ' should be automatically filled in when the search option for the PASSIM code is clicked on or when the first digit of the code is typed in.

**Comment by ErwinKomen** [comment]
This connects with a general remark on searching (I think it has a different issue number). When a user wants to look for a particular author or sermon number, wildcards should be used:
- Searching for `*001.*` - yields all SSGs attributed to author 001
- Searching for `*001` - yields all first SSGs for different authors

**Comment by ThijsRU** [comment]
This issue can be closed, the current wildcard possibilities are sufficient for now.
