### ISSUE TITLE
SSG detail view: add Edition (from SG)

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#211]
The SSG detail page should be expanded with an "Edition" part.  All text editions associated with the equality set (because they are part of the SG’s data) should be listed here.

**Comment by ErwinKomen** [comment]
Added method `get_editions_markdown()` to `EqualGold` model.
Call that method from the view `EqualGoldEdit`

**Comment by ErwinKomen** [comment]
NOTE: the list of editions is automatically determined from the current Gold Sermons in the equality set.
