### ISSUE TITLE
SSG list and detail view: remove sermon number 

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#212]
The function of the field ‘Sermon number’ is not clear, it seems not necessary to be visible (confusing).  It should be removed from the list view and detail view.

**Comment by ErwinKomen** [comment]
It is the number of the sermon attributed to a particular author.
But the information is, indeed, already there in the Passim code.

**Comment by ErwinKomen** [comment]
1. Details view: outcommented it
1. Listview: 
    1. Remove from `order_cols`
    1. Outcomment from `order_heads`
    1. Outcomment from method `get_field_value()`

**Comment by ErwinKomen** [comment]
Okay, works
