### ISSUE TITLE
SSG detail view: add Literature (from SG)

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#213]
The literature that is added to each SG in the equality set should also be visible in the SSG detail view. This means adding "Literature" to the detail view and collect all references from all SG's in the equality set.

**Comment by ErwinKomen** [comment]
This is potentially a lot of information, so possibly better behind a button (i.e. default not visible, unless the user pressed a button)

**Comment by ErwinKomen** [comment]
Determine all the editions associated with one particular SSG, sorted on 'short':
litrefs = `LitrefSG.objects.filter(sermon_gold__equal=equal).order_by('reference__short')`

Added method `get_litrefs_markdown()` to `EqualGold` model.
Call that method from the view `EqualGoldEdit`

**Comment by ErwinKomen** [comment]
works
