### ISSUE TITLE
SSG detail view: Manuscript table, change From / Until  

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#214]
In the Manuscript table in the SSG detail view the years that belong to the "From" and "Until" fields should be combined into one field, referred to as "Date range". For instance: From 800 and Until 900 --> Date range 800-900.

**Comment by ErwinKomen** [comment]
My suggestion: differentiate between the edit and the view mode of the details view.
- **Edit mode**: retain the different 'from' and 'until' fields
- **View mode**: combine date range as suggested

**Comment by ErwinKomen** [comment]
okay, works
