### ISSUE TITLE
SSG detail view: Manuscript table, change Items

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#215]
In the Manuscript table in the SSG detail view, the "Items" field which currently shows the number of items in a manuscript, should show: 

- the item number of the sermon 
- a dash
- the total number of items

For instance: "36/128" if the relevant manifestation is the 36th item of a total of 128 items in the manuscript.

_Preferably_ the user could click on the item-number of the sermon and would navigate directly to that specific item in the Manuscript detail view. 

_Otherwise_ the item-number of the sermon could stand out for instance with a different color. 

In case of a manuscript with 200 items it takes a while to find the relevant manifestation. The first solution would help reduce the searching.

**Comment by ErwinKomen** [comment]
Okay, this works, now.
What I've also done: the numbers of the sermons can be selected or deselected.
N.B: the scrolling into view is not perfect due to there being needed an offset, and I don't know how to set that.
