### ISSUE TITLE
SSG detail view: Author, add explanation determination of authorship

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#217]
In the SSG detail view, the Author field should offer contextual help that explains how the authorship of a SSG is determined. 

Add an info-button after the name of the author that would generate a pop-up with a text box after clicking on it. In the textbox a _universal_ text will be shown.

**Comment by shariboodts** [comment]
The textbox should contain the following universal text:

[Contextual help author.docx](https://github.com/ErwinKomen/RU-passim/files/4750575/Contextual.help.author.docx)

**Comment by ErwinKomen** [comment]
Okay,done
