### ISSUE TITLE
Sermon list view: add PASSIM code filter

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#220]
In the Sermon list view, the option to filter on the PASSIM code (from SSG) should be added.

**Comment by ErwinKomen** [comment]
Add the PASSIM code filter whereever possible.
Double check M, S, SG, SSG

1. **S**: 
    1. View `SermonListView`, form `SermonForm`
    1. Add select2 filter that looks in `sermondescr_super__super` for `code` - _Done, works_
1. **M**: not really applicable
1. **SG**: 
1. **SSG**: there already is a filter, but that one only filters on 'free text with wildcards'
    1. View `EqualGoldListView`, form `SuperSermonGoldForm`
    1. Add one that uses a Select2 - _Done, works_
