### ISSUE TITLE
SSG edit view: remove select2 "clear all" button

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#222]
The ‘clear all’ button in the right corner of the fields below is dangerous:

- Collections
- Contains
- Links 

It is too easy to accidentally delete all (S)SG links, which has large consequences.  This 'clear all’ button must be removed.

**Comment by ErwinKomen** [comment]
Note: this is the select2 clear all button. Need to find out in the django-select2 options how this can be done. Or alternatively check how this can be accomplished through JS (that's doable).

**Comment by ErwinKomen** [comment]
Okay, the [django-select2 documentation](https://pythonhosted.org/Django-Select2/_modules/django_select2/forms.html) shows that it is possible to set the variable `data-allow-clear` to `false`. This can be done easily in the `SuperSermonGoldForm` for:
- goldlist
- superlist
- collist_m, collist_s, collist_sg, collist_ssg
