### ISSUE TITLE
SSG detail view: incipit, explicit

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#223]
Mail Shari, 2/jun/2020

> EK: naast velden incipit en explicit zijn er intern in de database de velden srchincipit en srchexplicit. Die velden worden gebruikt voor het zoeken, en in die velden staan de inc en expl, maar dan all lower case en zonder punctuatie.
> SB: Als dat het geval is, is het dan mogelijk om die lower case/zonder interpunctie incipits en explicits op een of andere manier automatisch ook zo te zien in de velden incipit en explicit? Dat spaart ons weer een heel aantal correcties uit?  

The fields `srchincipit` and `srchexplicit` need to be shown (view only) too.

**Comment by ErwinKomen** [comment]
Okay, I changed the system slightly, so that with SSG, the `srchincipit` and the `srchexplicit` are shown in the following situations:
- Only in **view** mode (not in _edit_ mode)
- They are shown (in smaller print, different color) right under the actual incipit/explicit
- Everyone can see these right now

**Comment by ErwinKomen** [comment]
I think this one has been solved, so I'm closing it.

**Comment by MennaRempt** [comment]
Is het mogelijk om de srchincipit en srchexplicit te tonen ipv de gewone incipit/explicit? Zodat er maar één incipit en één explicit wordt getoond, en niet beide. De srchincipit/explicit is immers degene die we eigenlijk willen zien/waar we naartoe willen. (of alle incipit/explicit vervangen door srchincipit/explicit?)

**Comment by ErwinKomen** [comment]
Points to address:
1. **Do away with** inc/expl in favour of srchinc/expl
    1. I think that would be a gross mistake. We are importing manuscripts, and these manuscripts have the incipit/explicit marked in particular way, using particular symbols that are all 'thrown away' when they are converted to srchincipit/srchexplicit. If we would do away with the original inc/expl, we would lose touch with the original manuscript (description). We would then not be able anymore to export the more faithful inc/expl that includes the italics and the punctuation. So: we will keep both inc/expl as well as srchinc/expl. At least internally.
1. **Show** srchinc/expl instead of inc/expl
    1. Sure, that is possible. And I can make the 'real' inc/expl visible 'on hover' for the interested users

**Comment by MennaRempt** [comment]
as for point 1: this is only for the SSG, not for sermon manifestations, so manuscript incipit/explicit would remain unchanged.

**Comment by ErwinKomen** [comment]
That's not how 'vervangen' is generally understood, but I get your point. It should be okay now anyway.
