### ISSUE TITLE
Keyword: automatic showing

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#226]
Keywords of some M/S/SG/SSG are to be automatically shown in another place.

1. Keywords attached to an SSG are to be automatically shown (read-only) with:
    1. All the SGs that are part of the equality set
    1. ALl the Ss (Sermon manifestations) that are linked to the SSG
1. Manually adding keywords is possible for:
    1. SSG (super sermon gold)
    1. SG (sermon gold)
    1. S (manifestation sermon)
    1. M (manifestation) - _double check to make sure this is or becomes possible (see Menna's comment)_

**Comment by MennaRempt** [comment]
Manually adding keywords should also be (/remain) possible for Manuscripts

**Comment by ErwinKomen** [comment]
Implementation:

1. Keywords attached to an SSG
    1. **SG**: details view of **sermon gold** should show keywords attached to all other SGs that are part of the same equality set
    1. **S**: Details view of **sermon manifestation** should show keywords attached to 'equal' SSGs
1. Double check manually adding keyword possibilities for:
    1. **SSG**
    1. **SG**
    1. **S**
    1. **M**

**Comment by ErwinKomen** [comment]
What about this: the SSG details view now shows all the keywords (manually) associated with this SSG. SHould it also show: all the keywords associated with SGs in the equality set?

**Comment by ErwinKomen** [comment]
The above now works.
