### ISSUE TITLE
'Anonymus' as author

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#228]
The author 'anonymus' should have the same status as all other author names:  Anonymus should therefore receive its own author code and the incremental sermon numbering, just like 'Augustinus' or 'Dubius'.

**Comment by ErwinKomen** [comment]
Actions:
1. Remove 'anonymus' from special treatment in these places:
    1. `SuperSermonGoldForm`, method `clean_author()`
    1. `Author` model, method `get_number()`
