### ISSUE TITLE
Manuscript details: Clavis/Gryson codes in sermons

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#231]
The Manuscript detail view shows the list of sermons belonging to the manuscript. The Clavis/Gryson codes that are added to each sermon should be visible, both _manually_ added to SermDescr as well as the ones that are _automatically_ imported when a SermDescr is linked to a SSG. 

Currently only the Clavis/Gryson codes that are _manually_ added to the SermDescr are visible in the list of manuscript contents.

An example:

Manuscript example:
https://passim.rich.ru.nl/manuscript/details/1786/

Sermon example:
https://passim.rich.ru.nl/sermon/details/53948/

**Comment by ErwinKomen** [comment]
Okay, done
