### ISSUE TITLE
Sermon details: fields

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#237]
Changes in fields on the Sermon details page:

1. subtitle: delete
2. quote > lectio, move to between section title and title
3. bibliographic notes: delete
4. additional > cod. notes

**Comment by ErwinKomen** [comment]
Notes:
1. **subtitle**: right now I delete it only visually, but retain it internally. 
1. **quote**: renamed to **lectio**
1. **bibliographic notes**: I deleted this _visually_. It remains there _internally_.
1. **additional**: I renamed it to `cod. notes`. WHat is the **full** form? Is that 'coding', 'codex'?

**Comment by ErwinKomen** [comment]
cod. notes = `codicological notes`
Two fields have been made 'edit-only': `subtitle` and `bibnotes`
