### ISSUE TITLE
Sermon details: uncertain author

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#238]
We zouden graag de mogelijkheid hebben om een onzekere auteursattributie aan te kunnen merken op de Sermon details pagina, bijvoorbeeld met een soort vlaggetje/vraagteken dat je aan kan vinken naast de auteursnaam.

**Comment by ErwinKomen** [comment]
Okay, this is the way it works now:
1. If there's no attributed author, nothing is shown
1. If there _is_ an attribute author, it is shown together with a flag. The color of the flag reveals its certainty (see below)
1. When editing a sermon **two** fields show:
    1. The regular author (selection) field
    1. A separate field with author certainty. 

Levels and colors:
1. **red** very uncertain
1. **orange** uncertain
1. **gray** average certainty
1. **lightgreen** reasonably certain
1. **green** very certain
