### ISSUE TITLE
SSG to S linking

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#239]
Links between SSG and Sermon manifestations should only be of one, non-specified type (with the properties of the current equals-links, but without calling it 'equals'). 

All current partially equals links should ideally automatically be changed into these non-specified links as well.

**Comment by MennaRempt** [comment]
Just to be clear, link specifications between two SSGs should remain intact.

**Comment by ErwinKomen** [comment]
Actions:
1. Added a link type (seeker.linktype) called **Unspecified** `uns`
