### ISSUE TITLE
Sermon details: literature

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#240]
The field 'literature' on the Sermon details page should show the literature references from both the linked SSG and the MS the sermon is found in. 

Perhaps with an indication whether the reference has been copied from the MS page or the SSG page? (colour-coded?)

**Comment by ErwinKomen** [comment]
Note: there is **no** physical 'copying' involved :)

**Comment by ErwinKomen** [comment]
Implementation:
1. Showing the literature references (it's show-only) is done via model `SermonDescr`, method `get_litrefs_markdown()`

**Comment by ErwinKomen** [comment]
This now works
