### ISSUE TITLE
Sermon details: Gryson/Clavis codes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#242]
Currently there are two fields for Gryson/Clavis codes on the sermon details page (auto and manual). Is it possible to combine these into one field, but keep the possibility to add codes manually?

**Comment by ErwinKomen** [comment]
What we can do is this:
1. Show the Gryson/Clavis codes for auto + manual together in a Gryson/Clavis field
1. Allow adding Gryson/Clavis manually only in edit-mode

**Comment by ErwinKomen** [comment]
Yes, works!
