### ISSUE TITLE
S: SSG linktype invisible

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#245]
The type of link from a Sermon manifestation to a SSG should be hidden in de sermon details view (so only the link itself is shown).

**Comment by ErwinKomen** [comment]
Actions:
1. forms.py, `SermonDescrSuperForm`: remove `help_text="editable"` for `newlinktype`. This has the effect that the linktype is not editable anymore for the user
1. models.py, `SermonDescr` method `get_superlinks_markdown()`: don't show the linktype in the table anymore

**Comment by ErwinKomen** [comment]
Okay, all fine now. Checked life and works.
