### ISSUE TITLE
Manuscript details: 'origin'

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#248]
1. The field 'origin' should be moved down, to between 'literature' and 'provenances'.

1. It should be possible to enter locations, places and names, just like with 'provenance', instead of just places. Ideally also with a literature reference.

**Comment by ErwinKomen** [comment]
1. Moved the field `origin` to the new location (between literature and provenances) - _13/Aug/2020_
1. Manuscript's origin:
    1. Fixes to `origin`
        1. Renewed Edit and Details view to 'modern' look
        1. Repaired OriginOneWidget to make sure it really shows the origin
    1. Manuscript's origin should point to **origin** (it was pointing at **location**, which was wrong)

It is now (again) possible to:
1. Select the correct **origin** in the Manuscript details view
1. Add origins through (a) the button Origins, or (b) Tools > Origin
