### ISSUE TITLE
Sermon: wrong automatic Gryson/Clavis shown

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#249]
Menna:

> 1.	De automatische Gryson- en Claviscodes die worden getoond komen niet overeen met de gelinkte SSG, een voorbeeld (= https://passim.rich.ru.nl/sermon/details/55397/): 
De edities kloppen wel met de gelinkte SSG. Dit betekent ook dat de manifestaties niet op Gryson/Clavis zoekbaar zijn.

**Comment by ErwinKomen** [comment]
THe problem was/is a complex calculation of the correctly linked S > SSG > SG > `Signature`
See models.py, `SermonDescr`, method `get_eqsetsignatures_markdown()`

I think I've solved it now.

**Comment by MennaRempt** [comment]
Bij de sermon details is het nu inderdaad in orde! In de tabel met manuscript contents worden nog wel verkeerde Clavis/Gryson-codes getoond bij 'Gryson A'.

**Comment by ErwinKomen** [comment]
See issue #252
