### ISSUE TITLE
SSG: give option to not copy author when elevating SG

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#250]
Shari: "bij 'elevate' van een SG tot SSG: kopieer enkel incipit/explicit automatisch, geef keuze 'wil je ook auteur kopiëren of auteur handmatig toevoegen?' – dit om te vermijden dat PASSIM-code wordt aangemaakt en meteen irrelevant wordt omdat we auteur aanpassen (van pseudo-xxx naar dubius bv.( en er dus meteen een andere PASSIM-code moet aangemaakt worden".

**Comment by MennaRempt** [comment]
Dit issue graag met prioriteit behandelen, dan kan ik namelijk gaan beginnen met de SSG-lijst opschonen :-)

**Comment by ErwinKomen** [comment]
Okay, I added a button "Elevate simple", which only elevates inc+exp.
