### ISSUE TITLE
Collection: models for SuperSermonGold, Sermon & Manuscript

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#26]
Create three (or four) separate `Collection` models for:

1. SuperSermonGold (SSG)
2. SermonDescr (SD)
3. Manuscript (M)
4. SermonGold (SG) (possibly)

These collections have the following characteristics:

1. Name
2. Owner
3. Link to a number of instances of SSGs / SDs / Ms / (SGs)
4. ReadOnly flag (used for collections we make ourselves)
5. Short description
6. Link to a description or bibliography (url)

**Comment by ThijsRU** [comment]
Hiermee bezig

**Comment by ThijsRU** [comment]
The Collection model should link to the Super Sermon Gold (SSG) instead of SermonDescr.

**Comment by ThijsRU** [comment]
The models are ready, this issue can be closed.
