### ISSUE TITLE
PD collection: other listview wish list

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#267]
See issue #259 point 13:
> Once a personal dataset is built, the visualisations of the list view should be as follows:
> 1. From a dataset of SSG’s, you should be able to switch to the view of all Manifestations associated with this dataset of SSG’s.
> 1. At the top of the page should then be the filter options for Manifestations instead of the filter options for SSG’s.
>
> Once you’ve executed a filter on the dataset, you need to be able to switch back to the SSG-list view, which is now updated based on the filter.
> 1. Switching list views should be possible between [Sermon] Manifestations, SSG’s and Manuscripts, each of them with all filters as already available in the regular search view.
> 1. Again, there should be the option to save each filtered dataset,
> 1. but also to save as (so you can keep both original dataset and the new dataset after filtering).

**Comment by ErwinKomen** [comment]
Okay, I am not sure what needs to be done here, and if the request is doable at all.
What I've done now:
1. Added four "listview" buttons shown with a historical collection and a personal dataset
    1. Manuscripts - The manuscript listview filtered on this HD/PD
    1. Sermons - The sermon [manifestation] listview filtered on this HD/PD
    1. Gold - The sermon gold listview filtered on this HD/PD
    1. Super - The super sermon gold listview filtered on this HD/PD

What I _can_ do, is provide additional listviews or a SSG dataset:
1. A listview of the "manuscripts with sermons connected to this SSG dataset"
1. A listview of the "sermon [manifestations] connected to this SSG dataset"

Manipulation of a SSG dataset
---------------------------------
Manipulation can be done right now by adding or removing SSGs to/from the SSG dataset, and this should be done in the regular SSG listview. That is the place where the user can filter using whatever means are available to come up with a selection of SSGs.

If needed, the following manipulations can be added to the list of SSG shown in a Dataset Details View (private or public dataset):
1. Ordering SSGs in the list and saving that order (as is done with datasets of manuscripts)
1. Removing SSGs from the collection (as done with the datasets of manuscripts)

What I fail to see
------------------
Suppose that a personal dataset of SSG not only has a list of its SSGs, but also these following two lists:
1. List of sermon (manifestations) associated because of the SSGs in the dataset
1. List of manuscript with sermon (manifestations) associated with SSGs in the dataset

Then the removal of a sermon (manifestation) or a manuscript from such a list is problematic, because:
- It does not necessarily lead to the removal of the associated SSG, if the SSG is also associated with a different sermon (manifestation) or manuscript in the list
- The removal of the sermon (manifestation) or the manuscirpt **cannot** be 'remembered' by the system, because the PD _only consists of a set of SSGs_, and not of a set of sermons or manuscripts. The latter are only 'available' upon association, via-via.

Please advise how to proceed.

**Comment by MennaRempt** [comment]
> What I can do, is provide additional listviews or a SSG dataset:
> 
> A listview of the "manuscripts with sermons connected to this SSG dataset"
> A listview of the "sermon [manifestations] connected to this SSG dataset"

How are these listviews different from the listviews provided in i. and ii. above? Is this in the PD environment itself? If so, yes, please add these listviews, but without the option for manipulation OR giving the option for manipulation but the only 'save' option as saving as a new PD. (it should be clear before manipulation starts that the manipulation will not influence the original dataset!)

> If needed, the following manipulations can be added to the list of SSG shown in a Dataset Details View (private or public dataset):
> 
> Ordering SSGs in the list and saving that order (as is done with datasets of manuscripts)
> Removing SSGs from the collection (as done with the datasets of manuscripts)

Yes, please add this, if possible for all types of PDs (replace 'SSGs' with relevant item).

For the rest, manipulating the sermon manifestations or manuscripts associated with a SSG dataset can currently be done through going to the listview (either from the PD or by filtering on the PD), creating a basket with the manipulated list of results and creating a new PD. This is fine how it is; it is the responsibility of the user to make it clear to themselves that the two PD's are related, either through the name they give the PD or through the description they can add.

**Comment by ErwinKomen** [comment]
Okay, I've only done this:

> Yes, please add this, if possible for all types of PDs (replace 'SSGs' with relevant item).

The rest can be handled by using the listviews and basket manipulations
