### ISSUE TITLE
Collection: actions

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#27]
Add a number of actions related to `Collection` instances:

1. Create a collection (manually, for Super Sermon Gold / SermonDescr / Manuscript / (Sermon Gold)
2. Add a Super Sermon Gold / SermonDescr / Manuscript / (Sermon Gold) to a collection
3. Remove a Super Sermon Gold / SermonDescr / Manuscript / (Sermon Gold) from a collection
4. Remove a collection
5. Export a collection (to be used by colleagues)
6. Create a collection by importing it
7. A collection of one of the 4 entities should be visualized in the list view of one the other entities (using the filtering options).
8. The entities of that list view that are linked to the entities in a collection should be visualized, filtered and subsequently be stored as a separate collection, using the basket system. 
9. The system should store the paths to a certain query/filter.

**Comment by ThijsRU** [comment]
- Add Super Sermon Gold (SSG) to a Collection (instead of SermonDescr)
- Remove a SSG from a collection





Add a number of actions related to Collection instances:

    Create a collection (manually)
    Add a sermon(descr) to a collection
    Remove a sermon from a collection
    Remove a collection
    Export a collection (to be used by colleagues)
    Create a collection by importing it

**Comment by ThijsRU** [comment]
These sub-issues are ready: 1-4, 7 and first two (of three) parts of 8. Adding the newly filtered collection to a new collection via the Basket needs to be done after the Baskets are added to the other entities (M, SSG, SG). 

5-6 need to be changed: share with team or every user, instead of import/export. Please view the newer issues regarding the Collection milestone. 

9: to be done

**Comment by ErwinKomen** [comment]
9: done (EK, 6/apr/2020)

**Comment by ErwinKomen** [comment]
TODO:
10. **Append** the contents of a basket to an existing collection
