### ISSUE TITLE
Sermon: bible reference

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#284]
The field "bible reference(s)" should be changed into a drop-down menu/restricted field rather than a free text field, with three fields:

1. Bible book (I have a document for the abbreviations we want to use)
1. chapter
1. verse 

It should be possible to add multiple bible references, and make a note about which part of the sermon the reference refers to.

There are already bible references added into the field for some sermons, which should not be lost when changing the field, but it is fine if they're moved to the notes temporarily.

**Comment by MennaRempt** [comment]
Not all fields have to be filled out for a reference to be valid

**Comment by ErwinKomen** [comment]
Implementation details
===============

1. Phase 1: **parsers**
    1. Add field `verses` which holds a JSON rep of the verses in field `biblref` - _done_
    1. Write parser to convert content of `bibleref` into object for `verses` - _done_
    1. The parser must also provide the 'viewable text' representation of `verses` in field `bibleref`
        1. Write converter from `verses` to `bibleref`
        1. Implement in production
1. Phase 2: **editing**
    1. Extend view `SermonEdit` to enter bib refs in the form of bk/ch/vs
        1. Allow entering Book, Chapter-range, Verse-range
1. Phase 3: **operationalization**
    1. Remove _editing_ possibility from the field `bibleref` (so it becomes **view only**)
1. Phase 4: **testing**
    1.

**Comment by ErwinKomen** [comment]
TODO:
1. Add listview and details view for `BibRange`
1. Allow linking through to Bibrange from Sermon details

**Comment by ErwinKomen** [comment]
More related issues for these Bible references:
1. Right now the Bible References listview is not taken up in the Tools menu. Should it be? Non-editors don't have editing rights for Bible References, they can only view them.
1. Reflist visualization: right now a list of chapters is shown e.g. as 1:1-8:14, but it should really ideally be Sng 1-8

**Comment by ErwinKomen** [comment]
As for point (2) above:
1. Starting point: seeker/models.py, `SermonDescr`, method `do_ranges()`
1. The conversion from a list of scripture references to ChVsList: `book, chvslist = oRef.get_chvslist(oScrref)`

**Comment by ErwinKomen** [comment]
As for point (3): works!!
And when a user passes on a non-existing reference, the result is empty.
