### ISSUE TITLE
Sermon: feast

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#285]
The field "feast" on the sermon details page should be a drop-down menu (like the 'keywords' field) instead of a free text field. 

There should also be a list of feasts under tools, with three columns: 
1. English name (this is the one shown in the "feast" field) 
1. Latin name
1. feast date (free text, as some feasts are movable rather than have a fixed date)

The feasts already entered in this field should be automatically changed to appear on this list, if possible.

**Comment by ErwinKomen** [comment]
Actions:
1. Add model object `Feast` with fields: `name`, `latname`, `feastdate` (free text)

**Comment by ErwinKomen** [comment]
I think a listview of the sermons affected should be added to the Feast details view. That would be better than just a list of sermons.
