### ISSUE TITLE
Manuscript hierarchy: issue with deleting sermons

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#286]
When a sermon is deleted, an empty hierarchical bar remains, that is immovable and cannot be deleted.

**Comment by ErwinKomen** [comment]
I addressed this, and it should work properly now. 
It was a side-effect of adding the structural elements.

New feature: after deleting a sermon, the screen will return to the Manuscript Details view (if there is still a manuscript left)
