### ISSUE TITLE
Search: bible reference

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#287]
Option to search for bible references everywhere where you can search for other sermon characteristics. It should be possible for the search to get more precise: for example, searching for only Luc. will get all sermons with references to the gospel of Luke, regardless of chapter/verse; searching for Luc. + 1, all sermons with reference to Luke 1, regardless of verse; searching for a complete reference (e.g. Luc. + 1 + 7) only gives sermons with reference to that specific verse (but what to do with from–to references? e.g. a sermon with Luc. 1:1-10 as reference should be a result for searching for Luc + 1 + 7)

(Shari: "make sure you can search for Bible references: three fields (and you don’t have to fill out all of them, so you can search for all instances in the database for the Book of Psalms without specifying a Psalm)"

**Comment by ErwinKomen** [comment]
The first step has already been done with issue #284. That issue explains that searching (filtering) has been added to the SermonListView (sermon _manifestations_). 
What are the other places where searching is possible for 'sermon characteristics'?
1. Manuscript listview, 'Sermon' filters (there's currently only one: Gryson/Clavis)
1. Historical collection listview: 'Sermon' filters (a whole row of them now)
1. **SSG** Super sermon gold listview: **no** sermon filters
1. **SG** Sermon Gold listview: **no** sermon filters

**Comment by ErwinKomen** [comment]
**Next step**: make sure the user can select a book from a list (select2).

**Comment by ErwinKomen** [comment]
Okay, that's working now.
