### ISSUE TITLE
SSG: unable to mark as approved

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#290]
It isn't possible to mark SSGs as 'approved'; after saving, the status reverts back to 'edited'.

**Comment by ErwinKomen** [comment]
Okay, I repaired this for SSG.

**Comment by MennaRempt** [comment]
Does not work yet, either for SG or for SSG.

**Comment by ErwinKomen** [comment]
See for example: https://passim.rich.ru.nl/ssg/details/1517/

**Comment by ErwinKomen** [comment]
I fixed this for both SSG as well as SG.

SSG: remove 'code' from the list of inspected elements (stype_edi_fields)
SG: remove 'authorname' from the list of inspected elements
