### ISSUE TITLE
Sermon: sorting results when linking SSG

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#292]
Currently when searching for a SSG to link to a sermon manifestation, the results are sorted by PASSIM-code. It would be more intuitive if they were sorted by the "best match" to the search terms used. 

(if this is not possible, we just have to explain that they are sorted by PASSIM code in the data input manual)

**Comment by ErwinKomen** [comment]
Okay, well, the question here is what constitutes a 'best match'.
I guess we first of all need to look at the distance/difference in `incipit` and `explicit`

**Comment by ErwinKomen** [comment]
Okay, works

**Comment by ErwinKomen** [comment]
It's going too slow, and it doesn't deliver when the user wants to make use of it.
THe latter case is: when the user creates a new SermonDesc, fills in the inc/expl, the comparison should already be available. Ideally.

**Comment by ErwinKomen** [comment]
Clarification as to the original request (which I had misunderstood a bit:)...):

> als je daarin aan het typen bent. Dit kan ook door middel van Gryson/clavis-codes of auteur zijn (ik gebruik vaak een combinatie van auteurs-code/(deel van) Gryson-code (als ik denk dat de auteursattributie van het handschrift waarschijnlijk klopt met de huidige overeenstemming) en (delen van) de incipit/excplicit), maar dat is hier minder belangrijk, want die zijn "unieker". Het probleem is dat als je bijvoorbeeld begint met een incipit typen, en de eerste paar woorden daarvan vaker voorkomen (of in een andere volgorde in incipits/explicits) alle resultaten getoond worden, en dat die resultaten op PASSIM-code werden (worden?) gesorteerd (of dat is iig wat Riccardo had opgemerkt), ongeacht of de precieze volgorde meer overeenkomt met één bepaalde SSG. Dus als je bijv. "fratres carissimi dominus" typt, krijg je niet per sé de SSGs waarin de woorden in die volgorde voorkomen verder bovenaan te zien dan SSG waarin alle woorden ook voorkomen, maar in een andere volgorde. 
>
> Om een ander voorbeeld te geven, wanneer je dus wel met alleen een Gryson-code probeert om een SSG te linken (bijvoorbeeld als die informatie in de catalogus wordt gegeven), en je bijv. "AU s 9" intypt, krijg je alle SSGs te zien waar 'au', 's' en '9' ergens in de code, auteur, incipit of explicit te vinden is... oftewel héél veel. Wat ik zou willen is dat de resultaten dus worden gesorteerd met eerst alles waarbij "au s 9" achter elkaar te vinden zou zijn, en daarna pas waarbij de verschillende onderdelen van de zoekopdracht in andere volgordes te vinden zijn. Nu moet je namelijk of apart de PASSIM-code opzoeken, of een (deel van) de incipit/explicit weten (wat niet altijd het geval is), of toevallig weten dat de code "CPL 284.9" naar dezelfde SSG verwijst, of heel ver doorscrollen in de lijst met resultaten.

**Comment by ErwinKomen** [comment]
Undoing what I did so far:
1. `SermonDescrSuperForm`:
    1. Remove the `newsuperdist` variable, replacing it for the earlier `newsuper`
    1. Divide into two options, depending on `method` being `nodistance` or `superdist`
