### ISSUE TITLE
Manuscript: exact date

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#293]
Currently it is only possible to add a date range (and search for a date range), but there are manuscripts that we have an exact date for. It should be possible to add only year. These manuscripts should then be found when searching for a date range that includes that year. 

(or do we have to just add the same year both as from and as until?)

**Comment by ErwinKomen** [comment]
Okay, so 'exact' here means: **one specific year** (as opposed to a complete date dd/mm/yyyy)
