### ISSUE TITLE
Listviews: sorting by header

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#294]
Sorting any listview by clicking the headers does not always work as expected. It should sort alphabetically (or numerically) when clicking the header once, and in reverse alphabetical/numerical order when clicking the header again.

**Comment by ErwinKomen** [comment]
I have noticed this problem too.
I agree that the expected behaviour should be:
1. Sort alphabetically (or numerically) when:
    1. clicking the header **once**
    1. provided the list is _not yet sorted_ according to this particular column
        1. If the column is already sorted alphabetically, then the proper action should be: reverse order
1. Reverse order when clicking the header a second time

**Comment by ErwinKomen** [comment]
Research...
1. What happens when the user clicks a column: call to JS `ru.basic.searc_ordered_start('o=N')` (where N is the number of the column)
