### ISSUE TITLE
Sermon: manual Gryson/Clavis

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#296]
Currently it is only possible to manually add Gryson/Clavis codes that are already present in the database (i.e. connected to a SG). It should also be possible to add Gryson/Clavis codes that are not yet present in the database (in practice this will mostly be Clavis codes), for texts that we do know a code for, but do not want to add into the database as a SSG (e.g. saint's lives, historical texts etc.).

**Comment by ErwinKomen** [comment]
Current linking of Gryson/Clavis signatures: 
1. **Automatic**: table `Signature` links to `SermonGold`
1. **Manual**: table `SermonSignature` links to `SermonDescr`

TODO: provide '+' button and **formset** for `SermonSignature` in the `SermonEditView`

**Comment by ErwinKomen** [comment]
Notes to take care of:
1. When a new `SermonSignature` is created, a possible link with `gsig` should be checked
1. When a new `Signature` is created, all `SermonSignature` items must be checked to see if a link from there to Signature (via `gsig`) is needed

**Comment by ErwinKomen** [comment]
Seems to work okay
