### ISSUE TITLE
Manuscript contents: Gryson A/M

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#297]
In the list of manuscript contents, Gryson A (automatic Gryson/Clavis-codes) should be shown as standard rather than Gryson M (manual Gryson/Clavis-codes).

**Comment by ErwinKomen** [comment]
View: `ManuscriptDetails`
Is this perhaps arranged in template `manuscript_sermons.html`?
1. Is it in the setting of class `jumbo-1` versus `jumbo-2`?
    1. Partially:: this only sets the buttons, not the contents!
    1. The other part: hard setting in template `sermon_view.html`

Okay, works
