### ISSUE TITLE
Manuscript: field for notes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#298]
Adding an extra field to the manuscript details page for notes (= free text field):

Shari: "Is het mogelijk om voor manuscripten in het allemaal ook een notes veld aan te maken (bv. te plaatsen tussen provenances en external links in het overzicht) en die info over anciennes cotes daar dan in te zetten?"

Thijs: "een extra veld of table (…) waarin extra informatie gerelateerd aan het manuscript opgeslagen kan worden"

For now, only with team visibility, though depending on the type of information entered it might have to be made visible for all users at a later stage.

**Comment by ErwinKomen** [comment]
Implementation notes:
1. Added field `notes` (textfield) to model `Manuscript`
1. Migration done
1. Add field `notes` in `ManuscriptForm`
1. Visibility in manuscript details through view `ManuscriptEdit`:
    1. Only if user belongs to the group app_editor
    1. Then show and allow edit access
