### ISSUE TITLE
Manuscript: remove daterange fields

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#300]
The fields `yearstart` and `yearfinish` in Manuscript are outdated. 
All date ranges are now stored in the `DateRange` object.
Action: 
- remove the outdated fields from the table for clarity
- first test this in the development environment to make sure nothing goes wrong

Notes
-------
The original `yearstart` and `yearfinish` in Manuscript are still used in some situations:
1. Filtering in the listview of manuscripts

The situations above need to switch to the new `DateRange` object before the fields can be removed!

**Comment by ErwinKomen** [comment]
ManuscriptListView:
1. Listview fields 'from' and 'until' correctly use the DateRange object
    1. THe table `searches` correctly makes use of `manuscript_dateranges__yearstart` etc
1. uses form `SearchManuForm`.
    1. The form still has model fields `yearstart` and `yearfinish`
    2. Removing them: searching still works okay
1. Editing manuscript: can add date range

**Comment by ErwinKomen** [comment]
Okay, they are not used anymore, but remain present in the table `Manuscript`

**Comment by MennaRempt** [comment]
The 'date from' and 'date until' fields are still present in Sermons > Manuscript…

It should be changed to 'Date range' here too.
