### ISSUE TITLE
S: location ("city")

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#304]
Non-city locations currently are not visible in the manuscript listview. To change that, please implement the following: "Afspreken dat als je op “city” zoekt ook alle onderliggende locatietypes worden meegenomen (dus city == city, village, library, monastery)" (email from Erwin 14-10-2020)

cf. email from Riccardo 20-10-2020: "we do not have to think of the location name as either a "city" or something else – which is not that important –, but rather as the place (in general) where the library is located." ––Perhaps change "city" into "location"?

**Comment by ErwinKomen** [comment]
I changed the **listview**:
1. The column with the City is now City/Location
    1. Note that the ordering is a bit odd, because first the 'library.city' field is taken and then the 'library.location' field. That's why Montecassino now ends up in the beginning.
1. The filter for **city** now looks in both 'library.city' as well as in 'library.location'
2.
