### ISSUE TITLE
SSG to manifestation link

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#307]
Iris: Bij de Manuscripten op de SSG details pagina werkt het niet meer om, als je op de folia klikt, rechtstreeks naar de sermon pagina te kunnen; je wordt nu automatisch naar de algemene pagina van het handschrift gebracht.

**Comment by ErwinKomen** [comment]
See issue #216.
But it is a small matter to change this: the **item** now points directly to the Sermon itself.
