### ISSUE TITLE
SSG: create basket does not work

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#308]
Iris: Ik kan geen 'basket' meer creëren in de SSG omgeving (vroeger lukte dat wel, maar ik maakte de bestaande basket leeg en nu werkt het niet meer). Als ik op 'create' klik, gebeurt er niks.

**Comment by ErwinKomen** [comment]
The problem: an error due to `soperator`

1. Add in forms.py to `SCOUNT_OPERATOR` the 'null' option (_make a choice_)
1. Add more specific test in `search_generic()` to filter out `soperator` when it's empty

Now works okay again
