### ISSUE TITLE
SSG: elevate basic

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#309]
Iris: Bij het gebruik van 'elevate basic' (dus alleen inc en expl) lukt het niet om meteen na het kopiëren van de informatie de fiche te bewerken (door bijvoorbeeld een auteur toe te voegen). Dit werkt wel gewoon bij 'elevate all' (zowel inc, expl als auteur worden gekopieerd en zijn meteen daarna te bewerken). 

I have found the same, it is only possible to use 'elevate basic' if the SSG already has an author, otherwise the SSG is no longer editable, and after refreshing the SSG is cleared and the SGs attached are deleted.

**Comment by ErwinKomen** [comment]
Thoughts...

1. Elevate all/basic: `simple=f` (false) versus `simple=t` (true)
1. Both go to the `goldcopy=XX` section of `equalgold_details`
