### ISSUE TITLE
SSG: 'equals' to itself

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#310]
Some SSGs have an 'equals'-link to themself; this link cannot be removed. Example: [/1456 (PASSIM 08.0805)](https://passim.rich.ru.nl/ssg/details/1456/)

**Comment by ErwinKomen** [comment]
Actions:
1. Allow deletion: adapt code in method `after_save()` of view `EqualGoldEdit`
1. Remove any current self-links
1. Prevent adding self-links

**Comment by ErwinKomen** [comment]
Okay, done
