### ISSUE TITLE
SSG: author not copied with 'elevate all'

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#313]
When using 'elevate all' on a new SSG (no designated author yet), the author of the SG is not copied. 

There are no problems when the SSG does already have an author, in that case all the information, including the author is copied.

**Comment by ErwinKomen** [comment]
Can't reproduce this...

**Comment by ErwinKomen** [comment]
So where are the problems?

Menna:
> Okee, na nog wat meer experimenteren ben ik er achter dat het in ieder geval niet werkt voor 'undecided' (al zouden SGs toch dit toch niet als auteur moeten hebben) en 'anonymus' (wat wél als auteur van een SG kan voorkomen), bijvoorbeeld bij https://passim.rich.ru.nl/ssg/details/950/: die stond al op undecided (automatisch toegewezen omdat er twee SGs in de equality set zitten), en als ik de SG met auteur "Anonymus" wil elevaten, blijft de auteur op Undecided staan. 

Iris:
> bij haar ... inderdaad ook "Anonymus".

**Comment by ErwinKomen** [comment]
This is handled in views.py, `EqualGoldDetails`, method `add_to_context()`, when the gold_id to be copied is passed on inside `goldcopy`.
