### ISSUE TITLE
Template: fields (based on manuscript)

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#315]
Fields that should be copied when creating a template from a manuscript (and creating a manuscript from that template):

- attributed author
- section title
- lectio
- title
- incipit
- explicit
- postscriptum
- feast
- Bible reference(s) (linked! currently appears as text only)
- Note
- Keywords
- Manual Gryson/Clavis-codes
- SSG links (and associated copied information)

So the changes are:
Fields that are currently included but shouldn't be (because they are manuscript-specific): 
- locus
- cod. notes

Fields that currently are not included but should be:
- Bible reference(s) linking
- keywords
- manual Gryson/Clavis-codes

**Comment by ErwinKomen** [comment]
Actions
---
The actual copying takes place in model `Manuscript`, method `load_sermons_from()`
1. Removing fields from copying
    1.

**Comment by MennaRempt** [comment]
> While the fields 'keywords' and 'gryson/clavis' are now copied from the template, the templates themselves do not contain these fields in an editable form. When a template is created, these fields are excluded. They are not 'regular' fields, but relations with other tables.

I think this is fine. The important thing is (for me) that the manuscripts that are created from a template have the information from the original manuscript (that the template was created from)  from all the fields listed above.

**Comment by ErwinKomen** [comment]
Okay, good
