### ISSUE TITLE
MS: details (from template)

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#316]
Two options with the same result, so whichever is easier to implement: 

1. when creating a template from a manuscript, don't copy the manuscript details
2. when creating a manuscript from a template (based on a manuscript), don't copy the manuscript details (except for a note "created from template, see issue #314)

**Comment by ErwinKomen** [comment]
Note from issue #314  that there are two methods of making a manuscript based on a template:
1. Procedure "straight from template" (Tools > Templates > Create)
2. Procedure "import from template" (Search > Manuscdripts > Add > Import)

Assumption: this issue only applies to the procedure **straight from template**

**Comment by ErwinKomen** [comment]
okay,done
