### ISSUE TITLE
Hierarchy: moving items not possible

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#321]
It's no longer possible to move items up or down in the list of manuscript contents.

(it is possible to move items up or down a level hierarchically)

**Comment by ErwinKomen** [comment]
Nothing has changed, it is still possible.
Please see the instruction video at Extra > Guide, bottom

**Comment by ErwinKomen** [comment]
Okay, somehow FF was more lenient, but Chrome had this error, indeed.
The problem was in javascript, in passim.seeker.js, function `sermon_dragenter()`.
I had been testing on `sermon_new` here, and there was an assumption-mistake in there.
Corrected, should work fine now.
