### ISSUE TITLE
Sermon: filtering by Gryson/Clavis

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#323]
Not all sermons that are linked to a certain SSG are found when filtering on Gryson/Clavis.

e.g [MAX] h 11 gives 2 results in the sermon listview, but the SSG shows 6 connected manuscripts

**Comment by ErwinKomen** [comment]
This is very true. Right now the filter on Gryson/Clavis reaches two types of signatures:
1. The sermon-signatures (those manually connected to a sermon)
2. The signatures linked via the goldsermons connected with a sermon

**Comment by ErwinKomen** [comment]
Double checked: this now works
