### ISSUE TITLE
Sermon: template sermons visible in listview

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#324]
Sermons from templates are present in the sermon listview

(Iris: ik zag in de zoekresultaten ook een 'template' als 'sermon' voorbij komen.)

**Comment by ErwinKomen** [comment]
And the implication: that should **not** be the case, so this must be corrected.

**Comment by ErwinKomen** [comment]
I double-checked, and this should not be the case (obviously).
If this happens again I need more data to reproduce: what filters have been used on the sermon listview? Which template was visible?

**Comment by ErwinKomen** [comment]
I extended views.py method `search_generic()` (used by **all** basket operations) to plainly exclude all material that has `mtype = tem` (templates).

That should be enough for now. But the basket system may need to change in the future:
1. Whenever a user does a search, its results (as a stringified JSON list of id's) should be stored in the user's `Profile`
2. Adding, Removing, Creating etc should then take place on the basis of the `Profile`-stored-list-of-IDs
