### ISSUE TITLE
SSG: links in listview

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#327]
The number of links a SSG has to other SSGs should be visible in the SSG listview. It should also be possible to filer SSGs on the number of links.

**Comment by ErwinKomen** [comment]
This means:
1. Add field `ssgcount`
2. Add initialization in th EqualGoldListView
3. Add code to adapt the count when adding and deleting (in models.py, `EqualGoldLink`)
4. Adapt the `EqualGoldListview`
    1. adding a filter for 'ssgcount' and an operator 'ssgoperator'
    1. expanding `adapt_search()` to process ssgcount and ssgoperator
5. Adapt the form `SuperSermonGoldForm` to include ssgcount and ssgoperator

**Comment by ErwinKomen** [comment]
Implemented, and: works
