### ISSUE TITLE
SSG: manuscript table

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#328]
The table with manuscripts on the SSG details page behaves unexpectedly:

- inc and expl fields: every word of the incipit and explicit is shown on a separate line, making each row of the table very tall
- expanding columns doesn't work as designed: 'keyword' expands 'author'; 'expl.' expands 'ff.'; 'inc.' expands 'item'; 'ff' expands 'date'; 'item' and 'date' expand the year in 'or./prov.' (not the actual column); 'coll.' expands the place in 'or./prov.'. 'Shelfmark' and 'or./prov.' work as expected. 

to expand other columns you need to make them bigger manually.

**Comment by ErwinKomen** [comment]
I'm not sure what the mismatching was, but I set a few columns to be a bit more expanded on startup (or/prov, date, inc, expl) so that the table looks better to start with.
