### ISSUE TITLE
S: link to SSG

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#333]
The possibility for different link types between S and SSG should be deleted.

The desired situation is to have a flat link, without any name or specification, just "Link to [SSG]".

(aka: remove the drop-down menu with link types when adding a SSG)

**Comment by ErwinKomen** [comment]
Implementation:
1. THis is in view `SermonEdit`
2. The links from S to SSG are in `StossgFormSet` and go via model `SermonDescrEqual` and form `SermonDescrSuperForm`
    1. First attempt: simpley remove `editable` from `newlinktype` in `SermonDescrSuperForm`
