### ISSUE TITLE
SSG link types

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#336]
[EK: links from SSG to SSG, as on the SSG details page, may consist of] Five components:
1. link type: partially equals, nearly equals, echoes --> required
2. specification: uses/used by (direct link); uses/used by (via know intermediary); common source; unspecified --> optional
3. SSG link --> required
3. checkbox: one of several alternatives --> optional, editable
4. notes (free text field) --> optional, editable

**Comment by MennaRempt** [comment]
Change of the current SSG link types into a new system, consisting of five components (see above). 

    • SSG → required
    • link type: choice between three basic link types → required
        ◦ nearly equals: extensive textual overlap in the whole text, with differences only on the level of sentences; when the reference works give them as part of the same equality set but with a different incipit/explicit
        ◦ partially equals: default, everything that is not ‘nearly equals’ or ‘echoes’
        ◦ echoes: overlap only in a few sentences
    • specification (directional) → optional
        ◦ uses/used by (direct link): text A is the source of text B: A is used by (direct link) B – B uses (direct link) A
        ◦ uses/used by (via known intermediary): text A is the source of text B through text C: 
            ▪ A is used by (via known intermediary) B – B uses (via known intermediary) A;
            ▪ A is used by (direct link) C – C uses (direct link) A;
            ▪ C is used by (direct link) C – B uses (direct link) C
        ◦ common source: for when we know that two texts have a common source, but we do not know what the source was 
        ◦ unspecified: there is more information than that the texts just have textual overlap, but it is not possible to specify a direction of use and the texts directly influence each other, not via a common source (e.g. for versions of texts of which we do not know which is the older version)
    • checkbox: "one of several alternatives": check this box when there are several options for a source (of a part of a text), but it is not clear which of these is the direct source → optional
    • notes: for everything that is not already specified in the link type itself, but that you do want to include → optional

**Comment by ErwinKomen** [comment]
Implementation

1. SSG → required
1. link type: choice between three basic link types → required
    1. nearly equals: extensive textual overlap in the whole text, with differences only on the level of sentences; when the reference works give them as part of the same equality set but with a different incipit/explicit
    1. partially equals: default, everything that is not ‘nearly equals’ or ‘echoes’
    1. echoes: overlap only in a few sentences
1. specification (directional) → optional
    1. uses/used by (direct link): text A is the source of text B: A is used by (direct link) B – B uses (direct link) A
    1. uses/used by (via known intermediary): text A is the source of text B through text C: 
        1. A is used by (via known intermediary) B – B uses (via known intermediary) A;
        1. A is used by (direct link) C – C uses (direct link) A;
        1. C is used by (direct link) C – B uses (direct link) C
    1. common source: for when we know that two texts have a common source, but we do not know what the source was 
    1. unspecified: there is more information than that the texts just have textual overlap, but it is not possible to specify a direction of use and the texts directly influence each other, not via a common source (e.g. for versions of texts of which we do not know which is the older version)
1. checkbox: "one of several alternatives": check this box when there are several options for a source (of a part of a text), but it is not clear which of these is the direct source → optional
1. notes: for everything that is not already specified in the link type itself, but that you do want to include → optional

**Comment by ErwinKomen** [comment]
Questions
---

1. What should happen with the SSG-to-SSG links that now have linktypes 'unspecified' (2503, 2490), 'uses' (2496, 2497, 2629, 1980, 2865, 2490)?
    1. Leave as they are
    1. You will change them
    1. Automatically change into: ???
1. Right now there is no separate list or details view for the SSG-to-SSG links
    1. No need to make them: what is shown in the SSG details view is enough (added 'notes' to a link are visible by hovering over the SSG name)
    1. If there should be a separate list and details view, please add **issues** in GitHub

**Comment by MennaRempt** [comment]
1. Leave them as they are, I will have to go through the links anyway to check if they need to be updated. Very useful to have this list though!
2. No need to have a separate list.
