### ISSUE TITLE
SSG links: bidirectional

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#337]
All links should be bidirectional, and show up on both SSG details pages of the SSGs linked. 

'uses' on page A becomes 'used by' on page B and vice versa.

**Comment by MennaRempt** [comment]
Currently 'uses' links (from SSG A to SSG B) only show up on the page of SSG A, not of SSG B. They should show up on the page of SSG B as 'used by', and it should be able to add these links from either side of the link (so that when you add a 'used by' link from SSG B to SSG A, this shows up as a 'uses' link from SSG A to SSG B)

**Comment by ErwinKomen** [comment]
The bidirectionality should have been working all along already, so I'm not sure where this is not the case (at least for partially equals and nearly equals).

The bidirectionality now correctly assigns the 'specification' types (uses/used by).

**Comment by MennaRempt** [comment]
'uses' and 'unspecified' were not bidirectional, but since these are now specifications for bidirectional links, this doesn't matter anymore.

**Comment by ErwinKomen** [comment]
okay
