### ISSUE TITLE
SSG links: basic link

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#338]
The automatically selected option for links between SSG should be 'partially equals' with no further specifications.

**Comment by MennaRempt** [comment]
Only applies to the links from SSGs to other SSGs. When first adding a link, the by default selected one should be 'partially equals', since this is the one that will be used most often, and is the "basic" link type for when we have no further information. 

(currently the automatically selected link type is 'nearly equals' (because of the alphabetization?))

**Comment by ErwinKomen** [comment]
There was no default set, but I now changed the code in `forms.py`, class `EqualGoldLinkForm`:
```
self.fields['newlinktype'].initial = "prt"
```
