### ISSUE TITLE
SSG links: presentation on page

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#339]
The SSG links should be presented in a table, with the columns as below (but with the author/inc./expl. visible as is currently the case for the SSG links):

 link 			type | directional specification | SSG | one of several alternatives? | notes
 -- | -- | -- | -- | --
 partially 			equals | used 			by | PASSIM 			006.0041 (CAE s 220) |  | cap. 			10-11 for CAE s 220,1-2
 partially 			equals | used 			by | PASSIM 			006.0083 (CAE s 221) |  | cap. 			5-7 for 			CAE 			s 221,2-5
 partially 			equals | used 			by | PASSIM 			051.0337 (PS-AU s 211) |  | cap. 			9-11 for 			PS-AU 			s 211,2-3
   |   |   |  |  

The input when adding a link would ideally also happen in this table, with drop-down menus for the first three columns, a checkbox for the fourth column and a free text field for the notes.

**Comment by MennaRempt** [comment]
As presented on the SSG details page. 

All the SSG information as is currently visible in a link should still be visible in the SSG column in the table, so [PASSIM code] [Gryson/Clavis-codes] [author] [incipit – explicit].

**Comment by MennaRempt** [comment]
with the options that should be available for input:

link type | directional specification | SSG | one of several alternatives? | notes
-- | -- | -- | -- | --
partially equals <br> <br> nearly equals <br> <br> echoes | uses <br><br> used by <br><br> uses (via know intermediary)<br> <br> used by (via know intermediary)<br> <br> unspecified |  |   |

**Comment by ErwinKomen** [comment]
Basically the above has been supplied now with the issues #335, #336

**Comment by ErwinKomen** [comment]
Feedback:
- Kan de 'A' van de alternative links aan het einde van de link komen te staan? (dus na de incipit/explicit van de gelinkte SSG)
- Is het mogelijk dat de notes kunnen worden uitgeklapt? Dit hoeft niet het standaard view te zijn, maar met een plusje o.i.d.. Het is namelijk best mogelijk dat er vrij lange notes komen, en dan is het lastig te lezen als het alleen een pop-up is.

**Comment by ErwinKomen** [comment]
Changed as per the above.
