### ISSUE TITLE
Sermon listview: free text fields

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#349]
> Aangepast zoeksysteem voor free text fields (section title, lectio, title, incipit, explicit, postscriptum, cod. notes, notes): een free text query met de mogelijkheid om een combinatie van verschillende velden te selecteren om tegelijk in te zoeken, met AND / OR / NOT. 
> - Bijvoorbeeld, een zoekopdracht voor "quadragesima#", in section title OR lectio OR title OR postscriptum, but NOT in incipit, explicit, notes. Dit zou volgens mij dan alle sermons moeten teruggeven die in het manuscript toegewezen worden aan een zondag in de vasten voor Pasen ("in dominica x in quadragesima" meestal), zonder dat er preken bij zitten die het woord 'quadragesima' alleen in de incipit/explicit hebben. 
> - vraag: zou dit ook preken geven die 'quadragesima' bijvoorbeeld zowel in de incipit als de section title hebben? Lijkt mij wel, want er wordt wel in section title gezocht, dus dat zou toch die resultaten moeten geven?

**Comment by ErwinKomen** [comment]
But this is already possible using the current system:
1. Clear basket
1. Search for **quadragesima#** in `section title`
    1. Basket create
1. Search for **quadragesima#** in `title`
    1. Basket add
1. Search for **quadragesima#** in `lectio` - _There is **no** such search field right now_
    1. Basket create
1. Search for **quadragesima#** in `postscriptum` - _There is **no** such search field right now_
    1. Basket add
1. Search for **quadragesima#** in `lectio` - _There is **no** such search field right now_
    1. Basket add
1. Search for **quadragesima#** in `incipit`: Basket remove
1. Search for **quadragesima#** in `explicit`: Basket remove
1. Search for **quadragesima#** in `note`: Basket remove

Result: 67 items 
See: [erwin_QUadragesima](https://passim.rich.ru.nl/dataset/public/details/504/)

**Comment by ErwinKomen** [comment]
I added a "Free" text search item with limited possibilities:
1. Specify a search string (in the usual way)
2. Select fields in which the search string must be found (logical 'or': it is in one or more of these fields)
3. Select fields where the search string must **not** be present (logical 'or': if it is in any of these fields, the sermon is drops off)

Tested it on the example search (except for `lectio` -- what was that?).
Result: 67 items

**Comment by ErwinKomen** [comment]
Instructions
===

Complex queries can be made in two ways:
1. Use the **basket** to add results field by field and remove results field by field
1. Use the **free** option to specify a search string that must be present in one of several free fields and may not be present in other fields

**Comment by MennaRempt** [comment]
Current implementation is good! 

comment on the fields searchable: includes fields not shown to users (subtitle, bibliography notes); both lectio and quote are shown (same field?); locus does not need to be included.

**Comment by ErwinKomen** [comment]
Good observations:
1. I removed `Quote` (retaining `Lectio`), since both indeed show to the same underlying field `quote`
2. I removed `Sub title` and `Bibliography notes`, since you're right, they are not part of the normal search and view asset
