### ISSUE TITLE
Modifications to the import procedure of the A+M manuscripts

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#351]
Based on the comments of Menna after the first import some modifications need to be implemented to the script that imports A+M manuscripts: 

- The status of each imported manuscript needs to be changed to 'imported' instead of 'manually created' (Manuscript, stype). 

- For each A+M manuscript "Archives et Manuscrit import" needs to be added to the added as a Keyword. All manuscripts processed with the EAD script can automatically be linked to this Keyword.
 
- The main URL is stored in the manuscript table under URL but that field is not used in in ManuscriptDetail. The URL needs to be stored in ManuscriptExt. 

- The import of the URLs of the scanned bibliographical files is not necessary according to Menna, this part of the procedure is to be deleted. 

- When a manuscript is imported again, the existing DateRange(s) and ManuscriptExt(s) need to be deleted, view handling of Comment. Another option is to use the existing records in the specific tables for a manuscript that already exists in the database, please view Keyword/Provenances.

**Comment by ThijsRU** [comment]
Done:

- For each A+M manuscript "Archives et Manuscrit import" needs to be added to the added as a Keyword. All manuscripts processed with the EAD script can automatically be linked to this Keyword.

**Comment by ThijsRU** [comment]
All these issues have been taken care of. Issue can be closed.

**Comment by ErwinKomen** [comment]
Added download option for  the "processed_manuscripts" of EAD

**Comment by ThijsRU** [comment]
Something goes wrong with the b and c XMLs, some fields are not filled in, it looks like the script stops somewhere, view Latin 789 and 813.

**Comment by ThijsRU** [comment]
Testing the download of the Excel lead to more issues, with the f XML, Latin 1920 looks like 196 but differs, and the second <c> element has no scopecontent. Should be solved. 

But this issue showed that sermhead and sermdescr should be cleared when a manuscript is processed twice

**Comment by ThijsRU** [comment]
After importing the first batch of 26 XMLs locally, the same were imported on the live site. Until further notice this issue can be closed.
