### ISSUE TITLE
M: alignment of items

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#352]
Gleb writes: 
> "The placement of incipits depends entirely on how long the locus is: if it’s just “f. 1”, incipit beginning right after it will obviously be more to the left, than it would be, if it followed a longer locus, “fol. 132r-132r”, for example (screenshot “alignment”). This gives the user an impression of a hierarchy and nested entries. It would not be that big problem if there weren’t any hierarchy, but there is, and sometimes the “intellectual” place that of a piece contradicts (or at least does not correspond) to its presentation. (…)  the hierarchy should be presented only by the locations which will be nested, multi-level, etc., but as for incipits they all should rather be aligned left (they will be divided by some whitespace from the loci)." 
>
> So: the alignment of the items in the list of contents on the manuscript details page should not depend on the length of the loci, but should all be at the same level of indentation (depending on hierarchical level, of course).

**Comment by ErwinKomen** [comment]
Okay, did something...
