### ISSUE TITLE
MS: codicological unit

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#358]
Addition of an intermediarey level 'codicological unit'.
- 'Manuscript' should become 'manuscript identifier'

From the email:
> What we think would be the easiest solution, is to create a new level above the existing manuscript metadata and change the name of the existing set of metadata to associate them with 'codicological unit'

This is because most manuscripts will only have one codicological unit, so we wouldn't have to edit those. We would then only have to go edit composite manuscripts to have the right number of codicological units.

**Comment by ErwinKomen** [comment]
The above has been implemented, but the details are further in issues #359, for instance

**Comment by ErwinKomen** [comment]
### Pending questions
1. What does the following mean: 
> 'Manuscript' should become 'manuscript identifier'

**Comment by MennaRempt** [comment]
The name displayed should be changed from 'manuscript' to 'manuscript identifier'

**Comment by ErwinKomen** [comment]
Okay, I changed the display name in one place:
- `ManuscriptEdit` the `title` - This means it is now shown in the Manuscript details view

If more name changes are needed in different places, those need to be specified a bit more fully
