### ISSUE TITLE
MS/cod. unit: details

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#359]
The fields currently available for manuscript details have to be redistributed for either the manuscript details or the codicological unit details or both:

- Manuscript status; country; city; library; shelfmark; project; personal datasets; literature; external links
- Codicological unit: date; support; extent; format; origin
- Available for both: title; keywords; provenances; notes

Layout:
at the top of the page first the fields with manuscript details, and below that for each codicological uni the fields with cod. unit details. (first all the fields for cod. unit 1, then all the fields for cod. unit 2 etc.)

**Comment by ErwinKomen** [comment]
Okay, all works. Going to kick it off this evening probably!

**Comment by ErwinKomen** [comment]
## Revision
Just a few things, after looking at this together:
1. Show the codicological units by default - _ok_
2. Sermon details: add the codicological unit title in the top right next to the manuscript id
3. User comments: not working? - _fixed_
