### ISSUE TITLE
Cod. unit: contents

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#360]
Each codicological unit consists of a number of sermon manifestations (using current system).

The different codicological units should be separated from each other visually (e.g. with a line indicating the start of a new unit), but still presented as one list. 

It should be possible to move sermons from one codicological unit to another from the list of manuscript contents, e.g. by using the drag-and-drop system currently available for changing the hierarchy of manuscripts.

**Comment by ErwinKomen** [comment]
One question about the following requirement:

> It should be possible to move sermons from one codicological unit to another from the list of manuscript contents, e.g. by using the drag-and-drop system currently available for changing the hierarchy of manuscripts.

Suppose we have a manuscript with velums: 1-2-3-4-5 // 6-7-8-9-10.
It is currently divided into two codicological units:
[1]: 1-2-3-4-5
[2]: 6-7-8-9-10

Suppose this division was wrong, and the first codicological unit should be [1]: 1-2-3-4-5-6-7-8

If I understand it correctly, the user should be able to accomplish this by simply dragging sermon '8' into Codicological unit [1], right? That is to say: codicological units **must alwasy be consecutive**. So the 'border' between units can change, but we can never end up with e.g.:
[1]: 1-2-3-4-5-**8**
[2]: 6-7-9-10

**Comment by MennaRempt** [comment]
in principle, yes, but this depends on how the new sermons are added to the manuscript: are they added to a specific cod. unit, or are they added at the bottom of the list (as is the case now)? If the second, then it should be possible to move them to the desired cod. unit, regardless of whether it's the next one up or down. (and it should of course still be possible to drag and drop sermons to a different place in the manuscript hierarchically, as is now the case, since the sermons may not be added in the same order as they appear in the manuscript.) 

so, if in the second situation, the numbering is the order that the sermons were added in, but no. 8 is actually between 5 and 6 in the manuscript, it should still be possible to move no. 8 to its proper place in the list of contents, regardless of whether that is in the first or second codicological unit. (although i suppose you could move the sermon so that it is the first of the cod. unit, and then move the border, but that would not be very efficient if a manuscript has a larger number of cod. units.)

**Comment by ErwinKomen** [comment]
Okay, I actually was working on issue #359, where I've implemented this issue too, and it should work as described above. Hope to 'switch it on' tonight...
