### ISSUE TITLE
Cod. unit: search options

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#361]
There should be a search option to search within 
a) manuscript identifier (=whole manuscript), 
b) codicological unit, 
c) reconstructed manuscript, 
or any combination of these, with as default 'all'.

When searching for a combination of multiple SSGs (by Gryson/Clavis/PASSIM code) within a codicological unit (so option b above), only sermon manifestations that belong to the **same** codicological unit (when searching in the list of sermon manifestations) / only codicological units containing **all** those SSGs (when searching in the list of manuscripts) should be shown. Otherwise, also sermon manifestations **across** codicological units can be shown.

**Comment by ErwinKomen** [comment]
Please specify **WHERE** this search is taking place.
Is it in the listview of:
1. SSG
2. Sermon (manifestation)
3. Manuscript

**Comment by MennaRempt** [comment]
It should be possible for both the sermon manifestation listview and the manuscript listview.

**Comment by ErwinKomen** [comment]
### Manifestation listview
Functionality for this view restated from above:
1. Manuscript type restriction: `mtype`, which can be `man` or `rec` (or both, via a regex perhaps?)
1. Codicology **scope**: 'restricted' (to all via one codico) or 'across' (everything under the umbrella of a manuscript)


### Sermon listview
1. A

**Comment by ErwinKomen** [comment]
### Usage notes

1. The `Manuscript` listview has an additional filter option called "Manuscript" (=manuscript type), which allows fine-tuning on "reconstructed" or "manifestation" manuscripts (manifestation manuscript = manuscript identifier)
2. The `Sermon` listview also has this additional filter. It is under Manuscript... > Manuscript Type
