### ISSUE TITLE
MS: reconstructed manuscripts

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#362]
There should be the possibility to reconstruct a medieval manuscript that has since been dismantled, with its parts (codicological units) now belonging to different manuscripts. This is done by adding already in the database described codicological units to this reconstructed manuscripts. 

Codicological units in a reconstructed manuscript should be shown/linked/copied without the sermon manifestations and SSG links appearing in the database multiple times. 

Reconstructed manuscripts still has to be findable in the database.

**Comment by ErwinKomen** [comment]
Added `mtype` with value `rec` (Reconstruction) to the FieldChoice table

**Comment by ErwinKomen** [comment]
### Codicological units and reconstructed manuscripts
A reconstructed manuscript 'binds' **existing** codicological units.
This means that **no new** codicological units should be created for reconstructed manuscripts.
However, right now each codicological unit belongs **exactly** to one (and only one) manuscript.
Solution: create a new table `Reconstruction` that 
- just consists of foreign keys (pointers) to the reconstruction `Manuscript` and to the used `Codico`
- and that contains an `order` fields to be able to have the order of codicological fields within this manuscript (Note that the `Codico` itself also contains an `order` field, but that is for the order of the codicological unit within the 'real' manuscript it is part of)

### Creating a reconstructed manuscript
Some possibilities and problems:
1. Create reconstructed manuscript through Search > Manuscript > Add new manuscript
    1. Problem with this is that 'by default' a new empty codicological layer is created, but that's not what the user wants. The user wants to take one codicological layer as the basis of a new manuscript surely.
    2. It could be possible to have a (one-time?) button on the newly-created-manuscript with 'turn this into a reconstructed manuscript'. But that would then need to lead to the selection of a codicological unit as a 'basis'. This leads to the question how best a codicological unit can be selected (using select2, I would say). Probably only in two steps: (a) manuscript, (b) codicological unit within that manuscript. That needs much more thought.
1. Create reconstructed manuscript from a button within a codicological unit
    1. This is relatively easy: by taking the codicological unit as a basis, the new reconstructed manuscript could be created

###

**Comment by ErwinKomen** [comment]
Okay, implemented the above

**Comment by ErwinKomen** [comment]
Additional sub tasks here...

### Adding a codicological unit to a reconstructed manuscript
Try and make this available _from within the reconstructed manuscript_.

Related tasks (see issue x):

### Removal of codicological unit from a reconstructed manuscript
Add a 'disconnect' (or something) button that allows removing/disconnecting a codicological unit from a reconstructed manuscript

### Reordering of codicological unit within a reconstructed manuscript
Allow a user to move a codicological unit into a different order (within a reconstructed manuscript)

**Comment by ErwinKomen** [comment]
### Implementation: adding a codicological unit to a reconstructed manuscript
1. forms.py
    1. Add `CodicoOneWidget`
1. models.py
    1. Add method `get_identification()` to model `Codico`

**Comment by ErwinKomen** [comment]
Okay, I added the possibility to add an **existing** codicological unit to a **reconstructed** manuscript.

**Comment by ErwinKomen** [comment]
Change the output of `get_identification()` (see above) from:

manuscriptIdentifer ‘_’ codico volgnummer ‘_’ codico title ‘_’ beginpagina-eindpagina
 
into:
 
                manuscriptCity+Library+Identifier ‘_’ codico volgnummer ‘_’ beginpagina-eindpagina

**Comment by ErwinKomen** [comment]
Now working!
