### ISSUE TITLE
cod. unit: link to historical collection

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#363]
The association between HC and manuscripts would have to be changed to an association between HC and cod. units, i.e. the list with "manuscripts with sermons connected to this collection" has to become a list of codicologial units with sermons connected to the collection.

**Comment by ErwinKomen** [comment]
### Implication(s) for implementation
This means that individual **sermons** need to have an association with a particular `Codico`. So `MsItem` should have both a link to `Manuscript` as well as `Codico`

**Comment by ErwinKomen** [comment]
### Questions
1. Right now _internally_ there is a link table between **manuscript** and **collection** (HC). Should that change into a link table between **codicological unit** and **collection** (that is, at the core-level of the database)??
1. The list view showing **Historical collections** (i.e. Search > Collection) - any changes there?
    1. What should happen to the buttons under 'manuscript' (i.e. create either a manuscript or a template based on the historical collection)? I assume this will need to stay the same, except that a new manuscript automatically gets a new codicological unit inserted, right?
1. Clicking through from that listview to one particular HC (details view), the changes needed there:
    1. Changing the title "Manuscripts with sermons connected to this collection" into "COdicological units with sermons connected to this collection" - is that just superficial, or what should change in the list itself?
1. Would you like all "manuscript collections" to be transformed into "codicological unit collections"?
    1. The possibility to work with manuscript collections then disappears and is replaced by codicological unit collections
    2. Any other implications?

**Comment by MennaRempt** [comment]
1. This depends on whether it's needed for the implementation of the next questions... 
2. no changes to this view
i. yes, "create a new manuscript then means "create a new manuscript with a codicological unit containing this collection"; the same goes for template: a new template manuscript with one codicological unit containing the collection. (the same goes for these buttons on the HC details view)
3. the title has to be changed, but also the codicological units have to be shown rather than the manuscripts themselves. 
4. I don't understand what you mean by 'manuscript collections'. Is this the personal dataset? if so, it doesn't have to disappear but perhaps the possibility for a dataset with codicological units can be added? @shariboodts what do you think?

**Comment by ErwinKomen** [comment]
### Implementation
1. The creation of a HC was already going well, with Codico created and linked by default. But I've made this more explicit in the model `Collection`, method `get_hctemplate_copy()`

**Comment by ErwinKomen** [comment]
(I think this is handled now???)

**Comment by MennaRempt** [comment]
This has been implemented and seems to work well. I have no more comments or questions on it, so in my opinion the issue can be closed.
