### ISSUE TITLE
SSG visualisation download: watermark

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#381]
Include a (subtle) watermark (e.g. the PASSIM logo) and time/date stamp on downloaded visualisations (all formats).

**Comment by ErwinKomen** [comment]
Okay, I created a watermark insert for SVG.

Where to insert the watermark SVG?
Perhaps: `EqualGoldOverlapDownload`??

**Comment by ErwinKomen** [comment]
Everything was okayed, so this issue can be closed
