### ISSUE TITLE
Technical page: additions

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#382]
Please check if there is anything on the ELM database's technical page ([https://elmss.nuigalway.ie/about/technical](https://elmss.nuigalway.ie/about/technical)) that would be useful to include on the technical page in Passim. If there aren't any additions necessary, it's fine as it is now.

**Comment by ErwinKomen** [comment]
Possible additions:
1. Mention 'web browser' and say something about requirements
2. Mention the sources for data visualization

**Comment by ErwinKomen** [comment]
I added all of the points above (I didn't add anything on **license** info)

**Comment by ErwinKomen** [comment]
Also added the image created by Ger. Very nice!
