### ISSUE TITLE
PRE: saved items

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#385]
It should be possible to have a list of saved items (Manuscripts, Sermons, SSGs, Historical Collections, Public Datasets) in the Personal Research Environment ("My Passim"). 

It should be possible to save items from:
- the listview (see #386) 
- the item details page
- (low priority) the Personal Research Environment by way of a “quick add” option (drop-down menu) 

It should also be possible to: 
- sort the saved items
- group saved items together
- select saved items to add to an existing personal dataset
- to delete items from the list of saved items.

**Comment by ErwinKomen** [comment]
Trying to understand this... 
It is possible right now to have 'saved' Historical collections, Public datasets and Personal datasets.
Where in the current Passim application is it possible to **save** a Manuscript, Sermon or SSG?

Or is a 'saved manuscript' the same as a personal-manuscript-dataset consisting of one manuscript, for instance?

**Comment by MennaRempt** [comment]
Right now it is only possible to save items by adding them to a personal dataset. What we want is to be able to "favourite" items, as it were, without having to add them to a dataset, and to be able to view a list of all the favourited items in the PRE. 

But we can also say in the user manual that users have to use the PDs to save items, e.g. by making a dataset for each category and calling them something like "Saved SSG" "Saved MSS". It would just be more user friendly to have the option to save items directly without having to first make a PD. It would also facilitate later stages of the DCT, when DCTs with multiple types of source-lists will be an option.

**Comment by ErwinKomen** [comment]
### Implementation

1. Made areas in MyPassim collapsable with an indicator as to their status - that way one can get a better feeling of what's up

**Comment by ErwinKomen** [comment]
### Remaining issues

Two things remain, and they have been turned into separat issues
1. "Group saved items together"
    1. Not entirely sure what this means... See issue #429 
1. "Select saved items to add to an existing personal dataset."
    1. But 'personal datasets' are itemtype specific (e.g only M, only S, only SSG and so on), while saved items are generic (they can be of any itemtype). See issue #386
