### ISSUE TITLE
Listview: selecting items

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#386]
For the Sermon, SSG, Manuscript and Historical Collection listviews, there should be a way to select one or more items (e.g. check-boxes as a final column of the listview). 

After selection of one or more items, the following bulk-manipulation options should be available: 'add to basket'; 'add to DCT'; 'save' (in the Personal Research Environment ("My Passim"), see #385)

**Comment by ErwinKomen** [comment]
Ahum..., the 'save' option has been implemented as checking a star for each item (S, SSG, M, HC) in the listview (see issue #385).

But the other options should still be added..!

**Comment by ErwinKomen** [comment]
This could be implemented approximately like the W.A. web listview of messages:
1. A button to come into the select messages mode 
    1. When this is selected, a column is prepended with checkboxes
    2. Grayed out possibility icons appear ("mark with star", "remove", "forward to others")
    3. An 'X' appears left below, which is a button to leave 'Selection mode'
1. As soon as at least one checkbox has been selected
    1. The possibility icons are activated ("mark with star", "remove", "forward to others")
    2. The number of selected items appears to the right of the 'X' button

**Comment by ErwinKomen** [comment]
### Implementation

1. General support for this
    1. Added model dct `SelectItem`
        1. Did a migration online + got migrated DB
    1. Added JS `do_selitem()` function
    1. Added dct view `SelectItemApply` to process selection and de-selection
    1. Added view function `get_selectitem_html()` to show the button and the form in the listview
        1. Alternative would be to put all of this into basic.list...
1. Specific for `Manuscript`
    1. Added **select** column (autohide) to the listview
    1. Added 'select' custom processing in `get_field_value()`

TODO: Buttons to enter and exit select message mode (instead of manually using hidden columns)

**Comment by ErwinKomen** [comment]
**1/sep**
1. Functionality for 'add to saved items'...
    1.

**Comment by ErwinKomen** [comment]
Okay, works

**Comment by MennaRempt** [comment]
The selection mode is only available for editors, not for simple users. It should be available for all users. (the star to save items is available for all users)

**Comment by ErwinKomen** [comment]
### Implementation

1. dct/views.py
    1. `MyPassimEdit`: there seem to be no restrictions for non editors
    2. `SavedItemApply`: depending on `userpermissions`
    3. `SelectItemApply`: depending on `userpermissions`
