### ISSUE TITLE
DCT: tool page

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#387]
There should be a DCT tool page that is hosted in the "My Passim" Personal Research Environment (PRE). 

The DCT tool page can thus only be accessed when the user is logged in.

This page shows the research sets (= user-curated collections of source-lists) the user has made to be used as the basis for DCTs.

**Comment by ErwinKomen** [comment]
The PRE is a web page, an HTML page.
What does it mean to have  "DCT tool page" **hosted** in that PRE web page?
Is that page within page?
Or should there be a **link** from the PRE to a different HTML page, which is the "DCT tool page"?
(ANd then make that link only accessible from the PRE)

**Comment by MennaRempt** [comment]
> Or should there be a link from the PRE to a different HTML page, which is the "DCT tool page"?
(And then make that link only accessible from the PRE) 

Yes, this second option!
