### ISSUE TITLE
DCT launch: from DCT tool page

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#389]
Each research set should have a link to launch the DCT directly from the DCT tool page. 

compare e.g. the way manuscripts and templates can be created based on Historical Collections from the HC listview

**Comment by ErwinKomen** [comment]
Okay, from the DCT tool page the user now has a button to launch the 'default' DCT for a particular research set.
It's the **default**, since issue #390 tells us that one research set can have more than one named and defined DCT (definition).
