### ISSUE TITLE
DCT: multiple DCTs

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#390]
It should be possible for a user to have multiple active DCTs concurrently, i.e. for launched DCTs to stay accessible without having to launch it anew. 

Each DCT should be named, either by the user or automatically. Automatically assigned names should be based on a [username_DCT_number] format (e.g. "Menna_DCT_01"; "Menna_DCT_02" etc.)

**Comment by ErwinKomen** [comment]
The possibility to have multiple DCT's is now there.
A research set _does_ get a default DCT added to it automatically.

Each DCT can be named, but it now receives a default name in the format [username_DCT_number].

**Comment by ErwinKomen** [comment]
### Question
1. What should the **number** of a DCT be:
    1. A unique (order) number of all the DCTs belonging to one ResearchSet
    2. The database id (number) of this particular DCT

**Comment by ErwinKomen** [comment]
### Remaining TODO
Allow a user to **save** a DCT layout after manipulation
Possible manipulations:
1. Choosing a column order (one of the four 'standard' orders or the 'custom' order by dragging/dropping)
2. Custom choosing of pivot column (per #397)

**Comment by ErwinKomen** [comment]
Okay, this is now working
