### ISSUE TITLE
Research set: add source-lists

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#391]
Source-lists can be added to a research set in various ways:

1. From a listview by using the **basket** system: add a selection of sources to the basket > select 'add to DCT' (has to be added to the options). A drop-down menu with the user's research sets and launched DCTs is shown, and a research set to add the source-list(s) to can be selected
1. directly from a listview by using the **selection** functionality (see #386)
1. From the PRE: select a (combination of) saved source-list(s) > 'add to DCT'  > select research set
1. From the DCT tool page: there should be a button for each research set "add source-lists". Not completely clear what the best way to proceed from here is: clicking the button gives a drop-down menu that the user can filter by shelfmark/HC name/PD name, or clicking the button brings the user to the listviews from where they can add source-lists as described above.

See #392  for adding source-lists to a launched DCT.

**Comment by ErwinKomen** [comment]
#### Implementation
1. From a listview using basket system
1. From a listview using selection functionality
1. From the Personal Research Environment
1. From the DCT tool page
1. From the ResearchSet details page: **done** _(23/aug)_

**Comment by ErwinKomen** [comment]
#### Implementation (suggestion EK: phase 2) - _continued..._
1. From a listview using selection functionality - **TODO**
1. From the Personal Research Environment - **TODO**
