### ISSUE TITLE
DCT: add source-lists

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#392]
It should be possible to add additional source-lists to an active (launched) DCT in the same ways as source-lists can be added to research sets. (see #391)

When selecting "add to DCT" in any of these options, both active DCTs and Research Sets are shown.

**Comment by ErwinKomen** [comment]
From our discussion (Oct/20):

Adding a source-list in a DCT follows this process:
1. The user selects a source-list in the (to-be-made) box in the DCT and presses the button "Add source list"
    1. Three types of additions are possible:
        1. Existing (not-yet-used) item that is **already** part of the ResearchSet
        2. Additional manuscript (not yet in the ResearchSet)
        3. Additional collection (not yet in the ResearchSet)
2. The details are sent to the server
3. At the server:
    1. The source-list is added as the last `SetList` item part of the `ResearchSet`
    2. The DCT itself (defined in `SetDef`) is modified: its `contents` field is adapted to include the new source-list
    3. The adapted DCT information is returned in the response to the user's browser request
4. An adapted DCT is built and shown on the user's browser

**Comment by ErwinKomen** [comment]
Works
