### ISSUE TITLE
DCT: delete source-lists

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#394]
It should be possible to delete source-lists from an active (launched) DCT without the DCT having to be relaunched.

How exactly is unclear: possibly by using the column heading in some way?

**Comment by ErwinKomen** [comment]
From our discussion (Oct/20):
- Deletion of an item from a DCT is **only** from this current DCT, not from the `ResearchSet` on which this DCT is based
- THis means that there may be DCTs that do **not** show _all_ the source-lists that are part of their `ResearchSet`

**Comment by ErwinKomen** [comment]
This has now been implemented.

### How it works
The renewed DCT now also has a red-colored trash can symbol:
![passim_dct_trashcan](https://user-images.githubusercontent.com/11887269/140035318-a1c40256-c7fb-4c83-8836-1391f424290a.png)
Simply drag the green-colored column head and drop it into the trashcan.
Note: the list will still be part of the ResearchSet. But it won't show up anymore in this DCT.
