### ISSUE TITLE
DCT: Pivot Manuscript: automatic selection

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#396]
The Pivot Manuscript is the source-list chosen to function as the basis for the comparison.

The Pivot Manuscript should be automatically determined based on the number of unique matches source-lists have in relation to each other. A match is understood as a SSG appearing on multiple source-lists in the research set. Only unique matches are taken into consideration for the selection of the Pivot Manuscript: that is, matches that the potential Pivot Manuscript has to all other source-lists in the research set, where all SSGs are only counted once, regardless of whether they appear in multiple source-lists (apart from the potential Pivot Manuscript).

example: if manuscript M containing 15 texts (SSG links) has 3 matches with manuscript X and 10 matches with manuscript Y, and none of the texts (SSG links) from X and Y that match with M are the same, M has 13 unique matches. If, however, 2 of the texts (SSG links) from X and Y that match with M are the same, M has 11 unique matches. 

The source-list with the highest number of unique matches is selected as the Pivot Manuscript. If there are multiple source-lists with the same number of matches, the oldest (manuscript) source-list should be selected.

**Comment by ErwinKomen** [comment]
### Implementation

1. Need to know **when** to calculate the PM
    1. Whenever the order or something else of ResearchSet changes, the PM should be re-calculated
        1. Add to the `update_ssglists()` method of model `ResearchSet`
        2. What I do now: all `SetDef` objects for this research set get a `recalc = True` in their `contents` field
1. Calculation of the PM is triggered in view `SetDefData`, method `add_to_context()`:
    1. When `pivot_col` is not defined in contents
    2. When `recalc` is present in contents
1. Calculation of PM is done on the research set level and takes place in:
    1. ResearchSet, method `calculate_pm()`

**Comment by ErwinKomen** [comment]
Okay, I thought I had it all covered, but I missed one line:

> If there are multiple source-lists with the same number of matches, the oldest (manuscript) source-list should be selected.

This means: take into account `yearstart` and `yearfinish` in the title part!!

**Comment by ErwinKomen** [comment]
Okay, I've now taken this into account for possible ties: `yearstart` > `yearfinish` > `order`
