### ISSUE TITLE
DCT: PM manual selection

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#397]
**[phase 2 of the DCT]**

The user should be able to manually select a source-list to function as the Pivot Manuscript, e.g. by getting that option after right-clicking the column heading for that source-list.

**Comment by ErwinKomen** [comment]
Next stage (27/sep/21):
- Clicking the top identifier of the column (hc, pd, manuscript city) turns that column into the PC
- TODO: allow saving this change to this DCT-view
