### ISSUE TITLE
DCT: hiding items

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#398]
Items (rows) in the DCT can be hidden from view, but this should not delete the item from the source-list. Hidden items are still taken into consideration for calculations, but they are temporarily visually hidden to the user.

There should be "expand" buttons for each hidden row, and an "expand all" button to show all hidden rows.

**Comment by ErwinKomen** [comment]
### How it works
1. Hide a row by hovering over the **right** side of the Gryson/Clavis cell and then pressing the red 'minus' button that appears
2. If the hidden rows need to be saved, then press the save button
3. Expand **all** hidden rows back again by pressing the **expand** button that pops up, when a row has been hidden
4. When view mode "view all" is chosen, all hidden rows are unhidden, including the manually hidden ones. When the user then returns to "matches only", all previously manually hidden rows are visible again. 

Any view configuration is only 'kept', after it has been saved using the Save button

**Comment by MennaRempt** [comment]
This part of the issue is not yet implemented: "There should be "expand" buttons for each hidden row". 

Currently when rows are hidden, they are completely gone; would it be possible to have some indication that there is a hidden row, and to have the possibility to expand individual hidden rows (rather than all at once)?
