### ISSUE TITLE
DCT: layout

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#399]
The DCT is a table.

The **columns** contain the source-lists

1.  The column headings contain the source-list identification information
    1. _(phase 1)_ in the case of manuscript source-lists: location, library, shelfmark _(phase 1)_ - (**ok** EK)
    1. _(phase 2)_ in the case of HC source-lists: the name of the HC  - (**ok** EK)
    1. _(phase 2)_ in the case of SSG source-lists: 
        1. either the name of the PD - (**ok** EK)
        2. or a user-defined name (which means that the user should be prompted to name a SSG list when adding it to the research set/DCT for comparison). - (**ok**: **20/sep** EK)
1. The column headings should be clickable and link to the manuscript identifier / HC / PD (if available) details page.  - (**ok** EK)
1. The first column always contains the sermon identifiers based on the SSGs. 
    1. Only one identifier should be shown, by default in this order of priority: Gryson code – Clavis code – Other code – PASSIM code (i.e. if one type of code is not available, the next one in this list is shown).  - (**ok** EK)
    1. If a SSG has multiple of the same type of identifier, the first one alphabetically (and after that numerically) should be shown, followed by an ellipsis to indicate that there are more identifiers available.  - (**ok** EK)
    1. Hovering over the cell with the identifier will then show a pop-up with all the SSG codes.   - (**ok** EK)
    1. The cells with the sermon identifiers should be clickable, leading to the SSG details page.  - (**ok** EK)
1. The second column always contains the Pivot Manuscript. - (**ok** EK)
1. The first two columns should be pinned to the left of the table, so that the user can scroll horizontally through the rest of the table without losing sight them. - (**ok**: **20/sep** EK - corrected on **27/sep**)
1. The columns not containing the PM:
    1. _(phase 1)_ They are ordered horizontally by decreasing number of matches with the PM.  - (**ok** EK)
    1. _(phase 2)_ There should also be the option for a custom order:
        1. either alphabetically (e.g. city (a-z), library (a-z), shelfmark),  - (**ok** EK)
        2. chronologically,  (**EK**: only manuscripts have dates, not hist-coll or pers-dataset.)
        3. by increasing/decreasing number of matches to the PM  - (**ok** EK)
        4. or a manually selected custom order.  - (**EK**: the 'custom' order is the order within the research set)
        5. There should be buttons for the 'automatic' custom orders (_EK: that's there_), and the possibility to drag the columns around for a manual custom order.  - (**EK:** _Now working 27/sep/21_)

The **rows** contain the individual items in those source-lists.
1. By default, the table shows one row for each item in the Pivot Manuscript, regardless of it having a match or not. - (**ok**, but see below where the **default** is defined differently EK)
    1. The rows with items in the PM without a match should be faded in some way throughout the table. (**EK**: right now they are either not shown (view = `matches only`) or shown as they are (view = `view all`)
2. For the other columns (containing the source-lists), the items are ordered according to the Pivot Manuscript. 
    1. By **default**, the table should only show the matches to the Pivot Manuscript,  - (**ok** EK)
    1. but there should be an option to expand the table to show below that the rest of the contents of the non-PM source-lists: issue #401  - (**ok** EK)
    1. Order of the rows: they should follow the order that they appear in the source-list, minus the matches to the PM (since these are already shown earlier in the table). - (**ok** [EK]: they now show the order of appearance in the source lists.)
3. Only the numbers of the SSGs are shown in all columns apart from the first. The items will have the item number they have in the list of manuscript contents (in the case of a manuscript or codicological unit being used as a source-list) _(phase 1)_, the HC or the Personal Dataset _(phase 2)_.  - (**ok** EK)
    1. NB. since source-lists are lists of SSG links, sermon manifestations without a SSG link are of course not taken into account. This means that the numbering will skip those numbers that are assigned to sermon manifestations in manuscript source-lists that do not have a SSG link.  - (**ok** EK)

(fictional) example table:

  | St. 				Gall, 198 | Paris, 				Bnf, Lat. 2789 | Munich, 				StaBi, Clm 14572 | 
-- | -- | -- | -- |
AU 				s 125 | 1 | 1 | 2 |   |  
AU 				s 71 | 2 | 7 |   |   |  
CAE 				s Et5 | 3 |   | 4 |   |  
  | … | … | … |   |  
CPPM I 5431 |   |   | 5 |   |

**Comment by ErwinKomen** [comment]
**27/sep** : (hopefully) better solution for poin **5** above.
