### ISSUE TITLE
DCT: additional item information

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#402]
By default, the only information shown for items (SSG links) in the DCT is the order number of the item in the source-list. Additionally, information about the item should be available in the following ways:

1. _(phase 1)_ By hovering over a cell, the user should get a pop-up with basic information about the item (from the SSG page: author, PASSIM code, incipit, explicit, HC _(if the SSG is part of a historical collection)_, number of SGs contained in the equality set, number of links to other SSGs)
2. _(phase 2)_ for manuscript source-lists, there should be an option for the user to select additional sermon manifestation details fields to be shown (options: attributed author, section title, lectio, title, incipit, explicit, postscriptum, feast, bible reference, cod. notes, notes, keywords). How exactly this information should be presented is unclear and needs to be discussed.

**Comment by ErwinKomen** [comment]
#### Implementation notes
1. Phase 1
    1. Add the following information to be passed on from the view to html.
        1. Adapt `SetDef` function `get_contents()` ??

1. Phase 2

**Comment by ErwinKomen** [comment]
#### Implementation: first column
1. This is coded in JS, `private_methods.dct_row_combine()`
    1. Right now `title` is used for a regular popup
1. Necessary changes
    1. Add into the `<td` definition: `data-toggle='tooltip' data-tooltip='dct-hover' `
    2. Change the definition of `title` to include the SSG part
        1. Adapt existing `private_methods.dct_tooltip()` with additional argument **type** - `ssg` vs `srm`

#### Implementation: cells in other columns
1. ...
