### ISSUE TITLE
(Put on hold) DCT launch: from listview 

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#404]
It should be possible to launch the DCT directly from a listview, in two ways:

1. from a listview by using the basket system: add a selection of source-lists to the basket > select 'launch DCT' (has to be added to the options). The DCT is then launched using the selected source-lists
2. directly from a listview using the **selection** functionality (see #386) 

_(phase 2)_ NB1. when launching the DCT from a SSG listview, one needs to select additional source-lists for comparison, since the selected SSGs will only form one list. This should be possible after launching the DCT (see #392) 

_(phase 2)_ NB2. The HC and PD listviews currently do not have a basket functionality, so they can only be selected using the direct selection method outlined above.

**Comment by ErwinKomen** [comment]
### Implementation of phase 1
The task for this phase 1 is:
> from a listview by using the basket system: add a selection of source-lists to the basket > select 'launch DCT' (has to be added to the options). The DCT is then launched using the selected source-lists

**Comment by ErwinKomen** [comment]
### Implementation of phase 2
The task for phase 2 is:
> It should be possible to launch the DCT directly from a listview using the selection functionality (see #386)

This awaits implementation of issue #386...
