### ISSUE TITLE
PRE: Saved searches

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#408]
There should be an option to save specific searches in the PRE and give them a name. Currently searches are all assigned a unique URL, so it should be possible to use this to save the search in the PRE.

**Comment by ErwinKomen** [comment]
### Implementation

1. Added model `SavedSearch` to dct.models

**Comment by ErwinKomen** [comment]
### Approach
1. Decide when/how a user can perform a 'save search'
1. implement adding a `Saved search`
1. Add section `Saved searches` to MyPassim (similar to `Saved items`)
1. Implement removing a `Saved search` (from the list in MyPassim)
