### ISSUE TITLE
PRE: visualisations

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#409]
It should be possible to save any visualisations in the personal research environment (SSG visualisations, DCTs). The visualisations should be exportable directly from the PRE. It should also be possible to return to the page to manipulate the visualisation from here.

**Comment by ErwinKomen** [comment]
Question: what does it mean to 'save' a visualisation? What is a visualisation within PASSIM?

**Comment by ErwinKomen** [comment]
### Implementation

1. All Saved Visualizations
    1. Add model to dct: `SavedVis`. This holds fields: 
        1. `order`: the numerical order of the visualization for this user
        1. `name`: the name provided by the user
        1. `profile`: FK to the user that saved this visualization
        1. `url`: the URL to get to the main (details) view for this visualization
        1. `options`: JSON dictionary with key/value pairs to reconstruct the visualization
            1. Note that this must also contain `vistype`, which is the visualization type
            2. Currently `vistype` can have values: `overlap`, `transmission`, `dct`
    1. Add JS processing of saving a visualization
        1. Added passim.seeker.js function `do_savedvis()`. 
        2. This will issue a POST call to actually save the visualization for this user
        3. The call will be made to view `SavedVisualizationApply`, which expects the `options` to contain all necessary details
        4. This view will put the visualization into table `SavedVis`
1. Specifically for **overlap**
    1. Added code in `super_graph.html`, in order to make a calle to `SavedVisualizationApply` via JS `do_savedvis()`
1. Specifically for **transition**
    1. 
1. Specifically for **dct**
    1.

**Comment by ErwinKomen** [comment]
Added the DCTs (model `SetDef`) in the same way as the other items: via `rel_view.html`
Working!
