### ISSUE TITLE
Project: add labels to all items 

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#412]
1. Add project labels to sermon manifestations, SSGs, HCs (all items currently in the database should be added to project "PASSIM")
2. Make it possible for an item to be connected to multiple projects
2. Add a search filter: project (for all listviews of items that can be assigned to a project (=MS, S, SSG, HC)) (default = all); search for either OR or AND should be possible.

**Comment by ThijsRU** [comment]
For SSG/AF:

Ook daar moet ieder project aan kunnen geven of de approval er is of niet.
Dus bijvoorbeeld deze twee velden:

    # [1] Each CollectionProject combination should be manually approvable by that project
    approval = models.CharField("Type of approval", choices=build_abbr_list(APPROVAL_TYPE), max_length=5, default='cre')
    # [0-1] Approval history
    ahist = models.TextField("Approval history", default="[]")

Dan moet APPROVAL_TYPE worden gedefinieerd bovenin models.py (als seeker.approval), en vervolgens moet in de database handmatig in FieldChoice informatie worden toegevoegd over de verschillende opties van seeker.approval: created, approved, pending o.i.d.

Dezelfde velden zouden ook aan ManuscripProject toegevoegd moeten worden. Op die manier wordt in de database bijgehouden of een collection/manuscript voor een bepaald project ‘approved’ is of niet. Vervolgens kunnen we die informatie weer meenemen in het tonen en zoeken van de juiste manuscripten en collecties per project.

**Comment by ThijsRU** [comment]
store rev history 

stype_edi_fields project list

**Comment by ThijsRU** [comment]
=====
apart issue mbt users, profile en project

verplicht project name, default van de gebruiker, 

Profile FK naar default project, mag gebruiker niet zelf instellen, 

op het moment dat je een manuscript opslaat, check of er al een relatie, zo niet dan aanmaken met de default van de gebruiker. Dit moet als eerste werken voordat 

Tools, user profiles, default project tonen, Shari toegang profile edit list

plus igv nieuwe manu, direct project link in SermonDescrProject opslaan, de editors kunnen ook extra projecten aan een Sermon koppelen. 

opsplitsen issue in subissues

**Comment by ErwinKomen** [comment]
Points of attention that I noticed:
1. The SG details view:
    1. This correctly shows the SG's project[s] as being those of he SSG it belongs to
    2. But it looks like the projects can now be edited in the SG edit view -- that should not be possible, shouldn't it? At any rate, it is not working properly righ now. THe edit facility here should be taken away (see below).


#### Taking away editing from the Project field:
RIght now the code for `SermonGoldEdit` view, method `add_to_context()` is:
```python
                  # Project2 HIER zie keyword! Die worden 
                {'type': 'plain', 'label': "Project (SSG):",     'value': instance.get_project_ssg_markdown2(), 'field_list': 'projlist'},
```

What should be done is taking away `, 'field_list': 'projlist'`. When there is no field or field list, a field is view-only.

**Comment by ThijsRU** [comment]
1. The SG details view: Done

2. Safety precautions against deleting projects: 

In ProjectEdit, only moderators and superusers can create, edit and delete a project or is this not properly done? View:
https://github.com/ErwinKomen/RU-passim/blob/master/passim/passim/seeker/views.py#L6316

3. When a user adds a Project to a Manuscript, all the sermons are also added to this project, which is good. But...

    What if a user removes one particular sermon from this project
    ... and then later adds another project to the manuscript: What happens?
        Are all the manuscript's sermons only added to this last project?
        Or are all the manuscript's sermons added to all the projects of the manuscript?

They are all added to the new project.

**Comment by ErwinKomen** [comment]
We now have the following table with **actions** and the **effects** these have on S, M:

- | Add project X to Sermon | Add project Y to Manuscript | Add Sermon to Manuscript
--- | --- | --- | ---
Effect on Sermon | sermon gets project X added | _(see below)_ | sermon gets project of manuscript if ms has one project; editor has to manually add project if ms has multiple projects (sermon cannot be saved unless a project is added)
Effect on Manuscript | _nothing_ | manuscript gets project Y added | _nothing_
Effect on other sermons | _nothing_ | _nothing_ | _nothing_

**Comment by ErwinKomen** [comment]
### Actions and checks
1. When 'adding a project X to a Sermon'
    1. Effect on Sermon:
    1. Effect on Manuscript:
    1. Effect on other sermons:
2. When 'adding a project Y to a Manuscript'
    1. Effect on Sermon:
    1. Effect on Manuscript:
    1. Effect on other sermons:
3. When 'adding a Sermon to a Manuscript'
    1. Effect on Sermon:
    1. Effect on Manuscript:
    1. Effect on other sermons:

**Comment by ErwinKomen** [comment]
### Deletion effects

Right now the following effects for deletion are in place:
Effect on | Delete project X from Sermon | Delete project Y from Manuscript | Delete Sermon from Manuscript
--- | --- | --- | ---
**Sermon** | sermon loses project X (unless it would end up empty - see below) | _nothing_ | _nothing_
**Manuscript** | _nothing_ | project Y deleted from manuscript (can manuscripts be project-less?) | _nothing_
**other sermons** | _nothing_ | _nothing_ | _nothing_

**Comment by ErwinKomen** [comment]
Note: it is **not** possible to delete a project from a manuscript, if the number of projects belonging to a manuscript is **1**. See issue #485
