### ISSUE TITLE
Bug: sermon basket

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#413]
It is not possible to go to the second (or third, or fourth etc.) page of a sermon manifestation basket listview; instead, this leads the user to the second (or third, or fourth etc.) page of the entire list of sermon manifestations.

**Comment by ErwinKomen** [comment]
This was a bit tricky to find. 
In order to continue seeing the pages of any basket listview, the parameter `self.basketview` needs to be put onto `True` after each new listview request. Here is the code in BasicList.get_queryset():
```python
        if self.bHasParameters:
            # y = [x for x in get ]
            bHasListFilters = len([x for x in get if self.prefix in x and get[x] != ""]) > 0
            if not bHasListFilters:
                self.basketview = ("usebasket" in get and get['usebasket'] == "True")
```
