### ISSUE TITLE
Projects MSS count

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#415]
On the Tools > Projects page, the number of MSS linked to the project "PASSIM" shown on the badge in the list of projects is higher than the number of MSS in the database (1768 vs. 1753 MSS in the database).

**Comment by ErwinKomen** [comment]
This is shown in the `ProjectListView`.
Right now the calculation is: `count = instance.project_manuscripts.all().count()`
But this may also include manuscripts that are templates -- that's the problem.

Resolution:
```
count = instance.project_manuscripts.exclude(mtype="tem").count()
```
