### ISSUE TITLE
GoldSermon PD

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#416]
- Delete possibility for a GoldSermon dataset 
- Delete the option to search for a GoldSermon dataset (MS > collection/dataset > PD: sermon gold; if this is an option elsewhere, delete it there too)

**Comment by ErwinKomen** [comment]
This is on page: Personal Dataset

**Comment by ErwinKomen** [comment]
### Questions
1. Should **all** SG collections be banned? Right now we are leaving the possibility to have **public** ones
2. What about the Collection listview (Tools > My Datasets): right now it has the possibility to filter on _any kind_ of dataset, including a SG dataset. Should that stay or change?

**Comment by MennaRempt** [comment]
1. yes, the possibility for public SG datasets can also be deleted.
2. As long as there are still SG datasets in the database (I think there are a few), this option should remain; in the future these should be deleted though, and the option to filter on SG dataset should then be deleted too. (I think currently these datasets are used for data input)
