### ISSUE TITLE
Visualisation: update

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#417]
Add an update button to the SSG visualisations. Currently when changing the settings, the visualisation has to be closed and re-opened for the updated version to be shown, but this is not intuitive.

**Comment by ErwinKomen** [comment]
Okay, good point!

The SSG visualizations are moderated through template `super_graph.html`, so that is the place to add `Update` buttons.
(Note: this template is filled in view `EqualGoldDetails`, method `add_to_context()`)

**Comment by ErwinKomen** [comment]
Added update button(s)
