### ISSUE TITLE
MS template: delete page numbers

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#420]
For templates based on an existing manuscript, the page/folio numbers should not be copied into the template (and thus to a new manuscript based on that template).

**Comment by ErwinKomen** [comment]
A template is created from a manuscript using the `Create template...` button from the manuscript details view.
See `ManuscriptEdit`, method `add_to_context()`.

The button redirects to the template details view, having `manubase` (the id of the manuscript) as additional parameter.
THis opens up the view `TemplateDetails` (and also the underlying `TemplateEdit` view).
Before 'saving' the actual copying takes place using the `Manuscript` model's method `get_manutemplate_copy()`
(Note: the latter function is also called from `TemplateApply`, i.e. when a new manuscript is created, based on a manuscript template.)

Now, the page/folio numbers are formed by the field `locus`, which is part of the `SermonDescr` and the `SermonHead` models.

**Comment by ErwinKomen** [comment]
Okay, checked and this works.
