### ISSUE TITLE
SSG: "Authority file"

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#421]
"SSG/Super Sermon Gold" should be changed to "Authority file" throughout the database.

**Comment by MennaRempt** [comment]
It is still 'Super Sermon Gold' in two places:

- Manuscript > filter 'Collection/Dataset' > "PD: Super Sermon Gold"
- Sermon > filter "Collection" > "Super Sermon Gold"

**Comment by ThijsRU** [comment]
- Manuscript > filter 'Collection/Dataset' > "PD: Super Sermon Gold" DONE
- Sermon > filter "Collection" > "Super Sermon Gold" DONE

**Comment by MennaRempt** [comment]
One more place where it is still SSG:

Dataset > add a new dataset > 'Super Sermon Gold'

**Comment by ThijsRU** [comment]
Changed in dataset_add.html.

**Comment by ThijsRU** [comment]
Remember to check the templates not "added" in local VS project. 

SSG refs change?

**Comment by MennaRempt** [comment]
One more: it is still 'SSG' in the AF visualisations (when they are opened).

**Comment by ThijsRU** [comment]
OK, "SSG" references have been changed into "AF".

**Comment by ThijsRU** [comment]
The "super" type has been changed into "authority file"

**Comment by ThijsRU** [comment]
Found another reference to SSG, when making a comment on a AF:

![image](https://user-images.githubusercontent.com/46558447/199469170-1f1a257c-4893-408d-85c0-4e9a2266ce37.png)

**Comment by ThijsRU** [comment]
Another one

![image](https://user-images.githubusercontent.com/46558447/199472113-ecb29cbd-d01c-4c5f-861f-bc01addf05e2.png)

**Comment by ThijsRU** [comment]
AF, basket, create dataset

Description moet nog worden aangepast. super --> Authority file

eigenlijk moet de super in name ook aangepast worden,  thijs_946_super --> thijs_946_af WORKS

**Comment by ThijsRU** [comment]
Both instances of "super" have been modified, has this been done properly?
