### ISSUE TITLE
Sermon details: cod. unit

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#422]
The red codicological unit 'badge' in the right hand corner of the sermon details page (following the shelfmark) should say "cod. unit. [order nr.]" (so e.g. "cod. unit. 1") instead of the codicological unit title.

**Comment by ErwinKomen** [comment]
Okay, this is done in view `SermonEdit`, method `add_to_context()`, in determining the text for `title_right`.
Changed it.
