### ISSUE TITLE
Sermon: filter GRY/CLA

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#423]
1. Add the option to filter sermon manifestations on multiple signatures (as is possible for SSGs). This should yield as its result sermon manifestations that are linked to one of the signatures selected (OR, not AND).
1. Add an auto-complete filter for singular GRY/CLA signatures (as is already used for e.g. SSGs)

**Comment by ErwinKomen** [comment]
As for (1) above: this used to be there already. Restored it. THe `siglist` was taken instead of `siglist_a`

**Comment by ErwinKomen** [comment]
Works!
