### ISSUE TITLE
Bug: codicological unit date

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#426]
A date added to a codicological unit sometimes (often) disappears after saving the changes, even though it seems to be saved correctly. I have not been able to find out under what conditions it does or does not disappear.

**Comment by ErwinKomen** [comment]
I can't find any errors pertaining to this in the log files, nor am I able to reproduce the error.
I've added a bit of logging in `adapt_manu_dates()`, where some date processing occurs.

Otherwise: please let me know when exactly this occurs...

**Comment by ErwinKomen** [comment]
Okay, now I have some hard facts: the change of dates occurs when **saving** a codicological unit.

**Comment by MennaRempt** [comment]
Bug encountered again with [https://passim.rich.ru.nl/codico/details/841/](https://passim.rich.ru.nl/codico/details/841/): date added is visible in revision history, but has disappeared from cod. unit.

**Comment by ErwinKomen** [comment]
The action history of codico 841 shows two items milliseconds away from one another for codico 841:

Time | Details
--- | ---
2021-12-14 11:05:46.760875 | `{"id": 841, "savetype": "change", "changes": {"datelist": "[]"}}`
2021-12-14 11:05:46.783356 | `{"id": 841, "savetype": "add", "model": "Daterange", "changes": {"yearstart": 1100, "yearfinish": 1199, "newstart": "1100", "newfinish": "1199"}}`

**Comment by MennaRempt** [comment]
Happens again, e.g. with [https://passim.rich.ru.nl/codico/details/721/](https://passim.rich.ru.nl/codico/details/721/)

**Comment by ErwinKomen** [comment]
Problem: cannot find any action log for codico/details/721 (nor for the accompanying manuscript).

### Observations
1. In `Daterange`, method `adapt_manu_dates()` there was a kind of error: `manuscript_dateranges` was used, while that shouldn't.
    1. Corrected this one
    2. Looking for more mis-uses of `manuscript_dateranges`: see the work for LivingLaw :)

### Result
The direct link between Daterange and Manuscript has now been completely "cut", in favour of the link Manuscript > Codico > Daterange. The lingering of the former direct link must have been the cause for the flaws.
