### ISSUE TITLE
Provenance: cod. unit. link

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#428]
When a provenance is linked to a codicological unit, the manuscript is currently not visible on the provenance details page in the list of manuscripts linked to the provenance. Either the manuscript the cod. unit is part of should be visible on that list, or there should be a separate list of cod. units linked to the provenance on the provenance details page. (the second option is more desirable)

**Comment by ErwinKomen** [comment]
Ahum, an additional error on the fly, while checking this: the `/provcod/details/nnn/` page gives the wrong link to the provenance.
