### ISSUE TITLE
MS export: XML-TEI

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#429]
Add the possibility to download manuscript descriptions in XML-TEI.

**Comment by ErwinKomen** [comment]
Right now we have two download options: Excel and Json.
So when we add a third option, it is time to change the download button a little bit.
First doing that...

**Comment by ErwinKomen** [comment]
Note: we will continue the discussion on this topic in 2022

**Comment by MennaRempt** [comment]
Suggested amendments to the XML-TEI description of MSS, to include the Gryson/Clavis codes: 
 (NB. 'grégoire' should not be used as a label, but the labels already in use in the database for the signatures should be used, i.e. 'Gryson', 'Clavis' and 'Other code')
![image](https://user-images.githubusercontent.com/59916079/173769068-20795836-f1aa-49f8-a31b-9b1792510d64.png)

**Comment by MennaRempt** [comment]
Comments by Iris:
The solution for identification under ‘title’ (as posted in June) seems useful (<title type=’gryson’>AU s 202</title>), but some questions:
- The <author> mentioned here is the ascribed author, I assume? I’ve not found a suitable designation for ‘ascribed author’ yet in XML:TEI (and others have run into the same problem), so until we find one it might be best to leave out the ‘author’ altogether. As coded now, this would give the impression that Faustus is the real author of AU s 202 (which we should avoid, I think).
-- Perhaps we could use <author type=’attributed’> instead? I’m not quite sure.
-- There is also the option of ‘statement of responsibility’, found in par. 10.6.2, but that is perhaps not very useful
- We should use <rubric> to code what we’ve been calling a ‘title’ in each manuscript (e.g. just before the incipit, and after the ‘title’).
- If necessary, we can use <bibl> to refer to bibliography or editions for a specific <msItem>
- I see now that the current converted version in the database does not show any author (which is good), but also does not (yet) mention Gryson or other ID codes (which would be useful). I also think that ‘rubric’ would be useful and correspond to the standard.

![image](https://user-images.githubusercontent.com/59916079/204485217-319c215a-4e3e-4ba3-aee8-29ea0a1e3937.png)

**Comment by ErwinKomen** [comment]
### Implementation
The relevant code is in seeker/views.py, view `ManuscriptDownload` (so it's not just downloading one sermon, but a manuscript consisting of a number of sermons).
The XML templates is in `seeker/tei-template.xml`
