### ISSUE TITLE
SSG links: editable

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#430]
Elements of the links between SSGs should be editable: note, link type, direction and the checkbox for alternatives should be editable without having to delete and re-add a link. To link a different SSG, the previous link does have to be deleted and a new one added.

**Comment by ErwinKomen** [comment]
These are the links from SSG to SSG, which are visible in the section 'Links'.
The view for this section is provided by model `EqualGold`, method `get_superlinks_markdown()`
