### ISSUE TITLE
SSG links: alternatives

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#431]
The checkbox for 'alternatives' in a SSG link is not a stable size. On Firefox, the size of the checkbox changes depending on how large the window is (e.g. when the window is less than the full width of the screen, the checkbox shrinks). On Chrome, the checkbox is nearly invisible. It should be a stable size in all browsers.

**Comment by ErwinKomen** [comment]
This is in `EqualGoldEdit` view, where the user can add SSG links via a row, and this row.
So this is arranged in the form `EqualGoldLinkForm`
