### ISSUE TITLE
Spelling and typography details

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#433]
A few details of spelling and typography:

- on the ProfileEdits details page: "afilliation" > "affiliation"
- on the Manuscript Identifier details page: "shelf mark" > "shelfmark"
- on the SSG details page, if a SG does not have an author assigned, in the SG information in the 'contains' section: "unknwon author" > "unknown author" (e.g. [https://passim.rich.ru.nl/ssg/details/1235/](https://passim.rich.ru.nl/ssg/details/1235/))
- on the SSG details page, in the SG information in the 'contains' section: more space needed between the Gryson/Clavis codes and the author
- Tools > Synchronization…: "synchronisation" should consistently be spelled "synchronisation" (and "synchronise"); currently both spellings are used on the same page
- Some of the pages under tools are shown without a capital letter in the browser tab (‘templates’), others using a capital letter (‘Bible References’). The usage of capital letters should be the standard (also in the ‘history’ section (breadcrumb trail) at the top of the page, e.g. ‘Home > provenances’ should be ‘Home> Provenances’.
- on the SSG details page, the list of sermon manifestations at the bottom should be called "Manifestations" rather than "Manuscripts"
- on the HC listview page, the header "created" should become "added"

**Comment by ThijsRU** [comment]
on the ProfileEdits details page: "afilliation" > "affiliation" DONE

    on the Manuscript Identifier details page: "shelf mark" > "shelfmark" DONE

    on the SSG details page, if a SG does not have an author assigned, in the SG information in the 'contains' section: "unknwon author" > "unknown author" (e.g. https://passim.rich.ru.nl/ssg/details/1235/) DONE

    on the SSG details page, in the SG information in the 'contains' section: more space needed between the Gryson/Clavis codes and the author **TH: to be done**
 
    Tools > Synchronization…: "synchronisation" should consistently be spelled "synchronisation" (and "synchronise"); currently both spellings are used on the same page DONE

    Some of the pages under tools are shown without a capital letter in the browser tab (‘templates’), others using a capital letter (‘Bible References’). The usage of capital letters should be the standard DONE

(also in the ‘history’ section (breadcrumb trail) at the top of the page, e.g. ‘Home > provenances’ should be ‘Home> Provenances’. **TH: to be done**

    on the SSG details page, the list of sermon manifestations at the bottom should be called "Manifestations" rather than "Manuscripts" DONE

    on the HC listview page, the header "created" should become "added" DONE

**Comment by ThijsRU** [comment]
Done
