### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#434]
In the menu header, there should be six drop-down menus:

1. Browse: Manifestations, Manuscripts, Authority files, Historical Collections, Keywords, Feasts, Bible references
2. Tools: Bibliography, Visualisations, Datasets _(combines personal datasets and public datasets)_
3. Import tools: Author, Gold sermon, Repository _(=Library)_, Templates, Synchronisation, Origins, Provenances, Locations
4. MyPASSIM: just leads to the PRE
5. Help: About, How to quote, Technical, User manual, Import manual, Contact, Reports, Sources
6. User Profile: View, Log off

**Comment by MennaRempt** [comment]
"combines personal datasets and public datasets" just means that we would like for all datasets to be shown on the same page (in the same list), i.e. both public datasets and personal (private/team) datasets, rather than on two different pages as is now the case. If this needs to be a separate issue, please let me know.

**Comment by ThijsRU** [comment]
- What to do with the access to the views **User Keywords**, **User Comments**,  **Projects** and  **User profiles**? Keep them accessible? And if so: from which drop down menu? 

- The access to the views **Field changes** and **Field approvals** will be deleted.

- @MennaRempt, I think a separate issue should be made for **Datasets (combines personal datasets and public datasets)**

**Comment by ThijsRU** [comment]
For now this issue is done.
