### ISSUE TITLE
MS contents: signatures

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#436]
In the list of manuscript contents on the manuscript identifier details page, combine 'Gryson A' and 'Gryson M' into 'Signatures'. The option to manually add signatures on the sermon details page should remain, but these and the ones automatically shown from the SSG link(s) should be shown in one category on the manuscript details page.

**Comment by ErwinKomen** [comment]
There are two completely different questions in this one issue.
1. Manuscript details
    1. The Manuscript Details page contains a 'Contents' section with a list of sermons. That section has a green bar of top buttons
    2. THe top buttons "Gryson A" and "Gryson M" should be combined into one "Signatures"
    3. The signatures shown per sermon should be combined into one category **but only in the Contents section of the Manuscript Details page**
1. Sermon details
    1. This has (upon switching to edit mode) an option to add Gryson/Clavis manually
    2. This option should remain 'as is'

**Comment by ErwinKomen** [comment]
### Implementation

1. Combining buttons Gryson A and Gryson M into: `Signatures`
