### ISSUE TITLE
S: free search addition

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#439]
There should be an option "select all" when selecting a category in 'may occur in any of' under the 'Free' search filter

**Comment by ErwinKomen** [comment]
### Implementation 

1. Add to `Free` an item with field name `all_fields` - which has a special meaning
2. Adapt `SermonListView`, method `adapt_search()` to handle `all_fields`

**Comment by ErwinKomen** [comment]
### Notes
1. When using the option `All 'free' fields`:
    1. It should be the **only** option (if not, it won't have any effect)
    2. Combining the `All 'free' fields` with search wild cards like `*` or `#` takes **agesss...** (not sure if it actually finishes and finds something)
1. Free fields in general:
    1. We've added the option to search for fields just 'containing' a string. Use the `@` for this. E.g. searching for 'gratia' (including 'gratiam' etc) would be: `gratia@`.
