### ISSUE TITLE
Keyword: SSG badge

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#440]
In the keywords list, when hovering over the SSG badge, the text shown is "frequency in manuscripts"; this should be "frequency in Authority files"

**Comment by ThijsRU** [comment]
html.append("<span class='badge jumbo-3 clickable' title='Frequency in manuscripts'>{}</span></a>".format(number)) -->

html.append("<span class='badge jumbo-4 clickable' title='Frequency in Authority files'>{}</span></a>".format(number))

**Comment by ThijsRU** [comment]
Done
