### ISSUE TITLE
SSG listview: columns

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#443]
Changes to the columns in the SSG listview:

- The column 'HC' should be deleted. 
- 'Sermons' should be changed to 'Manifestations'
- 'Gold' should be changed to 'Contains'
- 'Super' should be changed to 'Links'
- 'HCs' should be changed to 'Hist. Coll.'

**Comment by ThijsRU** [comment]
_Super_ was already changed into _Authority_, now into _Links_
