### ISSUE TITLE
Search filters: colours

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#447]
Tablet/mobile specific: 

- the colour of the filter symbol changes from red to yellow when the search filters are opened and closed; it should not change colour
- if a filter is deselected, it becomes yellow; it should turn back to grey

**Comment by ErwinKomen** [comment]
I added code in site.css that targets devices with and without hover possibilities.
That seems to be working fine for **Chrome** on my Android phone.
It doesn't work for Firefox on that same phone.
No idea what it does on tablets.


### NOTE
We don't develop for tablet or phone
