### ISSUE TITLE
Revision history button

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#448]
The button to show the revision history moves around depending on if the window is full screen or made smaller: when the window is made smaller, it moves to the bottom of the page. It should remain in the same place.

**Comment by ThijsRU** [comment]
This issue is finished.

**Comment by ThijsRU** [comment]
The indentation needs to be sorted in the basic_details.html

**Comment by ThijsRU** [comment]
I have staged the changes, hopefully ok now.
