### ISSUE TITLE
PD: visible in revision history

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#451]
The revision history shows when items are added to private personal datasets; this should not be visible (since private datasets should be private).

**Comment by shariboodts** [comment]
The revision history also shows when editor notes were added from the Sermones file. These notes should only be visible to editors, not normal users, so the content of the editor notes that were added should not be visible in the revision history. 

Example: passim.rich.ru.nl/manuscript/details/7776/

**Comment by ErwinKomen** [comment]
### Action plan
1. Restrict revision history for non-editors:
    1. do not show field `editornotes`
1. Restrictions for private personal datasets (collection of scope `priv` and settype `pd`)
    1. Non-owner must see it 'read-only'
    2. Non-owner may not see revision history
