### ISSUE TITLE
Loading select2 menus

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#452]
Any select2 menu (links, bibliography, edition, author etc.): after having a page open for a certain amount of time, the drop-down menus stop loading. The page has to be saved and re-opened for them to work again. 

This is the case both when going to edit the page after having had it open for a period of time in the 'non-edit' view, and when having the page open in the 'edit' view.

**Comment by ErwinKomen** [comment]
See Stalla issue 38, where I remarked:
> This has to do with the caching timeout. I was finally able to solve this. See [django doc](https://docs.djangoproject.com/en/4.0/topics/cache/), from where I copied the default LocMemCache into the settings.py, and then I added 'TIMEOUT': None, That solved it!!

I've now added the same TIMEOUT setting to the Redis Cache setting (slightly different piece of cake).
Done a test, and....
