### ISSUE TITLE
User comment button placement

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#456]
On all pages where a user comment can be submitted, the button should be next to the one to show the revision history.

**Comment by ThijsRU** [comment]
This needs to be done for these views:

- Manifestations
- Manuscripts
- Authority file

Changes made using the revision history button as a template:

- BasicDetails, ManuscriptEdit, EqualGoldEdit and SermonEdit, comment_button = True

User comment is not restricted to certain users.

- button is visible

To be done:

- change the location of the button, right from the revision history button, not above
- delete the old button

**Comment by ThijsRU** [comment]
div inline?

https://www.w3schools.com/css/tryit.asp?filename=trycss_inline-block_nav

**Comment by ThijsRU** [comment]
This issue is done
