### ISSUE TITLE
My PASSIM/PRE: consistency

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#462]
in the menu the PRE is called "My Passim", but on the page itself the "Personal Research Environment": make this uniform, or make the PRE just a section of the page that opens.

**Comment by ErwinKomen** [comment]
> **make this uniform**

Please tell as what to change in which way:
1. Change PRE everywhere to "My Passim", or...
2. Change "My Passim" everywhre to "PRE"
    1. When does the abbreviation need to be used?
    2. When does the full term need to be used?

**Comment by MennaRempt** [comment]
Change Personal Research Environment/PRE everywhere to 'My PASSIM'.

**Comment by ThijsRU** [comment]
Changes made in topnav.html and mypassim.html.
