### ISSUE TITLE
Listview: column headers

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#463]
The column headers in any listview should remain visible when scrolling down the list of results.

**Comment by ErwinKomen** [comment]
### Implementation
1. Added to basic.css: `fixed-header-container`, `fixed-header`
2. Used these classes in `basic_list.html`
3. Added JS `fixed_header()` function to basic.js
4. Made sure the function is also used on resize() - see basic.js

Result; works
