### ISSUE TITLE
SSG textual overlap network visualisation: degrees shown

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#467]
Overlap network degree 1 geeft op dit moment eigenlijk al meer edges en nodes weer dan genoemd staan in het ‘SSG links’ overzicht. Het zou mogelijk moeten zijn om alleen de directe links rond de SSG in kwestie te laten zien (d.w.z. alleen de nodes die nu rood en paars gekleurd zijn, en de bijbehorende edges). Het netwerk ‘degree 1’ zou dan simpelweg ‘degree 2’ moeten heten.

> Er bestaat op dit moment al een optie om 'degree' (het aantal links verwijderd van de SSG waarvandaan het netwerk begon) aan te passen. Het probleem dat we tegenkwamen is dat het instellen van degree = 1 eigenlijk al een te groot netwerk weergeeft, namelijk de links twee stappen verwijderd van de begin-SSG. 
Wat we eigenlijk zouden willen, is dat de instelling degree = 1 echt alleen de direct gelinkte SSG's weergeeft, terwijl degree = 2 ook de links van de direct gelinkte SSG's laat zien, etc. De functie kan dus hetzelfde blijven, maar wat de gebruiker ziet bij het instellen van degree schuift dus een stapje op. Degree = 1 zou daarmee de ​default worden, maar de gebruiker kan (net als nu) de grootte van het netwerk optioneel veranderen.

**Comment by ErwinKomen** [comment]
Okay, changed this.
