### ISSUE TITLE
DCT: scope

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#468]
Allow a user to change the scope of their research set (and attached DCT(s)) to be either 'private' or 'team' (cf. Personal Dataset).

**Comment by ErwinKomen** [comment]
### Testing
1. Tested out: it is now possible to use:
    1. `private`: research set is only visible and editable by the user himself
    2. `team`: research set is visible, editable etc by all Passim users in the group `passim_editor`
    3. `public`: this doesn't work completely yet: any member of `passim_user` is not only able to see a research set, but that person can also:
        1. Remove items from the research set
        2. Re-order items from the research set
        3. Open a DCT, make changes in the order/view/columns, and save those changes
1. Resolution of the tested and undesired issues:
    1. `ResearchSet` item removing:
    2. `ResearchSet` item re-ordering:
    3. DCT changes saving:
