### ISSUE TITLE
Project: connect editor status to project(s)

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#473]
Connect the editor status to projects: it should be possible for editors to only have editor status for (a) specific project(s), so that they cannot edit items that aren't connected to their project(s). 

1. PI needs to be able to assign project(s) to an editor. Maybe more persons. - (**EK**: _done_)

1. Editors that are connected to multiple projects have to manually select a project to assign the item to. - (**EK**: _done for_ `SermonDescr`, `EqualGold`, `Collection` (hc) and `Manuscript`)

1. In Tools, User profiles, show default project (or multiple projects) for each editor. - (**EK**: _done_)

1. All new items they create should automatically be assigned the project that they have editor status for. 
    1. Project name is mandatory, default the project of the editor if the editor has only one. 

1. Make it impossible for items to be saved without a project assigned. - (**EK**: _done for_ `Sermon`)

---

Please note: This issue needs to be implemented before issue #412.

point 4 kijken naar `def custom_add(oManu, **kwargs)` ?

**Comment by ErwinKomen** [comment]
> Please note: after this issue is taken care of, make sure the in the adaptations.py file need to be outcommented:
> 
> adapt_passim_project_name_manu
> adapt_passim_project_name_equal
> adapt_passim_project_name_hc
>
> (Keep adapt_passim_project_name_sermo)

Commenting or outcommenting of these procedures is not necessary.
Make sure to arrange for their execution by putting the right values in the table `Information`

**Comment by ErwinKomen** [comment]
### Implementation notes: editor-project
How do we know which projects an editor has any 'rights' to?
That is probably linked to point number 5 above: the PI (i.e. the moderator) should be able to assign projects to an editor.
1. Create a table linking `Profile` (person, potentially editor) with a `Project`
    1. And let the `Profile` (i.e. the person) have a ManyToMany field with the projects of this person

**Comment by ErwinKomen** [comment]
I think that all of the above is now working.
However: we need to do some careful testing to check whether that holds!!!

**Comment by ErwinKomen** [comment]
All seems to work just fine...

**Comment by ErwinKomen** [comment]
### Note: project assignment checking
The project assignment checking (M, S, SSG, HC) occurs in the view's `before_save()` method. It basically involves an organized call to the general function `evaluate_projlist()` (defined high up in view.py). 
This checks:
1. How many projects the current item (M, S, SSG, HC) is connected to over which the current user does **not** have editing rights (e.g. that could be 1, 'passim', if the user only has rights for e.g. 'ErwinTest01' project)
1. If there is at least **1** project connected to the current item
    1. Then the user may add to and remove from 'at liberty' (since the non-editable project will always remain assigned to this item)
1. If there are **0** projects assigned to this current item, over which the current user does **not** have editing rights, then
    1. if this user has editing rights over only 1 project >> default assignment to that project is done in `after_save()`
    2. if the user has editing rights over multiple projects >> the user must **manually** assign to at least one project.
