### ISSUE TITLE
Project: implement approval by editors after creation/modification of SSGs/AFs from all linked projects

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#474]
When SSGs/AFs connected to multiple projects are edited, editors of all projects connected to that item should get a notification to check and approve this edit. Once it has been approved by someone from each connected project, the status be changed to "approved". Possibly these items to be checked should be visible on a separate page (as e.g. the user keywords are) in the "import tools" menu (in the new menu layout, cf. issue #434).

**Comment by ErwinKomen** [comment]
#### Strategy
1. Question: Should the changes that are made by an editor be already 'committed' (i.e. appear for all users) when one editor makes this change?
1. Possible solutions
    1. If they _are_ committed immediately, then the history needs to be kept, and changes need to be revertable
    2. If they are _not_ committed immediately, then the 'proposed' changes need to be recorded somewhere on the SSG:
        1. so that other editors can see them and approve them
        2. possibly even make a comment per suggested change (comment chains even??)
1. Resolution
    1. The proposed changes need to be separate anyway (see above _Possibly these items to be checked should be visible on a separate page_). This means that solution (2) is the better one.
1. Implications
    1. Create a model that holds proposed changes: `Proposal` with fields:
        1. `equal` - FK to SSG
        2. `field` - name of the field (options: author, incipit, explicit, keywords, historical collections, contains, links, editions, literature)
        3. `current` - the current value (which is either a type-dependant stringified JSON)
        4. `change` - the proposed value (also a type-dependant stringified JSON)

---

#### JSON representations of all changeable fields

field | JSON representation
--- | ---
author | `{'id': FK to Author }`
incipit | `{'text': text of new incipit}`
explicit |  `{'text': text of new explicit}`
keywords | `{}`
historical collections | `{}`
contains | `{}`
links | `{}`
editions | `{}`
literature | `{}`

**Comment by ErwinKomen** [comment]
### Done
1. Created app `approve`
2. Created model `EqualChange`
    1. Added methods `json_to_html()`, `change_html()` and `current_html()`

### Future actions
1. ...

**Comment by ErwinKomen** [comment]
Issues above are done
