### ISSUE TITLE
Project: modify import to take care of Project labels

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#479]
The import methods need to be modified in order to link Project labels to the newly added items. Please view #412.

**Comment by ErwinKomen** [comment]
#### Situations

1. Only someone who is editor for at least one project can import Manuscripts
2. If the importer is editor for exactly 1 project
    1. that project gets assigned to the imported manuscript
3. If the importer is editor for more than 1 project
    1. let the importer **select** the projects that should be assigned to the imported manuscript(s)
