### ISSUE TITLE
Project: delete old Project model and methods

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#480]
The old Project model and everything that refers to the old model should be deleted.

First out comment, mark with PROJECT_MOD_HERE, then delete.  

Django check migrate etc.

Do not change Project2 references to Project, maybe later.

**Comment by ThijsRU** [comment]
Check all marked sections and see if there need to be changes --> Project2

**Comment by ErwinKomen** [comment]
Okay, done.
