### ISSUE TITLE
Approval: new SSG - adapt SSG listview

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#492]
Part of issue #474 

Approval of newly proposed SSGs: Adapt SSG listview to filter for 'approved only' SSGs

**Comment by ThijsRU** [comment]
- In field **atype** all values are _def_, should be _approved / app_, this needs to be corrected using Adaptations.py

- Change listview SSG/AF using **atype** field

- Use same techniques for issue 493

**Comment by ThijsRU** [comment]
Modify searches, add:

 {'section': 'other', 'filterlist': [
            {'filter': 'atype', 'dbfield': 'atype', 'keyS': 'atype'}

Modify adapt_search: 

lstExclude = [ Q(atype='def') 

When navigating to the list view of the Authority Files, ALL are listed, only when _sorting_, the SSG/AF's with 'def' for atype are kept out of the list. Now add the other types for atype, 'rej' and 'mod'.

**Comment by ThijsRU** [comment]
bUseFilter = True (is crucial for filtering out before the active use of filters in the listview)

{'section': 'other', 'filterlist': [
{'filter': 'atype', 'dbfield': 'atype', 'keyS': 'atype'}]

lstExclude = [ Q(atype__in=['mod', 'def', 'rej']) ]
