### ISSUE TITLE
Approval: new SSG - adapt other listviews

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#493]
Part of issue #474

Approval of newly proposed SSGs: Adapt other listview searches to only filter for 'approved' SSGs

**Comment by ErwinKomen** [comment]
> I do not yet grasp the reason for filtering out the output in these views by leaving out the Sermons, HC's and SG's that are linked to SSGs/AFs that have rejected, or new modifications

What needs to be done here is different than so far. What we want here is that when the user filters for partigular SSGs (within these views), the list of SSGs only shows those, that have been accepted (atype='acc'). The place where this 'happens' is in the **form** for these different listviews. Find out which form that is by looking at the listview. Then look further in the listview to see which 'list' is used to filter on SSGs. Next, go to `forms.py` and find out how the `queryset`(s) for these lists of SSGs are populated (probably something like `EqualGold.objects.all()`). That 'all' needs to be changed to filter on 'only accepted'.

**Comment by ThijsRU** [comment]
First focus on Historical Collection --> CollectionListView 

- ssgpassimlist needs to be adapted

CollectionListView --> CollectionForm

# SSG section:

Here the queryset should be modified:

- ssgpassimlist 

Before:
self.fields['ssgpassimlist'].queryset = EqualGold.objects.filter(code__isnull=False, moved__isnull=True).order_by('code') -->

After:
self.fields['ssgpassimlist'].queryset = EqualGold.objects.filter(code__isnull=False, moved__isnull=True, atype='acc').order_by('code')

**Comment by ThijsRU** [comment]
SermonForm:
self.fields['passimlist'].queryset = EqualGold.objects.filter(code__isnull=False, moved__isnull=True, atype='acc').order_by('code')

**Comment by ThijsRU** [comment]
Test if it is not possible anymore to filter on SSG/AFs that have an atype that is not 'acc' (mod/rej/def).

**Comment by ThijsRU** [comment]
This seems to be done, but issue #507 needs to be resolved before we know for sure.
