### ISSUE TITLE
Approval: new SSG - propogate proposal

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#494]
Part of issue #474

Approval of newly proposed SSGs: Propogate (list of) newly proposed SSGs to 'MyPassim'

**Comment by ThijsRU** [comment]
Modify mypassim.html:

**Comment by ErwinKomen** [comment]
The section for this issue in MyPassim.html might look something like this:

![afbeelding](https://user-images.githubusercontent.com/11887269/152343653-dc6ae5e3-c56a-477d-ba84-dcc14bc665f9.png)

**Comment by ThijsRU** [comment]
When adding a new AF only the default project of the editors should be added (this is done automatically). Then the fields must be added and the AF needs to be saved. Only after saving the AF the editor can add one or more projects to the newly created AF. If this is done immediately, the other editors will have to approve the fields of the newly added AF separately.

**Comment by ThijsRU** [comment]
- Approving a newly added SSG works, test for other users
- In MyPassim the counts look okay but not in the listview of the SSG/AF approvals
- The same goes for the list, the users sees ALL the newly added SSG/AFs but he/she should only see the ones she/he needs to approve
