### ISSUE TITLE
Approval: new SSG - perform proposal acceptance

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#496]
Part of issue #474

Approval of newly proposed SSGs: Perform SSG 'addition' to the system upon proposal acceptance of all editors

**Comment by ThijsRU** [comment]
is soort van issue 490

**Comment by ErwinKomen** [comment]
The action flows as follows:
1. A user provides an approval in the `EqualAddApprovalEdit` view and presses 'save'
2. The method `after_save()` in that view is called
3. If at least one project approver from each relevant project has provided an approval, then...
    1. All remaining needed approvers (objects of EqualAddApproval) are reviewed and their `atype` is set to `aut`
    1. A call is made to `equaladd_to_accept()`, which processes either the actual addition of the EqualGold object (by setting its atype to `acc`) or the deletion of it (by deleting the object).
