### ISSUE TITLE
Search: square brackets

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#499]
If possible, disregard square brackets in free text fields (incipit, explicit (AF and sermon), title, section title (sermon)) in searches.

**Comment by ThijsRU** [comment]
The open square bracket "[" seems to be disregarded already.

**Comment by ErwinKomen** [comment]
Okay, so this means that the user may provide the search string `*ante dies deu*`, and the results should then include e.g. `[ante dies] deuotionem...`

**Comment by ErwinKomen** [comment]
Okay, works
