### ISSUE TITLE
HC: AF ordering

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#500]
It currently is not possible to reorder AFs within a HC and have that order saved (reordering is possible, but it does not seem to be permanent, but instead revert back to a random(?) order. The item numbers are also strange, in that it is possible for the same item number to occur multiple times). It's especially important for the use of HC in the DCT that the order of the HC can be manually determined.

When a manuscript template is created based on a HC, the order of the AFs in the HC should be copied for the template.

**Comment by ErwinKomen** [comment]
### Implementation
1. Process changes in order within a HC
    1. This was a matter of adding `self.check_hlist(instance)` in `custom_init()` of the `CollHistDetails` view
