### ISSUE TITLE
HC: add dates

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#501]
Add the possibility to add a date (year(s)) to HCs.

**Comment by ThijsRU** [comment]
View Codico, Manuscript, modify Collection in models, modify views CollAnyEdit

Wijzigen in Codico

def add_one_daterange(self, sDateItem):  in Collection? def custom_set in models.py?

voorbeeld: http://localhost:6405/codico/details/550/

**Comment by ThijsRU** [comment]
Om mij onduidelijke redenen kan ik het nieuwe Daterange model niet importeren:

class DaterangeHistCol(models.Model)

Forms.py aangepast

**Comment by ThijsRU** [comment]
instance werkt al niet

**Comment by ThijsRU** [comment]
Lijkt ok, alleen nog de melding "invalid literal for int() with base 10: '' at line 98" controleren.

**Comment by ThijsRU** [comment]
Done
