### ISSUE TITLE
AF creation bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#506]
The same as in issue #503, but for AFs.

**Comment by ErwinKomen** [comment]
This was much more complex. Reason: SSG field approval system has influenced `author` on a number of places in the EqualGold edit and detail views. This plays up in particular where a new SSG is created. I should have checked on this earlier, but I had overlooked it...

Anyway, it's now sorted out: I've tested that it is now possible again to create a new SSG.

### Note:
Right now an AF is created apparently 'bare' (no status, no author). 
As soon as a newly made AF is saved again (i.e. after editing any of the fields, or after just switching to edit mode, changing nothing, and pressing 'save'), the status is changed automatically, the author is set to Undecided, and the default project is assigned.
If a user is the editor of multiple projects, right now the user needs to at least assign an AF manually to one particular project. That will change a.s.a.p: assignment automatically to the "default projects" specified in MyPassim
