### ISSUE TITLE
AF overlap network changes: edges

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#510]
Op dit moment worden de edges in de 'kern' van het netwerk (directe links met de authority file vanaf waar een onderzoeker begint) dikker/donkerder weergegeven dan de rest van het netwerk (zie het voorbeeld hieronder). In verband met leesbaarheid is het volgens ons beter om in de ‘standaard’ modus alle edges toch 'dun'/met dezelfde dikte weer te geven. (NB: Dit geldt niet voor de optie om edges te 'vervagen' naar de achtergrond door te klikken op de opties onder 'link types')

![image](https://user-images.githubusercontent.com/59916079/152767869-dea65641-f359-4f7e-b544-0418afe3690a.png)

NB: this issue has high priority!

**Comment by ErwinKomen** [comment]
### Implementation
1. See `passim.seeker.js`, function `draw_network_overlap`
2. This function has two parts where the 'stroke-width' of edges (i.e. links) are determined:
    1. The initial `.attr()` function in the main body of the definition of `link` - set the width to `fixed_width`
    2. The 'link.style()' definition function that is part of the function `zoomed(event)` within draw_network_overlap - set the width likewise to `fixed_width`

**Comment by ErwinKomen** [comment]
Additional request pertaining to this issue:
> - De links in de standaardmodus moeten gelijk zijn (dezelfde zwartheid).
> - Uitzonderingen daarbij zijn inderdaad (1) het ‘uit’ klikken van bepaalde linktypes in de ‘Link type’ modus, en (2) het verschil in zwartheid dat (ook nu al) te zien is in de ‘Direction modus’ om uses en uses (indirect) uit elkaar te kunnen houden. Deze twee optionele veranderingen in zwartheid moeten dus blijven zoals ze zijn.
