### ISSUE TITLE
AF overlap network changes: arrows

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#511]
1. Bij het klikken op 'direction' verschijnen er pijlen die de aangegeven richting van de link types weergeven. Deze pijlen zijn alleen niet altijd zichtbaar: ze worden bijvoorbeeld niet weergegeven bij het eerste ‘level’ van het netwerk (zie de eerste afbeelding hieronder) en maar gedeeltelijk bij het tweede ‘level’ (zie de tweede afbeelding hieronder).

![image](https://user-images.githubusercontent.com/59916079/152768253-63829f74-ab4f-48ca-828b-f4b67b183679.png)
Level 1 netwerk geeft geen pijlen weer	
![image](https://user-images.githubusercontent.com/59916079/152768276-2d1e9a9f-c2de-4446-8ec8-6e123c8ea3ec.png)
Level 2 geeft niet alle pijlen weer (bijvoorbeeld de vele uses links rondom AN Jud, geel in dit netwerk). Deze verschijnen pas bij Level 3. Sommige pijlen die bij level 3 horen, lijken echter wel al te verschijnen.

2. Daarnaast lijkt het alsof de vorm van de pijltjes soms verschilt (sommige edges lijken een grotere pijlpunt te hebben dan anderen). Heeft dit een betekenis? Zo niet, dan lijkt het me beter om uniforme pijlen te hebben.

NB. part 1 of this issue has high priority

**Comment by ErwinKomen** [comment]
### Implementation

See related issues #375 and #377.
The direction is shown, depending on the `spectype`:

Abbreviation | Spectype | Direction shown
--- | --- | ---
usd | Uses | _no_ (see issue #375)
udd | Used by | **yes**
usi | Uses (indirect) | _no_ (see issue #375)
udi | Used by (indirect) | **yes**
com | Common source | _no_
uns | Unspecified | _no_

**Comment by ErwinKomen** [comment]
### Part 2
> Daarnaast lijkt het alsof de vorm van de pijltjes soms verschilt (sommige edges lijken een grotere pijlpunt te hebben dan anderen). Heeft dit een betekenis? Zo niet, dan lijkt het me beter om uniforme pijlen te hebben.

Please provide a concrete example. I cannot replicate this.
