### ISSUE TITLE
HC search filters fixes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#513]
Some issues with the Historical Collection search filters:

- 'Super filters' should be changed to 'Authority file filters' _DONE but not so nice, "Authority_File".
- 'Sermo filters' should be changed to 'Sermon filters' _DONE_
- 'Manu filters' should be changed to 'Manuscript filters' _DONE_
- AF > 'Gryson/Clavis' should be changed to 'Gryson/Clavis/Other code' _DONE_ 
- Manuscript > the 'country' and 'city' filters don't have a search field; either they should have one, or the filters should be deleted. _DONE_
- Manuscript > City: change to 'City/location' _DONE_

- Searching by AF > PASSIM code gives an error (only when entering a PASSIM code manually; selecting PASSIM codes from the drop-down list does work) (see #507) _DONE_ (nothing seems wrong on the live site, works there and locally)

- Sermon > 'feast' filter does not work (no feasts can be selected)

**Comment by MennaRempt** [comment]
Question: what is the AF > 'number' filter?

**Comment by ThijsRU** [comment]
basic/views.py. BasicList, 
daar aanpassen
# Add filter section name
            section_name = section['section']

**Comment by ThijsRU** [comment]
@MennaRempt Wat bedoel je precies met "Question: what is the AF > 'number' filter?"

**Comment by ThijsRU** [comment]
This issues is done...for now.

**Comment by ThijsRU** [comment]
Searching by AF > PASSIM code gives an error (only when entering a PASSIM code manually; selecting PASSIM codes from the drop-down list does work) (see #507) 

- Manuscript > the 'country' and 'city' filters don't have a search field; either they should have one, or the filters should be deleted. 

- Sermon > 'feast' filter does not work (no feasts can be selected)

**Comment by MennaRempt** [comment]
> @MennaRempt Wat bedoel je precies met "Question: what is the AF > 'number' filter?"

Ik bedoel hiermee: hoe moet dit filter gebruikt worden/waar wordt op gezocht met dit filter?
