### ISSUE TITLE
Sermon search filters fixes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#514]
- Manuscript… > City: change into 'City/location' to match the MS search screen
- Manuscript… > 'date from' & 'date until': change to date range (cf. issue #300) 
- Bible: change to 'Bible reference' to match the MS search screen

**Comment by MennaRempt** [comment]
Additional things:

- add a column "manuscript date"; it should be possible to sort the listview on this column
-  Change 'Signature' to 'Gryson/Clavis' (using the same terms as on the manifestation details page)
- Change 'Author' to 'Attributed author' in: manifestation listview (column header), 'author' search filter, and on the Authority file details page in the list of manifestations.

**Comment by ErwinKomen** [comment]
### Implementation

1. Manuscript… > City: change into 'City/location' to match the MS search screen
1. Manuscript… > 'date from' & 'date until': change to date range (cf. issue #300)
1. Bible: change to 'Bible reference' to match the MS search screen
1. add a column "manuscript date"; it should be possible to sort the listview on this column
1. Change 'Signature' to 'Gryson/Clavis' (using the same terms as on the manifestation details page)
1. Change 'Author' to 'Attributed author' in: manifestation listview (column header), 'author' search filter, and on the Authority file details page in the list of manifestations.

**Comment by MennaRempt** [comment]
Some more changes: 
- 'Collection': change into 'Collection/Dataset...'
- Add group 'Authority file' with the following search filters (in this order): 'PASSIM code' (this filter can be removed from the main section of search filters); 'Gryson/Clavis/Other' (this filter can be removed from the main section of search filters; the results should include both automatic and manual Gryson/Clavis/Other codes.); 'Author' (=the AF author); 'Incipit' (=the AF incipit); 'Explicit' (=the AF explicit)
- Move 'status' to the left of 'project'.
