### ISSUE TITLE
MS search filter fixes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#515]
- 'Manuscript': change to 'Manuscript type' to match the sermons search screen
- Add search filter: title (free text field with wildcards and auto-completion) (name from `Codico`)

**Comment by ThijsRU** [comment]
'Manuscript': change to 'Manuscript type' to match the sermons search screen DONE

**Comment by MennaRempt** [comment]
Some more changes:
- 'Manuscript type': change the options to 'manuscript' (manifestation) and 'reconstructed manuscript' (reconstruction)
- 'Sermon': change into 'manifestation'
- Move search filters: 'shelfmark' to the right of 'library'; 'title' to the right of 'date range'; 'status to the left of 'project'.
- Add group 'Authority file' with the following search filters (in this order): 'PASSIM code' (this filter can be removed from the main section of search filters); 'Gryson/Clavis/Other' (this filter can be removed from the main section of search filters; the results should include both automatic and manual Gryson/Clavis/Other codes.);  'Author' (=the AF author); 'Incipit' (=the AF incipit); 'Explicit' (=the AF explicit)  
- Sermon search filters: remove 'Gryson/Clavis (automatic)' and 'Gryson/Clavis (manual)'; add: 'Attr. author'; 'Author type'; 'Incipit'; 'Explicit'; 'Feast'. All to the left of 'Bible reference(s)', except for 'Feast', which should be added to the right of 'Bible reference(s)'.
- Collection/Dataset > HC/manu overlap: This should not be an individual search filter, but the slider should automatically appear when the search filters 'manuscript comparison', 'Historical collection' or 'PD: Authority file' are selected. The value should by default be 100%, with the option to move it to a lower percentage.
- Collection/Dataset > PD: Authority file: add the possibility to use the HC/manu overlap slider for AF datasets too.
