### ISSUE TITLE
HUWA import: linktype changes

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#526]
**NOTE**: this is related to issue #336 

1. Extend the list of `linktype` options to:
    - nearly equals - _already there_
    - partially equals - _already there_
    - echoes - _already there_
    - is part of / has as its part - _Added as:_ `pwh` (part-whole)
    - related to  - _Added as:_ `rel` (relates)
1. Add 'secondary' linktypes, according to the table + explanation below

#### Table
​Directional/explanatory linktype | Can be ​used for   main linktype
-- | --
​uses / used   by | ​all
uses (indirect) / used   by (indirect)​ | all​
​common   source | ​all
​unspecified | all​
​ | ​
​comments   on / commented on in (8) | ​related   to
​​paraphrases   / paraphrased in (16, 18) | echoes
​capitula   (10) | related   to​
t​abula/key/index​ (13) | ​related to
​prologue   (14) | ​related   to
​epilogue (17) | ​related to
​excerpt (11) | ​is   part of / has as its part
​translation   of / translated as (15) | ​​nearly   equals / partially equals

#### Explanation
In de tweede kolom hier, "can be used for...") heb ik aangegeven voor welke primaire linktypes de secundaire linktypes gebruikt zouden moeten kunnen worden. Is het mogelijk om in te bouwen in PASSIM dat een secundair linktype voor een subset van primaire linktypes gebruikt kan worden? Als dat niet kan, of erg lastig is, is dat geen probleem; dan zorg ik ervoor dat het in de input manual komt te staan en is het aan de editor zelf om hier op te letten. 

Voor de linktypes die echt 'directional' zijn, dus twee kanten op, geldt het dat het werk in de HUWA opera-lijst waar het nummer bij staat (kolom J in het bestand), de eerste van de twee moet krijgen. Het werk waar naar verwezen wordt in kolom K, moet dan het tweede linktype krijgen. Een voorbeeld hiervan uit de lijst: rij 168 en 169 zijn opera no. 3 en 5797; opera 5797 heeft als 'relation' 9, verwijzend naar no. 3. Opera no. 5979 moet dan een 'is part of' link naar no. 3 krijgen, en no. 3 een 'has as its part' link naar no. 5797. 

De overige nummers uit de eerste tabel zouden we als volgt willen behandelen bij de import:
- 12: partially equals + een keyword "additional text following" (hier moet een  handmatig een noot bij de link komen met meer uitleg)
- 19: geen linktype, keyword "HUWA linktype collection" (dit moet handmatig op manuscript-niveau worden uitgezocht)

Daarnaast zijn er een aantal van de nieuwe secundaire linktypes waar we momenteel keywords voor gebruiken. Het zou fijn zijn als bij de import de nieuwe AFs met deze linktypes ook direct die keywords kunnen krijgen. Dit gaat om de volgende keywords:

- excerpt (11): keyword 'excerpt'. NB. dit geldt ook voor opera met in kolom C (abk.) "exc." (dit heb ik in een eerder overzicht al staan, volgens mij, maar voor de volledigheid zeg ik het nog maar eens)
- translation of (15): keyword 'translation'

**Comment by ErwinKomen** [comment]
Scheme that combines the above and that figures out the special status of `excerpt`:


​spectype   (can be directional) | Directional | Can be ​used for main linktype | keyword(s)
-- | -- | -- | --
​uses / used   by | yes | ​all | -
uses (indirect) / used by (indirect)​ | yes | all​ | -
​common   source | - | ​all | -
​unspecified | - | all​ | -
​ |   | ​  | -
is part of / has as its part | yes | partially equals | -
​excerpt (11) | yes | ​partially equals | -
​comments on / commented on in (8) | yes | ​related to | -
​​paraphrases   / paraphrased in (16, 18) | yes | echoes | -
​capitula   (10) |   | related to​ | -
t​abula/key/index​   (13) |   | ​related to | -
​prologue   (14) |   | ​related to | -
​epilogue   (17) |   | ​related to | -
​translation   of / translated as (15) |   | ​​nearly   equals / partially equals | -

**Comment by ErwinKomen** [comment]
### Resulting relationship table
```
    relationships = [
        {'rel_id': 1,  'dir': 'no',  'linktypes': ['neq'],        'spectypes': []},               # Nearly equals
        {'rel_id': 2,  'dir': 'no',  'linktypes': ['prt'],        'spectypes': []},               # Partially equals
        {'rel_id': 3,  'dir': 'no',  'linktypes': ['ech'],        'spectypes': []},               # echoes
        {'rel_id': 4,  'dir': 'yes', 'linktypes': [],             'spectypes': ['usd', 'udd']},   # uses/used by (direct)
        {'rel_id': 5,  'dir': 'yes', 'linktypes': [],             'spectypes': ['usi', 'udi']},   # uses/used by (indirect)
        {'rel_id': 6,  'dir': 'no',  'linktypes': [],             'spectypes': ['com']},          # common source
        {'rel_id': 7,  'dir': 'no',  'linktypes': [],             'spectypes': ['uns']},          # unspecified
        {'rel_id': 8,  'dir': 'yes', 'linktypes': ['rel'],        'spectypes': ['cso', 'cdo']},   # comments on / commented on
        {'rel_id': 9,  'dir': 'yes', 'linktypes': ['prt'],        'spectypes': ['pto', 'pth']},   # is part of / has as its part
        {'rel_id': 10, 'dir': 'no',  'linktypes': ['rel'],        'spectypes': ['cap']},          # capitula
        {'rel_id': 11, 'dir': 'no',  'linktypes': ['prt'],        'spectypes': ['pto', 'pth']},   # Excerpt (use keyword 'excerpt')
        {'rel_id': 12, 'dir': 'no',  'linktypes': [],             'spectypes': []},               # additional text follows
        {'rel_id': 13, 'dir': 'no',  'linktypes': ['rel'],        'spectypes': ['tki']},          # tabula/key/index
        {'rel_id': 14, 'dir': 'no',  'linktypes': ['rel'],        'spectypes': ['pro']},          # prologue
        {'rel_id': 15, 'dir': 'yes', 'linktypes': ['neq', 'prt'], 'spectypes': ['tro', 'tra']},   # translation of / translated as
        {'rel_id': 16, 'dir': 'no',  'linktypes': ['ech'],        'spectypes': ['pas']},          # paraphrases
        {'rel_id': 17, 'dir': 'no',  'linktypes': ['rel'],        'spectypes': ['epi']},          # epilogue
        {'rel_id': 18, 'dir': 'yes', 'linktypes': ['ech'],        'spectypes': ['pad']},          # paraphrased
        {'rel_id': 19, 'dir': 'no',  'linktypes': [],             'spectypes': []},               # collection (no HC, but compilations?)
        ]
```

**Comment by MennaRempt** [comment]
All linktypes should be visible on the AF details pages of both linked AFs, so that users can see that there is a link. Currently 'capitula', 'tabula/key/index', 'prologue' and 'epilogue' are one-directional, which means that there is no indication on the AF page of the AF that they're linked to, that there is a link.
