### ISSUE TITLE
Approval: SSG field - one approval per project

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#527]
Part of issue #474 

One approval per project is enough to allow for a field change to be 'okayed'.
So if we have a project with three persons as 'project approver', then the consent of just one of these is enough to let the proposed change be accepted.

**Comment by ErwinKomen** [comment]
### Implications:
1. Adapt check for approval rippling through
    1. Location:
    2. Adaptation: 
1. Adapt approval-queues (views) visible from mypassim:
    1. My field change approval task: 
    2.

**Comment by MennaRempt** [comment]
This doesn't seem to work properly yet: even after a project approver of the project other than the one that made the changes has given approval, all changes remain as "pending". See e.g. for [AF no. 864](https://passim.rich.ru.nl/ssg/details/864/): I have approved the changes Iris made (I have project approval rights for both project connected to the AF), but it seems as if all connected project approvers still need to accept the changes too.

![image](https://user-images.githubusercontent.com/59916079/204560554-d52837e1-233b-4858-b805-becb334fe22d.png)

**Comment by ErwinKomen** [comment]
Okay, this must be related to the chain perculation as explained above in `Implications.2.b`
TODO: Need to check what happens in a specific situation (see my log).

**Comment by ErwinKomen** [comment]
Okay, this was a silly mistake in the code:
``` python
iLeft, iNeeded = change.get_approval_count()
if iNeeded > 0 and iLeft == 0:
```

The code assumes that `iLeft` cannot be lower than `0`, but in the current situation it has become `-3`
This is determined in the function `get-approval_count()`, and that function should **only** count the number of **projects** that are needed and left.
