### ISSUE TITLE
HUWA import: manuscripts to JSON

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#532]
Part of issue #530 

Convert the manuscripts in the HUWA database to JSON

**Comment by ErwinKomen** [comment]
### Implementation

1. Make use of the existing `EqualGoldHuwaToJson`
    1. Read the library info from `huwa_passim_library.json`
    1. Add in the output a section `manuscripts`

**Comment by ErwinKomen** [comment]
### Implementation

1. Make use of the existing `EqualGoldHuwaToJson`
    1. Read the library info from `huwa_passim_library.json`
    1. Add in the output a section `manuscripts`

**Comment by MennaRempt** [comment]
> ### Questions:
> 1. There is no **handschrift** with id `0`, but the first section has 16 items linked to it. What should be done with the first section?

> 2. How do the fields `von_bis` and `bis_f` need to be interpreted?

'von_bis' should be the page/folio number where the manifestation starts and 'bis_f' the page/filio number that the manifestation ends. (although there are some very strange numbers here, like negative numbers, so we have to ask CW for additional explanation).
NB. for the locus, the fields 'von_bis' + 'von_rv' have to be combined to form the start folio/page number, and the fields 'bis_f' + 'bis_rv' have to be combined to form the end page/folio number.
>    1. It looks like the number before the period is the folio number / page number?
>    2. But then for Handschrift `3`, there are numbers after the period - what does that point to?

The numbers after the period could potentially indicate the line number that the manifestation starts, but this does not seem to be compatible with what i see when I scroll down the list in the database... We have to ask for additional explanation here, too.

Handschrift no. 3 is strange anyway, since it has no shelfmark and links to an empty library record (no name), which links to an empty location record (no name, not linked to a country). We'll ask CW what to do with this record, exactly.
> 3. There are quite a few records in `inhalt` that have an opera id `0`. That means these are not connected with a sermon (manifestation) within the Huwa database. What should be done with these entries?

These should be imported as sermon manifestations, but not linked to AFs.

**Comment by ErwinKomen** [comment]
>> 3. There are quite a few records in `inhalt` that have an opera id `0`. That means these are not connected with a sermon (manifestation) within the Huwa database. What should be done with these entries?
>
> These should be imported as sermon manifestations, but not linked to AFs.

**EK**: I'm not sure how that works. If opera id is `0`, then there is no matching opera record, hence no sermon manifestation specification. So would you like me to just add **'empty'** sermon manifestations for those situations?

**Comment by MennaRempt** [comment]
> > > 3. There are quite a few records in `inhalt` that have an opera id `0`. That means these are not connected with a sermon (manifestation) within the Huwa database. What should be done with these entries?
> > 
> > 
> > These should be imported as sermon manifestations, but not linked to AFs.
> 
> **EK**: I'm not sure how that works. If opera id is `0`, then there is no matching opera record, hence no sermon manifestation specification. So would you like me to just add **'empty'** sermon manifestations for those situations?

No, as sermon manifestations with the information found in the table inhalt (i.e. locus) and in the other tables linked to **inhalt**: 
![image](https://user-images.githubusercontent.com/59916079/178957843-7abdf597-a45e-4087-8d18-19b33fa6584d.png)

The document "HUWA-mapping_01.xlsx" (in the wrkgrp folder, data > HUWA database) gives the corresponding PASSIM fields for the HUWA ones.

**Comment by ErwinKomen** [comment]
(responding to the above): I see now. Sorry for the confusion! Importing manuscripts works a bit differently...

**Comment by ErwinKomen** [comment]
Okay, picking this up again (19/sep/2022).
1. Added interface to activate downloading HUWA manuscript as JSON (Manuscript list view)

**Comment by ErwinKomen** [comment]
So, in principle, all of the above is working. 
Closing this issue now...

**Comment by ErwinKomen** [comment]
Okay, from issue #534, there is one thing that **should** be done at the level of making a Manuscript JSON:

>  Opera with only one link to inhalt, should not be linked to an AF

That is to say, when there is: 
1. If record from `opera` is referred to only once from `inhalt` (e.g. 11670) - _this means that there is only one `handschrift` with this opera_
2. Then the JSON output for this sermon should indicate that _no SG nor link to SSG may be created_

**Comment by MennaRempt** [comment]
Answers from CW to the questions above.

The fields for the folio numbers (von_bis, bis_f, von_rv and bis_rv) sometimes have strange contents, such as negative numbers and decimals. How should this be interpreted?

-  decimals (to be exact: the thousends) indicate the relative position of a work in a range, e.g. 14r-25r serm. 1,2,3,4 is represented by 14.001 r 25 r sermo 1, 14.002 r 25 r sermo 2, ... 
-  negative numbers refer to the VD ("Vorderdeckel": nr. -115-111; please treat them as identic, I do not know the difference any more); -110 to the first folia that are numbered separately (I); thus, -110 refers to fol. I, -109 to fol. II, ...
- I had used negative numbers to make sure that these entries are listed before the normal content (on ff. 1r, ...);
- similarily folia numbers 10000 refer to the last pages that are numbered separately (I...)

There is no handschrift with ID 0 in the list of manuscripts, but it does exist in the table inhalt, with 16 linked items. Do you know what manuscript this can be, or is this a HUWA-internal test?
- these data seem to be errors, doublettes without indication of a manuscript => delete them

Handschrift ID 3 has no shelfmark and links to an empty library record (no name), which links to an empty location record (no name, not linked to a country). It has a note "nicht löschen". What should we do with this during the import?
- this empty manuscript was created to have a full set for the request (otherwise MYSQL created an error because the WHERE clause used a not existing entry); if you do not need it (what I think), please delete table entries like this (it should be in every table)

**Comment by ErwinKomen** [comment]
> Below is an example of Huwa **inhalt**.
> 
> ### Questions:
> 1. There is no **handschrift** with id `0`, but the first section has 16 items linked to it. What should be done with the first section?
> 2. How do the fields `von_bis` and `bis_f` need to be interpreted?
>    
>    1. It looks like the number before the period is the folio number / page number?
>    2. But then for Handschrift `3`, there are numbers after the period - what does that point to?
> 3. There are quite a few records in `inhalt` that have an opera id `0`. That means these are not connected with a sermon (manifestation) within the Huwa database. What should be done with these entries?
> 


### Responses (29/sep/2022):

1. There is no **handschrift** with id `0`, but the first section has 16 items linked to it. What should be done with the first section?
    1. **CW**: these data seem to be errors, doublettes without indication of a manuscript => delete them
1. How do the fields `von_bis` and `bis_f` need to be interpreted?
    1. It looks like the number before the period is the folio number / page number?
        1. **CW**: decimals (to be exact: the thousends) indicate the relative position of a work in a range, e.g. 14r-25r serm. 1,2,3,4 is represented by 14.001 r 25 r sermo 1, 14.002 r 25 r sermo 2, ...
        1. **CW**: negative numbers refer to the VD ("Vorderdeckel": nr. -115-111; please treat them as identic, I do not know the difference any more); -110 to the first folia that are numbered separately (I); thus, -110 refers to fol. I, -109 to fol. II, ...
        1. **CW**: I had used negative numbers to make sure that these entries are listed before the normal content (on ff. 1r, ...);
        1. **CW**: similarily folia numbers 10000 refer to the last pages that are numbered separately (I...)
    1. But then for Handschrift `3`, there are numbers after the period - what does that point to?
        1. **CW**: this empty manuscript was created to have a full set for the request (otherwise MYSQL created an error because the WHERE clause used a not existing entry); if you do not need it (what I think), please delete table entries like this (it should be in every table)
1. There are quite a few records in `inhalt` that have an opera id `0`. That means these are not connected with a sermon (manifestation) within the Huwa database. What should be done with these entries?

**Comment by ErwinKomen** [comment]
Processing the CW responses from Sep/29...

### Implementation
1. Ignore (do not import) `handschrift` with id `0`

**Comment by ErwinKomen** [comment]
Read it again (5/oct) with latest counts:

date read | manuscripts | sermons
-- | -- | --
5/oct/2022 | 8444 | 57928

**Comment by ErwinKomen** [comment]
1. Problem: The JSON produced is not completely licit: the last object has a comma after it, where it should not.
2. Resolution:

**Comment by ErwinKomen** [comment]
Fix needed (see issue #534):
1. The datasets for sermons should be `HUWA_sermons`
1. The datasets for manuscripts should be `HUWA_manuscripts`

**Comment by ErwinKomen** [comment]
### More information
Leafing through the HUWA db tables, I recognize that there are some more pieces of information that might be / should be put into JSON and then imported.

1. The `title` of a **sermon** is in table `tit` (which links to  `inhalt`; there could be _multiple_ titles per sermon)

**Comment by ErwinKomen** [comment]
Points arising from the above
1. `Manuscript` library: Passim doesn't distinguish long/short name of library, Huwa does. Action?

**Comment by ErwinKomen** [comment]
Points arising from the above
1. `Manuscript` library: Passim doesn't distinguish long/short name of library, Huwa does. Action?

**Comment by ErwinKomen** [comment]
Okay, for correct processing one more step is needed:
1. Instead of simply adding `opera_id`, add this:
    1. A list of external ids: `[ { "externalid": (opera_id), "externaltype": "huwop" } ]`

**Comment by ErwinKomen** [comment]
### Processing of M (Manuscripts) and S (Sermon manifestations)
1. `col_bem`: separate from collectiones and collinhalt: gives remarks on the number of columns a manuscript has. Add in Cod. Unit: extent. 
    1. EK: _already done_
1. `fasc`, `faszikel`: these are both different ways to indicate numbered codicological units. If possible, for items in handschrift that are either connected to fasc or have an entry in the faszikel column, add one codicological unit for each connection, ordered as the number in fasc or faszikel indicated (if that is not possible, with as the cod. Unit name fasc_name or faszikel_name).
1. `infine`: manifestation: postscriptum (infine_text)
1. `mat_bem`: notes on the material of the manuscript: add in codicological unit: support.
1. `saec_bem`: remarks on the date of manuscripts. Please add this in codicological unit: notes.
1. `siglen`, `siglen_edd`: give information about which manuscripts were used for critical editions (siglen) and which older editions were used for critical editions (siglen_edd). This information should be added to the manuscripts in the form of a note “Used for [edition reference]”.
1. `zeilen_bem`: remarks on the field ‘zeilen’ in the table handschrift; has to be added in codicological unit: extent following the information in ‘zeilen’.
1. `zweitsignatur`: old shelfmarks. Add these in the manuscript details: notes as “Old shelfmark(s): [name]”.

**Comment by ErwinKomen** [comment]
Reminder: we are now working in reader/views.py, class `EqualGoldHuwaToJson`, method `get_data()`.
This class is the base class for `ManuscriptHuwaToJson`, with url name `manuscript_huwajson`, which is the download `Huwa Manuscripts: json` that is callable from the Manuscript Listview

**Comment by ErwinKomen** [comment]
### Siglen and Editions per sermon
Okay, so right now we've made available the `siglen` links (as well as `siglen_edd`) in the downloaded manuscript as a list of combinations between `editionen` id and the `siglen` text.

But actually, if we want to know the literature (including editions) for a particular sermon, we need to look at the Huwa table `editionen` (which is now reader.`Edition` in Passim) and find all entries for a particular `opera` number.

So: instead of taking up the `siglen` information into the manuscript json, it may be better to provide this idiosynchratic siglen information right into the `reader.Edition` system? That way, we can leave the Manuscript JSON idea 'cleaner'.

**Comment by ErwinKomen** [comment]
Okay, this then seems to finishe issue #533, and we now turn back again to #534, to see if it all matches...

**Comment by ErwinKomen** [comment]
Well, ahum, when evaluating the findings, there is one little matter coming up: the **libraries**.
E.g. 
- `Laici` is not recognized as such, because the Passim variant has an additional space
- `Bibliothèque Nationale` is not recognized, because Huwa doesn't add "de France"

Didn't we have a library matching Excel?

**Comment by ErwinKomen** [comment]
### Problems
1. Authors are not appearing

**Comment by ErwinKomen** [comment]
All issues above have been addressed. Perhaps this is enough...
