### ISSUE TITLE
HUWA import: process JSON SSGs

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#533]
Part of issue #530 

Import the SSGs from the HUWA-generated JSON file

### Implementation
The JSON reader is in view `ReaderHuwaImport`, method `read_json()`
For the colored table indicating what needs to be treated in what way: see issue #534

**Comment by ErwinKomen** [comment]
### Import rules for Authority Files (see issue #558)
Potential SSGs with manuscripts (see field `manu_type` in JSON): 
Number of </br> `inhalt` links | Has digit in `abk` | Number of `opera` items </br> (potential SSG) | Import SSG if...
--- | --- | --- | ---
zero (0) | - | 1575 | at least 1 signature
one (1) | - | 5992 | _not specified what to do here_
many | yes | 2568 | at least 1 signature
many | no | 955 | at least 1 signature

The following criterion is **NOT** taken into account:
Potential SSGs with **inc/exp** (see field `existing_ssg` in JSON)
Type | Full | Number
--- | --- | ---
ssgmN | no inc/exp match | 8554
ssgmF | full inc/exp match | 24
ssgmE | empty inc or exp | 2512

What **IS** taken into account: look at the signatures (Gryson/Clavis).

**Comment by MennaRempt** [comment]
For the first table: opera with one inhalt link have to be imported as manifestations, and not AFs/SSGs (see issue #557).

**Comment by ErwinKomen** [comment]
### Implementation

The JSON reader is in view `ReaderHuwaImport`, method `read_json()`

**Comment by ErwinKomen** [comment]
Here is a list of situations where import can go ahead right now.
This is based on parameters `sig_status`, `many_type` and `existing_ssg.type`.

`sig_status` | `manu_type` | `existing_ssg` </br>`type` | Subset | Action
-- | -- | -- | -- | -- 
--any-- | `zero_links` | | all_zero | CW: investigate further
`opera_ssg_0_0` | `many_links_*` | | ssg00_m | create 💡subset - </br>**QUESTION** _or_ import - </br>__or__ have CW first update something or?
`opera_ssg_0_0` | `one_link` | | ssg00_o | create 💡subset - </br>**QUESTION** _or_ import as sermons </br>_or_ both?
`opera_ssg_0_n` |  |  | ssg0n | EK: create 💡subset _done_ </br>MR: check subset _done_  </br>EK: import correction
`opera_ssg_1_0` |  | `ssgmF` | | EK: **import** as new AFs
`opera_ssg_1_0` |  not `zero_links` |  | | EK: **import** as new AFs
`opera_ssg_1_1` |  | `ssgmE`, `ssgmF` | ssg11_ef | EK: **import**: create 💡subset</br>import through matching of HUWA/PASSIM AFs</br>through Gryson/Clavis code</br>**QUESTION**: overwrite what??
`opera_ssg_1_1` |  not `zero_links` | `ssgmN` | ssg11_n | EK: create 💡subset</br>CW: check manually
`opera_ssg_1_n` |  not `zero_links` | | ssg1n | EK: create 💡subset</br>CW: check manually
`opera_ssg_n_1` |  not `zero_links` | | ssgn1 | EK: create 💡subset</br>CW: check manually


Import actions for items from the `ssg11ef` subset:
1. Create an SG for the item
    1. create a new copy of the `Signature`, and link it to this new SG
    1. Add a keyword to the SG to make sure it can be recognized as having resulted from the HUWA import
1. Add this SG to the SSGs equality set
    1. That is to say: link this sg to the correct SSG (the one to which the other SGs with the same `Signature` value link)
1. Add the SSG to the project `HUWA/CSEL`
1. Add the `opera` id from HUWA to the SSG because of:
> Het belangrijkste is dat de manuscripten die in de HUWA-database aan dit opus hangen, bij import ook vlot gelinkt kunnen worden aan de SSG die met het desbetreffende HUWA-opus verbonden wordt, hier dus via een nieuwe SG in de equality set.

**Comment by ErwinKomen** [comment]
### Implementation of import
The actual import (of those situations that are allowed per the above scheme) should be an import of a particular JSON file.
So the course of actions would be:
1. Add an **import** handler `ReaderHuwaImport` in `reader/views.py` for Huwa AF JSON
    1. Add a basic handler for importing SSGs: `ReaderEqualGold` - _added, but needs testing_
    1. Then derive from it the handler `ReaderHuwaImport`  - _working on this_
        1. Add a function to input one opera: `import_one_json()`
        1. Added a model `EqualGoldExternal` to provide a link between an SSG and an external ID, such as the Opera ID
        1. Processing this into the `import_one_json()` function
            1. Made sure to add keyword "HUWA import" to the SG that is created
        1. TODO: process handling of `len(same_sig_ssgs) == 0` inside `import_one_json()` function
            1. Need to consult with MR what to do with this group
        
1. Add reference to `ReaderHuwaImport` it in `urls.py` - _done_
1. Adapt the  `EqualGoldListView`  handler in `seeker/views.py` - _done_
1. What `read_json()` returns must be an object/list that is processable by `ReaderHuwaImport/process_files()` - _done_
1. Process any relations from the `opera_relations` list within the JSON
1. Check different import types:
    1. `ssg11ef` - make SGs under existing SSG/AFs - _asked MR_
    3. `ssg10_f` + `ssg10_nz` - adding new SSG/AFs - _asked MR_
    4. `ssg11n`

**Comment by MennaRempt** [comment]
CW about subset **all_zero**: 

> All opera that are not used anywhere else (e.g. inhalt.opera, editionen.opera, opera.incipit ...) can be skipped.

**Comment by ErwinKomen** [comment]
Okay, we're going to read the HUWA material a.s.a.p...
