### ISSUE TITLE
HUWA import: process JSON manuscripts

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#534]
Part of issue #530 

Import the **manuscripts** from the HUWA-generated JSON file

1. Make sure that the correct **manuscript** JSON is generated from Huwa (see issue #532)
2. Adapt the existing 'import manuscript JSON' function to process this Huwa manuscript JSON

**Comment by ErwinKomen** [comment]
Here is a list of situations where import can go ahead right now.
This is based on parameters `sig_status`, `many_type` and `existing_ssg.type`.

`sig_status` | `manu_type` | `existing_ssg.type` | Other | Action
-- | -- | -- | -- | -- 
any | `zero_links` | | | CW: investigate further
`opera_ssg_0_0` | `many_links_*` | | | create subset - or import - or have CW first update something or?
`opera_ssg_0_0` | `one_link` | | | create subset - or import as sermons or both?
`opera_ssg_1_n` |  |  | | EK: create subset, MR: check subset, EK: import correction

**Comment by ErwinKomen** [comment]
### Implementation of import
The actual import (of those situations that are allowed per the above scheme) should be an import of a particular JSON file.
So the course of actions would be:
1. Add an **import** handler in `reader/views.py` for Huwa AF JSON
    1. Make sure it ends up in e.g. `ssg_uploads`, which can later be used in `seeker/views.py`
1. Add reference to it in `urls.py`
1. Add details of the handler in `seeker/views.py`
    1. It should end up in view `EqualGoldListView` and then in `self.uploads`

**Comment by ErwinKomen** [comment]
### Questions that need answering before importing

1. If a library doesn't exist (yet) in Passim, but is specified in the HUWA (json) with a valid `country`, `city` and `library` name, should that library be created in PASSIM?

**Comment by MennaRempt** [comment]
1. Yes, see excel.
2. The link from sermon to SSG should be made through the field **inhalt** in HUWA, since this is where the manuscript contents are described. Opera with only one link to inhalt, should not be linked to an AF, but just imported as sermon manifestations.  
3. Yes!

**Comment by ErwinKomen** [comment]
### Notes for the implementation
1. When a Sermon is imported from JSON, double check the `manu_count` variable. 
    1. If it is just `1`, then do **not** create an SG on the basis of it, nor make a link with a corresponding SSG

**Comment by ErwinKomen** [comment]
> 1. Yes, see excel.
> 2. The link from sermon to SSG should be made through the field **inhalt** in HUWA, since this is where the manuscript contents are described. Opera with only one link to inhalt, should not be linked to an AF, but just imported as sermon manifestations.
> 3. Yes!

Okay, just double-checking point (2) about when a link from sermon to SSG may be made.
One example that makes me wonder is this one: a sermon in a manuscript, and this sermon only occurs one time in `inhalt`, yet its signatures (as linked to `inhalt`) are pointing to a SG and SSG that are already 'on board'.
But since the opera only occurs once in `inhalt`, still not make the link to the SSG?
``` python
{
  "id": 11,
  "idno": "279",
  "handschrift_id": 15,
  "support": "",
  "extent": "",
  "format": "",
  "library_id": null,
  "library": "Biblioth\u00e8que municipale",
  "lcity": "Tours",
  "lcountry": "France",
  "msitems": [
    {
      "order": 1,
      "parent": "",
      "firstchild": "",
      "next": 2,
      "sermon": {
        "type": "Plain",
        "locus": "v94-r96",
        "author": "",
        "author_id": null,
        "title": "",
        "incipit": "",
        "explicit": "",
        "note": "",
        "keywords": [ "HUWA" ],
        "datasets": [ "HUWA_manuscripts" ],
        "signaturesA": [
          { "editype": "cl", "code": "CPL 284.60", "gold": 1461, "ssg": 1326 },
          { "editype": "gr", "code": "AU s 60", "gold": 1461, "ssg": 1326 }
        ],
        "opera_id": 5741,
        "manu_count": 1
      }
    },
```

**Comment by ErwinKomen** [comment]
### Small fixes
These are some small fixes that were met when importing
1. `Manuscript.custom_add()`: adding to `notes` must not use `self` but `obj

**Comment by ErwinKomen** [comment]
### Action points for JSON-to-DB process 
For the process of importing a JSON Manuscript into Passim, some of the matters above lead to action points.
This is from issue #532 
1. Process `Manuscript.provenances` into the appropriate `Codico`
1. Process `Manuscript.scribeinfo` into the appropriate `Codico`
1. Process `Manuscript.scriptinfo` into the appropriate `Codico`

**Comment by ErwinKomen** [comment]
### More action points
Upon verification of the process, there are some more things that need to be dealt with.
1. Attributed author: is not added, where it should be.
    1. E.g. from manuscript `Cod. 12 H`, sermon 74, the author should be `Augustinus`, especially since `author_id` is given. However, no author is assigned in the process of reading.
    2. First occurrance in test set is sermon 57, author Cyprianus, manuscript `Cod. 14920-22`

**Comment by ErwinKomen** [comment]
### Other points to be aware of

It is possible that two manuscripts result with the same or almost the same `idno` (identifier), e.g:
![image](https://user-images.githubusercontent.com/11887269/211882712-c286a082-67fc-4248-acb8-4fd10786c155.png)

Note the last two manuscripts. The same item is ultimately in view. But the top item `Cod.  641` (with two spaces) is from HUWA and the bottom item `cod. 641` (with one space) is from SERMONES.

**Comment by ErwinKomen** [comment]
All issues above have been addressed. Perhaps this is enough...
