### ISSUE TITLE
MS: search by date range

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#535]
When searching by date range, results should include all manuscripts with a date range that **overlaps** with the date range searched for. E.g. when searching for "500-850", manuscripts with "800-899" should also be included in the results.

**Comment by ErwinKomen** [comment]
Yes, this makes sense. The way it is implemented now is too simplistic:
- Look for database `yearstart` >= search-supplied `date_from`
- And also database `yearfinish` <= search-supplied `date_until`

There should be a more complex OR-combination of several AND-combinations...
Need to solve this in `adapt_search()`, wherever a daterange is used: listviews for S, M, Codico

**Comment by ErwinKomen** [comment]
Okay, seems to be working
