### ISSUE TITLE
Datasets: combine public datasets and My datasets

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#536]
Combine the lists of Public datasets and My datasets into one list "Datasets", that shows both public datasets and private/team datasets in one listview. 

The columns should be as in current 'My datasets', with scope "public" for public datasets.

Add filters: type, scope

cf. issue #434.

**Comment by ThijsRU** [comment]
almost ready: one issue remains: when sorting the standard view (with team, public and private (user specific) datasets, the scope becomes : private, this needs to be corrected
 
-

**Comment by ThijsRU** [comment]
The solution is working but it is probably not the most efficient. After the users navigates to _Datasets_, the correct selection is presented, the Private datasets of the user and the Public and Teams. 

When filtering the first time on any of the three options `scope `will be empty, but after the second time `scope` will remain "priv".

**Comment by ThijsRU** [comment]
After working on issue #433 and checking the correct spelling of the breadcrumbs I saw that there are some issues with the navigation from the detail view of a Public or Team dataset going back the list view. 

This results in a list of all datasets, also those from other users. 

Now everything seems to work as it should be.
