### ISSUE TITLE
Cod. unit: title

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#539]
Currently imported or newly created codicological units without a title automatically get "SUPPLY A NAME" added. Is is possible to delete all the 'SUPPLY A NAME' -titles for existing cod. units, and instead leave the field empty if no title is added? And for newly created cod. units, leave the field empty when the cod. unit is first created.

**Comment by MennaRempt** [comment]
Also: manuscripts that have been assigned a title later still have "SUPPLY A  NAME" in the overview of manifestations on the AF details page (see for example [AF PASSIM 051.1205](https://passim.rich.ru.nl/ssg/details/4024/)).

**Comment by ErwinKomen** [comment]
Okay:
1. Added `adapt_supplyname()` in adaptation.py, section Manuscript listview
2. Changed the default `name` field for `Codico` and `Manuscript` to be able to be `empty`
