### ISSUE TITLE
Cod. unit deletion bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#540]
It's currently not possible to delete a codicological unit from a manuscript. After clicking 'save', the page refreshes and the cod. unit is not deleted.

**Comment by ErwinKomen** [comment]
### Note
There are two ways to delete a codico, one of which is working correctly:
1. In the Manuscript Details view one can 'delete' a codico (from the special codico overview window), and then press **Save** to acivate this.
2. One can go to the Codico details view, and delete the codico from there.

Method 1 is **not** working, but method 2 **is**.

**Comment by ErwinKomen** [comment]
### Follow-up
Okay, the above actions work, but there is one thing not working correctly now: the codicological boundary for codico #2 is not draggable anymore. What happened?
