### ISSUE TITLE
S: 'HC (link)' field

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#547]
The field 'Historical collections (link)' on the sermon manifestation details page does not show the HCs that the linked AF is in. (e.g. https://passim.rich.ru.nl/sermon/details/73766/, which should show two HCs).

**Comment by ErwinKomen** [comment]
Well yes, that's true. It doesn't. 
The popup at "Historical collections (link)" does indeed suggest that it should...
