### ISSUE TITLE
MS template: project label

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#548]
Sermon manifestations in a manuscript template currently can't be edited, because to save them a project label has to be assigned, but they do not have the project label field. The project label should not be needed for the sermons in a manuscript template.

**Comment by ErwinKomen** [comment]
Okay, the warning comes from the `evaluate_projlist()` method defined in seekere/views.py
This method is called in `SermonEdit` class, method `before_save()`
It is there that we should check for template/non-template?
