### ISSUE TITLE
AF visualisation download: CSV

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#550]
If possible, add the option to download the visualisation data in CSV format.

**Comment by ErwinKomen** [comment]
### Implementation
1. This makes use of `seeker/download.html`
2. Added option `csv` after JSON
3. Implementation for the current visualizations
    1. Overlap: views.py, `EqualGoldOverlapDownload`
        1. 
    3. Transmission: views.py, `EqualGoldTransDownload`
    4. Leftover: not done is`EqualGoldGraphDownload`
