### ISSUE TITLE
Manifestation: alternate page numbering

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#551]
- Add an option for editors to add (and make visible) additional page numbering systems, with a notes field for the editor to indicate the origin of the numbering system.

- The alternative page numbering should also be visible in the list of manuscript contents, e.g. between brackets following the main page numbering.

**Comment by ThijsRU** [comment]
Comments Menna:

Het kan soms het geval zijn dat een manuscript paginanummering heeft uit bijvoorbeeld de middeleeuwen en de 18e eeuw, of dat de catalogus de pagina's anders nummert dan dat ze in het manuscript genummerd zijn. We willen dus een manier om alle aanwezige paginanummering in passim weer te geven. Dat kunnen er inderdaad meer dan één (extra) zijn. Ik denk dat het makkelijkst (voor ons, ik weet niet of dat ook het makkelijkst voor jullie is) is om met een +-knop een extra paginanummeringsveld toe te kunnen voegen.

**Comment by ThijsRU** [comment]
Een SermonDescr kan dus meerdere alternatieve paginanummeringen hebbebn

Vraag me af of het goed ingericht is.

# altpages = models.ManyToManyField(AltPageNumber, related_name="altpage_sermons")

Example: Daterange of Path in RIPD
(id)
created
start
end
note
sermon id
