### ISSUE TITLE
Search filters: and/or/not

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#552]
Add the option to apply boolean operators to search filters (AND/OR/NOT). The default everywhere should be AND, with the option to switch to a different choice. This is especially for search filters where multiple options can be selected at the same time (e.g. Gryson/Clavis code; author etc.)

**Comment by ErwinKomen** [comment]
### Implementation
This is implemented in the basic app.
The `basic_list.html` is extended with this patch at two filter places (regular filter and section filter):
```html
                                    <!-- Room for operator -->
                                    <td style="min-width: 80px;" valign="middle">
                                      <span class="filter-operator form-inline">&nbsp;</span>
                                    </td>
```

**Comment by ErwinKomen** [comment]
Okay, checked, works
