### ISSUE TITLE
S listview: title

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#555]
When using the search filter 'title' in the sermon/manifestation listview, the column 'section title' appears instead of the column 'title'. It is possible to manually open the 'title' column, and the search results seem to be as expected.

**Comment by ErwinKomen** [comment]
What exactly is the request?

**Comment by MennaRempt** [comment]
The column 'title' should appear in the listview when a user uses the search filter 'title' for a search. Currently, the column 'section' (title) appears instead.

**Comment by ThijsRU** [comment]
- Ok, section title must be title. 

- for oOrderHead in self.order_heads: in BasicList, this is where the sectiontitle and title columns are made visible, no clear why it does not work for title, it does work for sectiontitle though...
