### ISSUE TITLE
HUWA import: opera as sermon manifestation

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#557]
No immediate action required!

All HUWA opera with one link to **inhalt** have to be imported as sermon manifestations, with no link to any AFs. 

We have to first find a way to check whether the manuscripts they are connected to already exist in the database, keeping in mind the varying ways shelfmarks are described. (language, interpunction etc.)

**Comment by ErwinKomen** [comment]
It seems to me this has been overruled by other considerations.

**Comment by MennaRempt** [comment]
If the opera have a Gryson/Clavis-code, and a matching AF is found, it can be linked to the manifestation.

**Comment by ErwinKomen** [comment]
Okay, settled
