### ISSUE TITLE
AF: links bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#559]
It is no longer possible to link Authority Files to each other. When searching for an AF to link, 'the results could not be loaded' appears. (see screenshot below)

![image](https://user-images.githubusercontent.com/59916079/168008881-127577a6-65ec-40fa-aa8c-cccaa0b318b0.png)

**Comment by ErwinKomen** [comment]
That was due to a final change I had made in the function `label_from_instance()` in form `EqualGoldWidget`.
That's now fixed.
