### ISSUE TITLE
Manifestation: move to another manuscript

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#561]
There should be a way to move a manifestation to a different manuscript (comparable to how Sermon Golds can be moved to a different AF).

**Comment by ErwinKomen** [comment]
Could you be more specific?
There is a marked difference between the two.

When a SG (Sermon Gold) is 'moved', it just changes its affiliation from AF1 to AF2

When a S (Sermon Manifestation) would be moved to a different M (Manusript), what would need to change?
- An S links to a Manuscript via-via:
    1. An S is part of a `MsItem`, which contains its 'order' number as well as its position within the hierarchy of sermons
    2. An `MsItem` links to a Codicological unit (`Codico`)
    3. It's only the `Codico` that links to the Manuscript

In other words, to 'move' an S, the user would have to indicate to exactly which position the S would need to move in the other manuscript.

Alternative way to do this:
1. Provide a button in the Sermon details view 'Move to other manuscript'
    1. Only available for Passim Editors, of course
1. When this button is clicked, the user can select a manuscript (just like AF selection)
1. When the manuscript has been selected, the user can press a button 'Move to selected manuscript'
1. The Sermon is **added to the end** of the Sermon Collection in that Manuscript
1. The user will then need to re-position that Sermon within that Manuscript/Codicological unit, as desired

**Comment by MennaRempt** [comment]
The alternative way sounds good! This is mostly so that manuscripts that are in the database multiple times can easily be consolidated.

**Comment by ErwinKomen** [comment]
Okay, this will be worked at either by Thijs or Erwin, when it is due w.r.t. priorities

**Comment by ErwinKomen** [comment]
## Implementation
1. Add a button **Move to other manuscript** in the Sermon details view
