### ISSUE TITLE
MS hierarchy bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#564]
Sometimes nested hierarchical elements (i.e. hierarchical elements whose parent is another hierarchical element) disappear, making the sermons nested under them move to the bottom of the list of manuscript contents. 
Example: for the following ms: [https://passim.rich.ru.nl/manuscript/details/2352/](https://passim.rich.ru.nl/manuscript/details/2352/) at 15-06 12:37 (10:37 in revision history)

I have not been able to figure out under what circumstances this happens.

**Comment by ErwinKomen** [comment]
Thanks for the clear reference. Looking at the revision history around that time:
![image](https://user-images.githubusercontent.com/11887269/183858460-6e7f83d1-dd48-4d63-b50f-8fcf65f64c68.png)

What sticks out is what happens just prior to 10:37, namely 10:35 - that's when in the hierarchy details a `'sermon': 'none'` appears. How did that get there? Could this have anything to do with it? I'm not sure, but let's look...

Checking on the `Action` table: there are 108 instances of  `'sermon': 'none'` 
ALl with savetype `change` and actiontype `save` for itemtype `Manuscript`.
And this has been occurring from july 2020 until june 2022.
