### ISSUE TITLE
AF: editable links

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#570]
AF links (linktypes, alternatives, note) should be editable. Currently it is possible to click through to the Authority File Link details page, and to begin to edit the link. However, it is impossible to actually save the edits. After clicking save, the page becomes empty, and the link remains unchanged.

view of AF link details page after trying to edit it:
![image](https://user-images.githubusercontent.com/59916079/178944859-bff9765e-618c-4b74-adbb-320d6cf33099.png)

**Comment by ErwinKomen** [comment]
This is the /ssglink/details/NNNN page.
Indeed, it comes up fine, appears to allow editing, but then there is a problem...

View: `EqualGoldLinkEdit`, form `EqualGoldLinkForm`
Edited the `mainitems` to include hidden values for src and dst
