### ISSUE TITLE
MS: link MSS to each other

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#571]
It should be possible to manually link manuscripts to each other, which would be displayed on the MS details page as 'Related manuscripts'. There should be the option to add a note to this link, to explain the nature of the link. The link should be bi-directional, so appear on both of the linked MS details pages.

This does not affect the contents; it is purely so that we can create an actual link to a related manuscript, rather than having to give this as a note. Users then do not have to separately look up the related manuscript, but are able to click through to the relevant page.

This would for example be used to: link two (or more) manuscripts that are volumes of the same homiliary (copy); link a reconstructed MS with the MSS containing the cod. units used for the reconstruction; link MSS that we know are direct copies of each other.

**Comment by MennaRempt** [comment]
Update: if a manuscript contains a cod. unit that is used for a reconstructed manuscript, this should automatically be shown on the manuscript details page.

**Comment by ErwinKomen** [comment]
### Point 1: Manuscript linking

I found this confusing, because it reminded me of issue #526. It took me a while, but then I finally realized that the latter is for SSG-SSG relations, while this issue is for MS-MS relations.

#### Implementation
1. Add table for the link between manuscripts:
2.

**Comment by ErwinKomen** [comment]
### Point 2: Codico signal
The request is to signal on a manuscript detail's page, if one of its codicological units is used for a reconstructed manuscript.

#### Implementation
1. Determine where to show this: 
    1. Within the heading of "Manuscript identifier details"?
    2. As a separate line in the main details section?
    3. On the line "Codicological" by a special (red) warning sign?
    4. Within the relevant codicological unit itself?
