### ISSUE TITLE
S: link manifestations to each other 

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#572]
Add the possibility to link manifestations to each other **within the same MS**. There should be an option to add a note to explain the nature of the relation. As in issue #571, this should just create a clickable link to the linked manifestation, not change anything about the manifestation. 

This would be used to e.g. link manifestations that are split up through later disordering of the pages; to link a manifestation to a reference to that manifestation in the same MS ("require"); to link the parts of split sermons to each other.

**Comment by ErwinKomen** [comment]
### Implementation
1. Add table for the link between **sermons**: `SermonLink`
    1. It has a `linktype` default set to `rel` (relation) for possible future use
    2. And it has a field `note` to facilitate a note by the user
    3. When a ManuscriptLink is saved or deleted, the number of links per sermon (field `sermocount`) is adapted
