### ISSUE TITLE
PRE: group saved items

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#574]
See issue #385 

> It should also be possible to:
> - group saved items together

**Comment by ErwinKomen** [comment]
### Question
What does it mean to "group saved items"???
Is that like a hierarchy (well, at least up to one level)??
And should a group have a name or not?

**Comment by MennaRempt** [comment]
"Grouping items" means that the user can create categories that they can add items to that they want to have together. It would be good to be able to name the groups. It should be possible to mix types of items in categories. This way a used can e.g. create different groups for different research projects they're working on. 
It sounds good if it works like the hierarchies, with the drag-and-drop system. But if something else is easier or makes more sense, that's also fine!

**Comment by ErwinKomen** [comment]
### Model ideas
Okay, well, we could do the following in terms of grouping at the model level:
1. Add model (dct/models): `SaveGroup`, which would (just like `SavedItem`) need to be linked to a particular user
2. Add an optional FK to a `SaveGroup` from a `SavedItem`

**Comment by ErwinKomen** [comment]
### Implementation
1. Add items to existing group:
    1. Drag and drop item to (a) group-name-row or (b) item in a different group.
        1. This uses basic.js adaptation of `related_dragenter()` and newly added `related_dragentergroup()`. There also is a helper function `related_update()`
        2. All of the needed functionality is in template `rel_view.html`
        3. It should also have been implemented in `basic_details.html`, but there could be things missing from there

**Comment by ErwinKomen** [comment]
### Follow-up
When one presses the button "add new group", and then presses "Cancel" - still a new group is added
