### ISSUE TITLE
PRE: add saved items to dataset

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#575]
See issue #385 

> It should also be possible to:
> - select saved items to add to an existing personal dataset

**Comment by ErwinKomen** [comment]
But 'personal datasets' are itemtype specific (e.g only M, only S, only SSG and so on), while saved items are generic (they can be of any itemtype). See issue #386

**Comment by shariboodts** [comment]
The first option seems simpler to me, from the point of view of the user. If it is also easier/same level of difficulty for you, Erwin, I propose 1.

**Comment by ErwinKomen** [comment]
Okay, I've started implementing this.
Approach:
1. Add a multiple choice select2 field `Saved items:` to the details view of **Dataset**
    1. THis is done in `CollAnyEdit`, with `settype == 'pd'`
    2. The datasets must have a consistent contents, and these can be of type: `sermo`, `manu`, `gold`, `super`
        1. But note that datasets of type `gold` should not have this field `Saved items:`, because there are no SermonGold saved items
1. Create appropriate list-fields for the `CollectionForm` that _only_ offer a choice of M/S/SSG, that are part of the particular user's Saved Items
    1. Four list fields: `sitemlist_manu`, `sitemlist_sermo`, `sitemlist_gold`, `sitemlist_super`
    2. Appropriate widgets to show the right contents
    3. Initialize querysets to 'none' (empty)
    4. Fill querysets for a particular instance of `Collection`
        1. Get all the M/S/SSG instances associated with the `SavedItem` instances of the user for the particular `sitemtype` (which can be `manu`, `serm`, `ssg` - no _gold_)
        2. Exclude the M/S/SSG that are currently part of the instance Collection

### Verification
1. Sermons: works (20/jun)
2. Authority Files: works (20/jun)
3. Manuscripts:

**Comment by ErwinKomen** [comment]
Okay, all working as expected.
