### ISSUE TITLE
Granting PASSIM editor rights 

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#577]
Add an option/interface for Shari and Menna to give users editor rights.

**Comment by ErwinKomen** [comment]
This option should be for anyone belonging to the group `passim_moderator`

**Comment by ErwinKomen** [comment]
Perhaps it is simplest to extend the `profile/list`  and `profile/details` views...

### Implementation
1. Extend the profile details view
    1. Add a button for moderators: `Grant editor rights`
    2. Add a button for moderators: `Remove editor rights`
1. Extend the profile list view
    1. Make it possible to filter on the name and/or email of the person

**Comment by ErwinKomen** [comment]
### Result
The above is implemented.
A moderator is now able to grant or revoke editor rights to a particular person.
This is done via menu Import Tools > User Profiles, search for the person (email or name), edit the profile, bottom row has a "editor rights" yes/no box.
