### ISSUE TITLE
Overlap network: nodes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#578]
1. Alle nodes even groot in standaardmodus: niet alle nodes zijn even groot in de ‘standaard’ modus (bij een hogere degree); dit zou wel zo moeten zijn; alleen na het aanklikken van ‘manuscript count’ zou de grootte van de nodes moeten veranderen naar gelang het aantal gelinkte manifestaties.
Een voorbeeld is het netwerk hieronder (afb. 1); de node linksboven is groter dan de andere, zonder dat ‘Manuscript count’ modus aan staat. Ze zouden allemaal even groot moeten zijn in de standaard modus

3. In 'manuscript count' modus worden sommige nodes té groot (NB. voor na de HUWA manifestations import.)

4. Labels bij nodes: Sommige nodes ‘verliezen’ hun label na in- of uitzoomen (zie het voorbeeld van AU s 169 hieronder, fig. 4). Elk label zou bij de juiste node moeten blijven, ook bij in- of uitzoomen.

Images in: [22.08.18_Overlap network.docx](https://github.com/ErwinKomen/RU-passim/files/9468613/22.08.18_Overlap.network.docx)

**Comment by ErwinKomen** [comment]
### Implementation

1. Fixed node size in 'standard' modus
    1. ll
