### ISSUE TITLE
Overlap network: readability

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#579]
Leesbaarheid: Ik vergeleek het huidige netwerk met dat van (ongeveer) een jaar geleden, en er lijkt iets veranderd qua leesbaarheid (zie afb. 2 en 3). Ik weet niet zo goed waar dit precies aan ligt. Het aanpassen van de ‘gravity’ helpt niet veel.

a. Is het de lengte van de edges, die nu vaak veel langer lijken? Kunnen we dit aanpassen?
b. Ook het slepen en manipuleren van het netwerk werkt niet meer als eerder (de weggesleepte nodes blijven niet staan waar ze zouden moeten staan; het netwerk verschuift en verspringt oncontroleerbaar) 
c. Een ander voorbeeld van dit probleem is het eerstegraads netwerk van PS-ILD s 7 (afb. 6 hieronder). Dit eerstegraadsnetwerk heeft een vreemde vorm (zeer lange edges, onleesbaar) vergeleken met het eerstegraadsnetwerk van PS-AU s 121 (rond netwerk met de begin node in het midden, goed leesbaar).

Afbeeldingen in: 
[22.08.18_Overlap network.docx](https://github.com/ErwinKomen/RU-passim/files/9468651/22.08.18_Overlap.network.docx)

**Comment by MennaRempt** [comment]
Hierbij aansluitend een paar vragen: 
- Op basis van welk algoritme worden de visualisaties gegenereerd? Ger zal dit in de technische informatie in de user manual zetten.  
 - Is het mogelijk verschillende algoritmes aan te bieden, waaruit de gebruiker kan kiezen? (bijv. de drie meest gebruikte/beste van gephi)
- Wordt er nu een ander algoritme gebruikt dan vorig jaar, waardoor het uiterlijk van het netwerk zo is veranderd?

**Comment by ErwinKomen** [comment]
> Hierbij aansluitend een paar vragen:
> 
> * Op basis van welk algoritme worden de visualisaties gegenereerd? Ger zal dit in de technische informatie in de user manual zetten.
> * Is het mogelijk verschillende algoritmes aan te bieden, waaruit de gebruiker kan kiezen? (bijv. de drie meest gebruikte/beste van gephi)
> * Wordt er nu een ander algoritme gebruikt dan vorig jaar, waardoor het uiterlijk van het netwerk zo is veranderd?

1. We gebruiken [https://observablehq.com/@d3/force-directed-graph](d3 force directed graph)
2. Er zijn 'parameters' in te stellen, zoals gravity, collition etc.
3. Vorig jaar zelfde 'd3 force directed graph'. Wellicht zijn parameters iets gewijzigd

**Comment by ErwinKomen** [comment]
### Implementation and comments
... for the readability issues

> a. Is het de lengte van de edges, die nu vaak veel langer lijken? Kunnen we dit aanpassen?
> b. Ook het slepen en manipuleren van het netwerk werkt niet meer als eerder (de weggesleepte nodes blijven niet staan waar ze zouden moeten staan; het netwerk verschuift en verspringt oncontroleerbaar)
> c. Een ander voorbeeld van dit probleem is het eerstegraads netwerk van PS-ILD s 7 (afb. 6 hieronder). Dit eerstegraadsnetwerk heeft een vreemde vorm (zeer lange edges, onleesbaar) vergeleken met het eerstegraadsnetwerk van PS-AU s 121 (rond netwerk met de begin node in het midden, goed leesbaar).

1. Length of the edges
    1. There is a function `.distance()` that is added to the `.force("link", ...)` call. 
    2. I have now made it into a variable `distance_factor`, and changed it from 100 to 50. This yields e.g. the following for PS-AU s 121:

![passim_EqualGold_1176](https://user-images.githubusercontent.com/11887269/189662994-2bd0a085-de2c-4713-9fe6-1c14ceee80e8.png)
