### ISSUE TITLE
HC: literature bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#582]
When adding literature references to a Historical Collection, multiple duplicates are added automatically. 

See e.g.  https://passim.rich.ru.nl/collection/hist/details/958/ (also visible in the revision history that the literature is added multiple times in the same exact second)

**Comment by ErwinKomen** [comment]
### Investigation...

1. The method `custom_init()` of view `CollAnyEdit` apparently _allways_ adds a `ClitFormSet`
    1. Reduced this to one time: double checking to see if it already contains one with prefix `clit`
