### ISSUE TITLE
MS template: manifestation not viewable

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#584]
The manifestations details for template manuscripts are not show when the manifestation is opened; instead, the page is blank with only the status shown and the indication that it is a template. This is also the case when adding a new manifestation to the template.

![image](https://user-images.githubusercontent.com/59916079/196653958-5a343458-ed83-4c3a-8f5e-3a71af58e393.png)

cf. issues #503 and #506 and issue #548

**Comment by ErwinKomen** [comment]
(This error was unrelated to issues #503, #506, #548)

Problems:
1. View `SermonEdit`, method `add_to_context()` was not inside try/except, so the error was shown for basic
2. The actual error was in the code that excludes 'locus', which assumed the presence of `field_key` everywhere, but for templates this is not the case

COrrected the above, and the matter is now solved
