### ISSUE TITLE
MS search filter: location

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#588]
Currently, non-city locations are not available in the dropdown menu in the MS search filter 'city/location'. However, when entered exactly, they _can_ be used to search (e.g. "Montecassino"), and will yield the expected results.

Non-city locations should also appear in the dropdown menu like city locations.

**Comment by ErwinKomen** [comment]
This is basically only the typeahead that needs changing.
1. I added `cityloc_ta` to form `SearchManuForm`, and initialized the typeahead to `locations`, which includes cities (and more).
