### ISSUE TITLE
AF listview: Author sorting

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#590]
In the AF listview, the authors should be sorted alphabetically on first name, rather than on last name. This is already the case for the Author listview, and the Manifestation listview.

(e.g. currently 'Caesarius Arelatensis' comes before 'Augustinus Hipponensis' when sorting by author.)

**Comment by ErwinKomen** [comment]
This proves more difficult, because the underlying problem is different.
The problem is that the select-column intervenes. The sort column is correctly passed on (numerically), but then sorting doesn't take place on the right column.
