### ISSUE TITLE
AF listview: contains number

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#591]
The number given in the 'contains' column in the AF listview is not always correct. This may have to do with the HUWA imported SGs not showing up? e.g. for PASSIM 008.0632 the number given is '1', but there are 4 SGs in the equality set of the AF.

**Comment by ErwinKomen** [comment]
Verified, and this is true.

1. Most likely cause: the 'contains' number is 'pre-calculated' into the `sgcount` field. Probably the calculations have not been kept up-to-date correctly
    1. What is the re-calculation method?
    1. Where are the places this method is called?
    1. Which places are missing??
