### ISSUE TITLE
AF listview: column sorting

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#593]
In the AF listview, when clicking a column heading to sort the listview by that column, the listview is instead sorted by the column to the left of the intended column. Clicking a column heading should sort the listview by the selected column.

**Comment by ErwinKomen** [comment]
Sorting on the first four (4) columns is okay.
Sorting on the columns 'Manifestations' until 'Status' is faulty: the column left of it is used for sorting.
The reason: there is an additional column with 'saved item' asterikses.

**Comment by ErwinKomen** [comment]
Working correctly now.
