### ISSUE TITLE
HUWA import: tables processing

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#596]
Instructions are needed to be able to know what to do with each of the Tables in HUWA.

**Comment by ErwinKomen** [comment]
Unprocessed HUWA tables (from issue #532): instructions
1. Archiv: can be ignored
1. autor_editionen: SG-author (connected to opera through editionen). Only two items?
1. Bearbeiter: editors of HUWA volumes, i.e. who was responsible for the entry for a specific manuscript (connected to handschrift). Should be shown in some way, but not completely sure how. 
1. Bhl: SG: Clavis-code (in the format: “BHL [name]”). Connected to opera
    1. EK: so this Clavis code should be tied to the relevant SG (it then appears at the SSG / AF)? We will need to do this as post-processing of already imported SGs, then.
1. Bhm: SG: other code (in the format “BHM [name]”). Connected to opera
    1. EK: same question: tie this other code to the relevant SG (it then appears at the SSG / AF)?
1. Bloomfield: Add to SG -  HUWA literature table with the following information: 
Author: Bloomfield, Morton W.
Title: Incipits of Latin works on the virtues and vices, 1100-1500 A.D.
Year: 1979
Pp: [name]
Location: Cambridge, MA
    1. EK: okay, this, then, also is post-processing of already imported SGs
1. collectiones, collinhalt - these could be processed separately?: collectiones and collinhalt together give Historical Collections, with collectiones containing the names of the collections and collinhalt the position of opera (AFs) in the collection. We will have to see how many of those collections are not present in PASSIM yet.
    1. EK: True, we don’t have to do these right now already. They could be done later
1. col_bem: separate from collectiones and collinhalt: gives remarks on the number of columns a manuscript has. Add in Cod. Unit: extent. 
    1. EK: already done
1. Datentraeger: can be ignored.
1. Edenda: can be ignored.
1. Editionen: Processed in issue #587
1. Fasc, faszikel: these are both different ways to indicate numbered codicological units. If possible, for items in handschrift that are either connected to fasc or have an entry in the faszikel column, add one codicological unit for each connection, ordered as the number in fasc or faszikel indicated (if that is not possible, with as the cod. Unit name fasc_name or faszikel_name).
1. handschrift_archiv: for internal purposes, can be ignored.
1. Hilfe: can be ignored (contextual help for data input)
1. Huwa: internal references to other HUWA volumes. Add this in SG: bibliography, preceded by “HUWA”.
1. Indiculum: list of titles from Possidius’ indiculum (a late antique list of Augustinian texts). The sermons from this list are already entered into PASSIM as SGs with in the ‘other code’ the numbers as “Possidius [indiculum signatur],[indiculum_genus] [indiculum_nummer]” and separately as other code [text]. If the indiculum_genus is empty, the comma separating it from indiculum_signatur is not present. Can we use this to see how many are present in HUWA but not in PASSIM (and vice versa, but probably there are more in HUWA than PASSIM)?
1. Infine: manifestation: postscriptum (infine_text)
1. katalog_inhalt, katalog_name: this should link a catalogue reference to manifestations, but the actual reference is not given anywhere, making this information unusable. Can be ignored.
1. Links: can be ignored.
1. Literatur: literature references for opera; processed with issue #587.
1. literatur_archiv: can be ignored
1. Loci: fragmentary table, planned for referring to specific places of an edition (for incipit and desinit entries). Links to editionen, so can also be used in the HUWA editions table in issue #587. 
1. mat_bem: notes on the material of the manuscript: add in codicological unit: support.
1. Nebenwerk: links excerpts to the main work. The column ‘opera’ gives the ID for the excerpt, the column ‘hauptwerk’ gives the ID (opera) for the main work; the column ‘ist_von’ gives the relationship. If possible, add these as ‘partially equals: is part of’ links from opera to hauptwerk, with the text in ‘ist_von’ as a note.
1. Personen: should be merged with verfasser.
1.  personen_publikationen: bridge between personen and publikationen
1. Publikationen: should be merged with literature
1. reihe, reihealt: already processed in issue #587. Reihealt can be ignored.
1. Retr: reference number to Retractationes  (a collection of changes and additions to his works published by Augustine at the end of his life). Connected to opera. Can these be shown on the SG page in a separate field ‘Retractationes’? With the following information:
    - ‘name_knoell’ as follows: “P. Knöll (ed.), Retractationes, CSEL 36 (1902): [name_knoell]” 
    - ‘name_mutz’ as follows: “A. Mutzenbecher (ed.), Retractationum Libri II, CCSL 57 (1984): [name_mutz]”
1. Rubriken: can be ignored
1. saec_bem: remarks on the date of manuscripts. Please add this in codicological unit: notes.
1. Schoenberger: Add to SG -  HUWA literature table with the following information: 
Author: Schönberger, R. and Kible, B. (eds.)
Title: Repertorium edierter Texte des Mittelalters aus dem Bereich der Philosophie und angrenzender Gebiete
Year: 1994
Pp: [name]
Location: Berlin
1. Stegmueller: Add to SG - HUWA literature table with the following information:
Author: Stegmüller, F.
Title: Repertorium Biblicum Medii Aevi
Pp: [name] 
1. siglen, siglen_edd: give information about which manuscripts were used for critical editions (siglen) and which older editions were used for critical editions (siglen_edd). This information should be added to the manuscripts in the form of a note “Used for [edition reference]”.
1. Thll: SG – other code “TLL [name]”
1. User: can be ignored.
1. verfasser, verfasser_literatur: author names for secondary literature and editions. Already used for issue #587?
1. Verkn: “this is a very necessary table that contains any relational information, e.g. for making a reference from one item (opera, bibliothek, manuscript, …) to another, from one field to a specific bibliographic information”. 
1. Verlage: can be ignored.
1. zeilen_bem: remarks on the field ‘zeilen’ in the table handschrift; has to be added in codicological unit: extent following the information in ‘zeilen’.
1. Zweitsignatur: old shelfmarks. Add these in the manuscript details: notes as “Old shelfmark(s): [name]”.

**Comment by ErwinKomen** [comment]
### Post-processing for SSG and SG

Use reader view `EqualGoldHuwaOpera`

**Comment by MennaRempt** [comment]
Additional information:

1. **bearbeiter**: Add this into the MS identifier details, in the notes field as: "HUWA Bearbeiter: [vorname] [name]" 
2. **Indiculum**: Can these be connected to existing SGs/AFs as the opera were? In Passim this information is added as two 'other codes' to the same SG: 
i. "Possidius [indiculum signatur],[indiculum_genus] [indiculum_nummer]" (if indiculum_genus is empty, the comma preceding it is left out as well)
ii. "[text]" (only if there are no other signatures excerpt for the Possidius code, i.e. if it cannot be identified with a known Augustinian sermon)
If the item can be identified with an existing SG/AF, nothing has to be done; if it cannot, then it has to be imported as a new SG (and AF) with the codes as described above, and author 'Augustinus Hipponensis', and the AF keyword 'deperditus'.

**Comment by ErwinKomen** [comment]
### Implementation

1. Retractationes
    1. Added field to model `SermonGold`
    2. Added field to view: `SermonGoldEdit`

**Comment by ErwinKomen** [comment]
Hang on... some of these still need inc/exp, which are retrievable via `opera`
(The batch of `indiculum` that doesn't have a link in `identifik` misses out on inc/exp, obviously)

**Comment by ErwinKomen** [comment]
Okay, done

**Comment by ErwinKomen** [comment]
### Resolving remaining unclarities
1. `nebenwerk`: links excerpts to the main work. The column `opera` gives the ID for the excerpt, the column `hauptwerk` gives the ID (opera) for the main work; the column `ist_von` gives the relationship. If possible, add these as ‘partially equals: is part of’ links from opera to hauptwerk, with the text in ‘ist_von’ as a note.
    1. **EK**: But this is only needed, if both the opera as well as the hauptwerk have led to a SSG / AF, right? (If they only made it to Sermon [manifestations], then we can’t make such a link, I think)
    2. **MR**: _Ja, inderdaad, als zowel opera als hauptwerk een AF zijn (of als SG onderdeel van een AF). Als er aan hauptwerk gelinkte opera zijn die als manifestation worden geïmporteerd, kunnen we dan een link naar de AF maken, en bij de manifestatie het keyword "excerpt" toevoegen en de text uit "ist_von" in de note zetten? Dan gaat de connectie in ieder geval niet verloren._

1. `personen`: should be merged with verfasser.
1. `personen_publikationen`: bridge between personen and publikationen
1. `publikationen`: should be merged with literature
    1. **EK**: I don’t see how ‘personen’ or ‘publikationen’ connect to editionen or literatur. 
    They seem to be completely outside of that system, not connected to anything else.
    Or am I missing something?
    1. **MR**: _Zijn inderdaad niet verbonden met editionen of literatur, maar publikationen en literatur geven dezelfde soort informatie in verschillende tabellen, dus de informatie uit publikationen kan precies hetzelfde verwerkt worden als die in literatur. (publikationen is via edenda aan opera gekoppeld.)_


1. `verkn`: “this is a very necessary table that contains any relational information, e.g. for making a reference from one item (opera, bibliothek, manuscript, …) to another, from one field to a specific bibliographic information”. 
    1. **EK**: sorry, but I don’t see how this works. E.g:
        1. inhalt 6341 is tied with inhalt 6342. Both are sermons (manifestations). What should be done?
        1. Handschrift 1218 is tied with literatur 112. What should be done??
        1. Opera 5468 is tied with opera 11672. Are they equal? What should be done?
        1. Relation numbers 0, 1, 2, 3, 4 – what do they represent?
    1. **MR**: _ik hoopte eigenlijk dat jij daar wijs uit zou kunnen worden, voor mij was het ook niet echt duidelijk wat voor relatie Clemens hier bedoelt... Ik denk dat we dat aan hem zullen moeten vragen._

**Comment by ErwinKomen** [comment]
### Implementation: nebenwerk
This pertains to `opera` items that have been read as `SermonDescr`. That simply hasn't happened yet. Issue #534 treats importing HUWA-generated JSON manuscripts, and this matter should be taken up as part of that issue.
