### ISSUE TITLE
HC: scope

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#599]
Currently it is possible to make 'private', 'team' and 'public' Historical Collections; instead, the only possible scope should be 'public'. All currently existing private and team HCs should become 'public' as well.

**Comment by ErwinKomen** [comment]
### Implementation

1. One-time: convert existing private/team into public
    1. That can be done via seeker/adaptations in the HC listview
1. Disable 'scope' setting for HC details view
2. Turn scope into 'public' when collection turns from PD into HC

**Comment by ErwinKomen** [comment]
### Related
On a related note, I observed something else.
When the Tools > Dataset is filtered (doesn't matter on what), all of a sudden the settype is no longer kept to `pd`, but also includes `hc`
