### ISSUE TITLE
User comments: 'unread user comments' indicator

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#600]
The user comments in the user comments listview should have an indicator of whether they are read or unread (bolded timestamp if unread, normal if read?)

**Comment by ErwinKomen** [comment]
### Strategy
What marks that a user comment is 'read'? 
A user comment is stored in `Comment`, which has fields: 'content', 'profile', 'otype', 'created'.
Perhaps: add a `ReadComment` object that links a Profile with a Comment and adds a 'read' date (datetime)?
