### ISSUE TITLE
user comments: replies

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#601]
It should be possible for editors to reply to user comments from the UserCommentEdit details page, and for the user who added that comment to get an email with the original user comment and the reply. The reply should be visible in the UserCommentEdit details. It should be possible but not automatic for the editor to make the reply visible in the overview of user comments that can be opened for each item. If the reply is made visible, it should be indicated that the reply is from a PASSIM editor. (e.g. indicated after the username?)

**Comment by ErwinKomen** [comment]
### Contents of this request
1. **Editors** should be able to **reply** to a user comment in the details page
    1. The reply should be visible in the details page??
    2. When a reply is made (by an editor):
        1. Send an email 
            1. To: user who made the comment
            2. From: editor - this should be `PASSIM editor` ??
            3. Contents: original user comment + reply
1. Visibility of the reply:
    1. The editor should have a place to indicate that the reply may be visible or not in the overview
    2. If the reply should be visible: 
        1. make it visible in the overview of user comments that can be opened for each item
        2. make sure that the 'from' field includes  `PASSIM editor` _after the username_

**Comment by ErwinKomen** [comment]
### Implementation

1. Add model `CommentResponse`: this is the response to one particular comment
    1. Migrate with this new model
    2.

**Comment by ErwinKomen** [comment]
### Implementing visibility

1. **Visibility** of the reply:
    1. The editor should have a place to indicate that the reply may be visible or not in the overview
        1. Add a field "visible in overview" (boolean, checkbox??)
    2. If the reply should be visible: 
        1. make it visible in the overview of user comments that can be opened for each item
        2. make sure that the 'from' field includes  `PASSIM editor` _after the username_

**Comment by ErwinKomen** [comment]
Result is something like this:
![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/f5af48a3-467b-47c8-8a02-8c4ad117585a)
