### ISSUE TITLE
Manif.: Bible reference bug

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#602]
Sometimes when a Bible reference is deleted, it remains visible on the manifestation details page, for example in [sermon /105936](https://passim.rich.ru.nl/sermon/details/105936/). This reference is not visible in the edit view and thus cannot be deleted again.

**Comment by ErwinKomen** [comment]
Observation is right!

### Details
1. Value shown in details view
    1. That is calculated by `instance.get_bibleref()`, with instance being the SermonDescr instance
    2. This basically takes the `self.bibleref` field, which is a kind of in-between placeholder
        1. Then it checks for actually biblereferences through `self.sermonbibranges.count()`
        2. But... it only calculates + corrects `self.bibleref`, if there **are** related bibranges
1. Resolution:
    1. As soon as we find out that `self.sermonbibranges.count()` is zero, the value of `self.bibleref` should be cleared

**Comment by ErwinKomen** [comment]
Okay, fixed
