### ISSUE TITLE
Listview: number of items per page

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#603]
For any listview, users should be able to change the number of items shown on a page. The available options should be: 20 (default, current number of items), 50 or 100. 

NB. if you think that 100 would slow down the database too much, a maximum of 50 is ok.

**Comment by ErwinKomen** [comment]
Okay, this is partly already available.

### Implementation
1. Add code to the `basic_list.html` to show (a) current pagination value and (b) allow choosing between the indicated options.
