### ISSUE TITLE
Stable URI button

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#605]
For Authority files, Manuscripts, Manifestations and Historical Collections, add a button  with the stable URI to the left of the user comment button on the details page. Clicking this button should copy the URI to the user's clipboard. 

Cf. Trismegistos (e.g. [https://www.trismegistos.org/authorwork/78](https://www.trismegistos.org/authorwork/78)):
![image](https://user-images.githubusercontent.com/59916079/204550134-28f6a2cb-5a57-40cb-8451-a21ad132a3d4.png)

**Comment by ErwinKomen** [comment]
### Implementation
1. Add function `get_abs_uri()` to view `BasicDetails`
2. Adapt `basic_details.html` to accommodate `stable_uri`
3. Add `stable_uri` to `context` in these items:
    1. ManuscriptEdit - _done_
    1. EqualGoldEdit - _done_
    1. SermonEdit - _done_
    1. CollAnyEdit (with settype `hc`) - _done_
