### ISSUE TITLE
Cod. unit: contents after deletion

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#606]
When a codicological unit is deleted, the manifestations that were part of it are currently moved to the top of the preceding codicological unit. They should instead be added at the _bottom_ of the contents of the preceding codicological unit (so that the order within the manuscript as a whole is kept intact as much as possible).

**Comment by ErwinKomen** [comment]
### Finding my way
1. Where does deletion of a codico happen in the application?

**Comment by ErwinKomen** [comment]
Okay, implemented the above. Tested. Is working.
