### ISSUE TITLE
Manif search: related keywords

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#607]
When filtering the manifestations on keyword, manifestations that have that keyword as a related keyword (i.e. the manifestation is linked to an AF with that keyword) should also appear as results.

**Comment by ErwinKomen** [comment]
### Implementation
1. Where is this?
    1. This concerns the `SermonListView`, and then specifically the filter `keyword`
    2. This search currently looks for the `kwlist`, which gets filled as `Keyword.get_scoped_queryset(username, team_group)`

**Comment by ErwinKomen** [comment]
Okay, works
