### ISSUE TITLE
MS Excel upload/download fixes

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#609]
- When uploading a manuscript description from an excel file, the sermon manifestations are not imported, but instead empty manifestations are added to the manuscript.
 - Manuscripts are currently overwritten based on only the shelfmark field. This should be based on the combination of City + Library + Shelfmark
 - The codicological unit information isn't present in the downloaded excel, but it should be. Additionally, because it isn't present in the downloaded excel, there is no way to add it in a new excel manuscript description, but that should be possible.

**Comment by ErwinKomen** [comment]
### More points from myself
- The downloaded `Sermons` tab, Type = `Structural`: wrong column for `Locus`, and column `Status` is empty

**Comment by ErwinKomen** [comment]
### Implementation
1. Downloading a manuscript as Excel
    1. y
1. Uploading an Excel manuscript
    1. x

**Comment by ErwinKomen** [comment]
Okay, fixed it all.
(Modulo the outstanding question)
