### ISSUE TITLE
Shelfmark: City + library + shelfmark combination

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#610]
Everywhere that just the shelfmark of a manuscript is shown or used, should be changed to the combination of city + library + shelfmark (since this information together makes up the "long" shelfmark that identifies a manuscript). 
An exception is naturally the "shelfmark" field on the manuscript identifier details page, as well as the shelfmark shown in the "name" column in the manuscript listview, since the city and library are shown in the columns preceding it.

See also #681

**Comment by ErwinKomen** [comment]
### Implementation
1. The method in class `Manuscript` to get the combination of city + library + shelfmark is: `get_full_name()` (default `plain=True`)
2. Places where the manuscript's shelfmark is shown or used:
3.
