### ISSUE TITLE
Project: editor for one project

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#612]
See issue #473: users still cannot be assigned editor status for a project before they have been granted Passim editor status. It should be possible to be be editor for a project other than Passim without also being able to edit items with the Passim project label.

**Comment by ErwinKomen** [comment]
Okay, see issue #613, where this has been implemented.

### Note
- A user will be able to **edit** (change + save) items (M/S/SSG/HC) to which he/she has editing rights
- A user will **not** be able to 'add' a project to an item (M/S/SSG/HC), unless: 
    - the user has **approver** rights for that project
    - this project has been set as one of the 'default' projects for that user
