### ISSUE TITLE
Project: separate editor status and project approval rights

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#613]
Related to issue #612. It should be possible to be editor for a project other than Passim without also having to be project approver. Currently assigning project approval rights is the only way to assign editing rights to users for projects other than Passim.

**Comment by ErwinKomen** [comment]
### Current situation
That is shown in dct/views.py in `MyPassimEdit`. The context provides the `edit_projects` variable, which shows the projects to which one has editing rights. This is determined by: `qs = profile.projects.all()` ANd `projects` is a many-to-many field from model `Profile` via the table `ProjectEditor`.

**Comment by ErwinKomen** [comment]
### Implementation

1. Check that everywhere `edi` is verified for approving

**Comment by ErwinKomen** [comment]
NO! better solution:
1. Change table `ProjectEditor` into `ProjectApprover`
2. Add new table `ProjectEditor`

**Comment by ErwinKomen** [comment]
Okay, made that change. Now the next step is to find out where the new `project_approver` / `ProjectApprover` is being mis-used to point to a project **editor**...

**Comment by ErwinKomen** [comment]
### Questions
1. Now that we are separating **approval** from **editing** rights: 
    1. should **default** project assignment be taken from the projects one has _approval_ rights for or from the projects one has _editing_ rights for?
