### ISSUE TITLE
Person: VIAF link

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#624]
Each person should be linked to the VIAF record (VIAF.org).
[Shari bespreekt graag met Thijs en/of Erwin of dit de beste resource is en hoe die precies in zijn werk zou gaan, zie ook de vragen in issue #615 ].

**Comment by shariboodts** [comment]
Leave for now - a big review of Authority files for people, places and works will be part of the long-term planning of PASSIM
