### ISSUE TITLE
Person: details page

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#625]
The person details page (see issue #622 ) should have the following information: 

- VIAF-link [or if another type of authority record is decided on, that one] (see issue #624) 
- links to go to the listview of the AFs/manifestations (if type=author) and manuscripts/codicological units (if type=owner/copiist/compiler) connected to that person, in the form ‘origin (manuscripts)’ ; ‘ origin (codicological units)’; ‘provenance (manuscripts)’; ‘provenance (codicological units)’. 
- Linked location(s)

**Comment by shariboodts** [comment]
Leave for now - a big review of Authority files for people, places and works will be part of the long-term planning of PASSIM
