### ISSUE TITLE
Libraries: multiple entries for one library

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#63]
Some libraries occur more than once. 

- **Basel**:  Universitätsbibliothek / Universitätbibliothek

- **Fribourg**: Bibliothèque cantonale et universitaire and **Fribourg/Freiburg**: Bibliothèque cantonale et universitaire/Kantons- und Universitätsbibliothek 

- **Fribourg**:  Couvent  des Cordeliers and **Fribourg/Freiburg**:  Couvent des  Cordeliers/Franziskanerkloster

- **Sion**:  Archives  de l'Etat du Valais and **Sion/Sitten**: Archives de l'Etat du Valais / Staatsarchiv Wallis

- **Sankt Gallen**: Stiftsbibliothek and **St. Gallen** Stiftsbibliothek

- **Sankt Gallen**: Stiftsarchiv and **St. Gallen** Stiftsarchiv (Abtei Pfäfers)  

- **Sankt Gallen**: Kantonsbibliothek Vadiana and **St. Gallen** Kantonsbibliothek, Vadianische Sammlung

**Comment by ErwinKomen** [comment]
The reason for the different items in **Basel** is three different ways of writing the same library.
A 'passim_editor' should handle this.

Implications for the application:
1. The library list view must show
    1. the "CNRS Library ID"
    1. the `id` field of that library
1. When clicking for 'more information' on a particular library id, the details must show:
    1. the number of manuscripts in the database that use this library id
    1. the list of libraries that use this id

**Comment by ErwinKomen** [comment]
I have done:
1. Added the CNRS library ID number in a separate column where known
1. A column with the amount of manuscripts from that library
    1. If that number is above zero, it also contains a link to the Manuscript list view for that particular library (by library id)
