### ISSUE TITLE
Feasts: manif. badge

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#631]
the manifestation count in the feast listview should become a clickable badge that takes the user to the manifestation listview filtered for that feast. (cf. the badges in the keyword listview)

**Comment by ErwinKomen** [comment]
### Implementation

Adapted the function `get_field_value()` of view `FeastListView` to deliver the correct badge that includes the count as well as provides the link to the filtered Sermon List View.

Working
