### ISSUE TITLE
Feast details: table

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#632]
Add the following (sortable) columns to the table on the feast details page: section title; title; Gryson/Clavis/other code (of with manifestation associated AF; if there is no Gryson/Clavis/other code linked to the manifestation, this can remain empty) 

The table should by default be sorted alphabetically on Shelfmark.

**Comment by ErwinKomen** [comment]
### Implementation
1. The table contents needs tweaking anyway, because it is now kind of overloading the cells
    1. Adapted the `Manuscript` column to show the regular manuscript's `get_full_name()`, but added a `plain` boolean argument, so as to show the shelfmarks
    1. Adapted the `or./prov.` column, so that provenance text is just following after the provenance location (if any)
