### ISSUE TITLE
AF details page overhaul overview 

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#635]
We would like to change the way that the information on the Authority file details page is presented, and add some sections. 
All the fields and information will be grouped into various (collapsible) **sections**.

Below the header with the back button and the buttons for the user comments and revision history:
- Page title at the right side
- immediately following the "save item" star
- At the far left: the item status stoplight
- at the far left for editors: button to add a SG, below that the 'edit' pencil and the delete button.

Below this all the **Gryson/Clavis/Other codes** signature badges connected to the AF (i.e. from the SGs in the equality set), coloured as in the listviews.

Then the Passim code and HUWA ID

Then in collapsible sections:
- **Details**
-- Author
-- Incipit
-- Explicit
-- Editions
-- Literature
-- Keywords
-- Project label(s)
- **User contributions** (by default: collapsed, title should remain visible as well as an indication that the section can be unfolded)
-- User keywords
-- Datasets
- **Connections** (by default: collapsed, title should remain visible as well as an indication that the section can be unfolded)
-- Equality set _[precise terminology to be determined]_ ("Contains:")
-- Historical collections
-- AF Links
- **Networks**
-- Overlap Network 
-- Transmission network
- **Graphs** (New section: visual representation of some info based on the connected manuscripts/manifestations, see #636 )
-- Pie charts (two pie charts next to each other: attributed author and origin) (see #637 and #638 )
-- Chronological graph (date of cod. units) (see #639 )
- **Manifestations**
-- #640 
-- #641
-- #642
-- #643 
-- #644

A quick word mock-up of the top:
![image](https://user-images.githubusercontent.com/59916079/204776380-275e1b1c-55f0-4ad2-8a27-48d9e6c3e85c.png)

**Comment by ThijsRU** [comment]
Use separate template based on basic_details. In Lenten zit al collapsible. Binnen huidige systeem: regel toevoegen aan mainitems, label leeg, html geeft voor een knop, uitvouwen.

**Comment by ThijsRU** [comment]
Eerst doe ik #640

**Comment by ThijsRU** [comment]
Eea is zoals bij Stalla/RIPD ondergebracht in secties maar ze kunnen nog niet bewerkt worden, stijl ook nog niet in orde.

Transmission en Overlap bespreken, is het handig dat die samen komen in 1 sectie?

**Comment by ThijsRU** [comment]
Gryson/Clavis/Other codes Added

**Comment by ThijsRU** [comment]
Network: Overlap / Transmission
Graphs: Authors / Origins / Dating

.btn {
    font-size: medium;
}

**Comment by ThijsRU** [comment]
Some items in the AF view have not been discussed, this has been communicated to the PI.

**Comment by ThijsRU** [comment]
Ok, buttons Networks and Graphs seem to work, 

To do:
- get rid of the box (af_networks.html)
- Manuscript button

**Comment by ThijsRU** [comment]
table met Manuscripts: eea wordt nu in basic_details.html afgehandeld, buiten de sections om. Behoorlijk groot stuk code. Beter om het netjes te houden en in af_manifestations.html te houden lijkt mij zo. 

Welke onderdelen moeten daar dan in? Uit basic_details ? En hoe moet het in views.py worden aangepakt?

basic_details.html:

views.py:

**Comment by ThijsRU** [comment]
Komt bij basic_row.html maar vooralsnog worden alleen de reguliere items afgehandeld

**Comment by ThijsRU** [comment]
Done

**Comment by ErwinKomen** [comment]
Okay, this is now working.
What I've done:
1. In `basic_edit.html`: allow optional field `button` in one `mainsection`. If `button` is True, then only show the button, not the mainsection contents
1. In `basic_details.html`: allow optional field `nobutton` in a `section`. If `nobutton` is True, then do not show the button, but only the div's content with the provided name for the div
1. `EqualGoldEdit`, method `add_to_context()`: added the following definition for **mainsections**:
``` python
            context['mainsections'] += [
            
                {'name': 'Networks', 'id': 'equalgold_networks', 'button': True, 'fields': [ 
                    ]},
                {'name': 'Graphs', 'id': 'equalgold_graphs',  'button': True,'fields': [ 
                    ]},
                {'name': 'Manifestations', 'id': 'equalgold_manifestations', 'button': True, 'fields': [ 
                    ]},
                      ] 
```
1. `EqualGoldDetails`, method `add_to_context()`: defined the **sections** this way:
``` python
        context['sections'] = [
            
            {'name': 'Networks', 'id': 'equalgold_networks', 'nobutton': True, 'fields': [ 
                ], 'template': 'seeker/af_networks.html'},
            {'name': 'Graphs', 'id': 'equalgold_graphs',  'nobutton': True,'fields': [ 
                ], 'template': 'seeker/af_graphs.html'},
            {'name': 'Manifestations', 'id': 'equalgold_manifestations', 'nobutton': True, 'fields': [ 
                ], 'template': 'seeker/af_manifestations.html'},
                  ] 
```

**Comment by ThijsRU** [comment]
Ok, this is done, again. Part of this issue will be handled in issue #708.

**Comment by shariboodts** [comment]
Na veel, veel vertraging, een reactie op jouw vraag over positie niet gespecifieerde items:

- Transcription staat intussen in de Details view. Transcription file mag daar meteen onder.
- Bible references staat ook in Details, zie ik: als dat niet teveel moeite is, zou het fijn zijn als die in het lijstje meteen na Keywords zou komen, maar enkel als het niet teveel werk is.
- HUWA-editions mag ook verhuizen naar Details, en daar in het rijtje meteen onder Editions komen.
- Indien niet teveel werk, graag Project naar beneden verplaatsen, naar net boven Add to project in Details view.

Volgorde van Details view wordt dan:

Author
Incipit
Explicit
Editions
HUWA Editions
Literature
Keywords
Bible References
Transcription
Transcription File
Project
Add to project
Remove from project

**Comment by ThijsRU** [comment]
Order, check up on hidden items also ordered?

**Comment by ThijsRU** [comment]
Done
