### ISSUE TITLE
AF details graphs: attributed author

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#637]
A graph added to the AF details page as described in #635  and #636 : this graph is a pie chart with each section representing an attributed author. 
For manifestations where no attributed author is present (no data has been entered into the field), please show these as 'not applicable’

**Comment by ErwinKomen** [comment]
### Implementation
1. Added visualization view `EqualGoldAttr` that provides a dictionary with element `attr_author` containing a list of data points that is very similar to the data points used in JS `private_methods.draw_pie_chart(divid, data);`
2. Provided URL `equalgold_attr` to this graph-collection view in context for `EqualGoldDetails` view
3. Aded entry for this in template `seeker/super_graph.html`
4. Added function in seeker/passim.seeker.js: `piechart_attr(elStart)`
