### ISSUE TITLE
AF details graphs: origin

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#638]
A graph added to the AF details page as described in https://github.com/ErwinKomen/RU-passim/issues/635 and https://github.com/ErwinKomen/RU-passim/issues/636 : this graph is a pie chart of the origins connected to codicological units that the manifestations are found in.
 Each origin (locations) is a section of the chart. The origin should be represented by the country that the origin connected to the cod. unit is part of. There should also be a section for “no origin defined”. 

Example from [Trismegistos](https://www.trismegistos.org/authorwork/78):
![image](https://user-images.githubusercontent.com/59916079/204779695-2093ccb7-e68c-4844-afb6-ca555580092d.png)

**Comment by ErwinKomen** [comment]
### Implementation
1. Add in visualization.py a view `EqualGoldOrigin` 
    1. This provides a dictionary with element `origin_country` containing a list of data points that is very similar to the data points used in JS `private_methods.draw_pie_chart(divid, data);`

1. Provided URL `equalgold_attr` to this graph-collection view in context for `EqualGoldDetails` view
1. Aded entry for this in template `seeker/super_graph.html`
1. Added function in seeker/passim.seeker.js: `piechart_attr(elStart)`
1. Tweaked SVG to work and to have a legend and to be interactive

**Comment by ErwinKomen** [comment]
Okay, working!
