### ISSUE TITLE
AF details graphs: chronological chart

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#639]
A graph added to the AF details page as described in https://github.com/ErwinKomen/RU-passim/issues/635 and https://github.com/ErwinKomen/RU-passim/issues/636: this graph is a chronological chart of timeline of the dates of the codicological units. 
Any suggestions how to best visualise the date ranges would be very welcome!

Example from [Trismegistos](https://www.trismegistos.org/authorwork/78): 
![image](https://user-images.githubusercontent.com/59916079/204778905-964a5fe2-0bee-4895-af07-fdb29fcc26c4.png)

**Comment by ErwinKomen** [comment]
### Strategy
What is asked for is a 'timeline of the dates of the codicological units'.
- The horizontal axis is the 'date'.  
    - But this is not the 'fixed' date, but a time interval, e.g. 25 years (above).
    - Hovering over the line allows one to see the exact **years** of the codico. So if there are 4 codico's between 425-450, 
- The vertical axis is some kind of 'weight'
The 'help' facility for this graph actually says:
![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/620e3e35-77e3-4ffa-888e-35465898a4ed)

**Comment by ErwinKomen** [comment]
### Implementation
1. Create a view `EqualGoldChrono` in seeker/visualizations.py
2.

**Comment by ErwinKomen** [comment]
### Remaining issue(s)
1. Popup visualization problems
    1. Sometimes the popup window is too low
    2. Sometimes the text for the popup window is in a different place than the popup window itself
