### ISSUE TITLE
AF manifestations: table columns show/hide

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#641]
Add an option to hide columns in the manifestation table on the AF details page, e.g. comparable to the listviews, with a button that shows a list of the available columns when clicked, after which you can select and deselect the desired columns.

**Comment by ErwinKomen** [comment]
### Implementation

1. Adapt template `basic_details.html`
    1. Add a 'column wrapping' div with `id="tab_colwrap"` that is normally hidden
1. Extend the `related` list with the following items for column wrapping:
    1. list `colWrap`
    2. list `order_heads`: those are the names of the columns that _can_ be shown/hidden

**Comment by ErwinKomen** [comment]
Okay, working.
