### ISSUE TITLE
AF manifestations: table sorting

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#642]
It should be possible to sort the manifestations table on the AF details page. The default should be alphabetical on shelfmark, with as additional options: 
- On date: chronologically (so 900 should come before 1000), one click: oldest first, possibility to sort it the other way around 
- On origin/provenance: alphabetical (when the origin/provenance/locations have been completely sorted out: alphabetical on country) 
- Attributed author: alphabetical

**Comment by ThijsRU** [comment]
Used ProvDetails, works!
