### ISSUE TITLE
AF manifestations: table appearance

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#643]
The manifestations table on the AF details page should have columns with a fixed width (which can be different for the different columns), e.g. something similar to this:

![image](https://user-images.githubusercontent.com/59916079/204798127-c3b4f267-ff4a-4092-b4c2-662fb636247d.png)

This is so that the user does not have to move all the columns to the left to be able to see the information in the columns on the right, and the shelfmark does not have to use quite so much space.

**Comment by ThijsRU** [comment]
Percentages gebruiken, volgens mij kan dit gewoon in de template, deze table wordt alleen bij AF gebruikt volgens mij.

**Comment by ThijsRU** [comment]
Hoe elke specifieke kolom een aparte width geven?

Eerst in css voor elke mogelijke optie een width aangeven:

Welke file?

- Shelfmark
- or./prov.
- date
- coll.
- item
- ff.
- attr. auth.
- inc.
- expl.
- keyw.

**Comment by ThijsRU** [comment]
Done

**Comment by ThijsRU** [comment]
Needs modifications after #640
