### ISSUE TITLE
AF search filter: manuscript

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#655]
Add a search filter to the AF search filters to filter the AFs on the contents of a specific manuscript (linked AFs).

(currently the only way to do this is to create a dataset with one manuscript and filter the AF listview on this dataset)

**Comment by shariboodts** [comment]
Leave for now

**Comment by ErwinKomen** [comment]
This has become part of: issue #719
Let me have a look...

**Comment by ErwinKomen** [comment]
Okay, works.
