### ISSUE TITLE
MS search filter: combine manual and automatic Gryson/Clavis/Other codes

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#658]
The Authority file section of the Manuscript Listview contains both Gryson/Clavis/Other codes filters, automatic and manual. These filters need to be combined to include both automatic _and_ manual Gryson/Clavis/Other codes.)

The results should show the manuscripts that contain sermons with a link to one or more signatures and/or manuscripts that contain sermons that are linked to an EqualGold that is linked to a GoldSermon that is linked to one ore more signatures.

Manuscript <--> SermonDescr <--> SermonSignature <--> Signatures (Manual) 

Manuscript <--> SermonDescrEqual <--> EqualGold <--> GoldSermon <--> Signatures (Automatic)

Not possible with Select2

automatisch vanuit SSG, manual is vanuit user kunnen?

Q expressie toevoegen aanpassen of toevoegen 

Voorbeelden?

**Comment by ErwinKomen** [comment]
This is now overruled by issue #718, which EK is implementing
