### ISSUE TITLE
Security: restrict downloading

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#671]
It should not be possible to download the entire contents of the database just like that.

The PI writes:
> Voor nu is het beperken van de downloadrechten van gewone users en niet-PASSIM-editors voldoende. 
> Voor dat laatste kunnen we download-rechten bv. beperken tot de items die het projectlabel van de editor dragen

### Actions
1. Restrict the download possibilities of a `passim_user` to: **only visualizations** (not datasets or other stuff)
2. Restrict the download possibilities of a `passim_editor` to those items that bear the project label of that editor

**Comment by shariboodts** [comment]
1. For now, let's only allow the download of visualisations, not datasets. I would like to open this up more in future, but first we need to sort out the details with Brepols.

**Comment by shariboodts** [comment]
See issue #716

**Comment by shariboodts** [comment]
REPLACED BY #716
