### ISSUE TITLE
AF Manifestations: Small formatting issues

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#675]
**1)**	<i> tags in titels van manifestations blijven zichtbaar als je bij een manuscript in het overzicht van manifestations kijkt, maar de tags verdwijnen (en passen de schuingedrukte tekst correct toe) zodra je op de manifestation in kwestie klikt.  Voorbeeld:   Dit is wat je ziet in het overzicht van manifestations: 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225027529-752778a7-1847-4230-b146-276f139cee15.png">

En dit is wat je vervolgens ziet op de pagina van de manifestation in kwestie:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225027589-6b06ea02-426a-4d3c-8e44-66100764eced.png">

  (NB: volgens mij geldt dit probleem voor alle HTML-formatting die in deze velden kan worden gebruikt)

**2)**	Bij het bewerken van manifestations die al ingevoerd zijn: als iemand per ongeluk hoofdletters heeft gebruikt, dan zie je die inderdaad staan in het overzicht van manifestations. Klik je echter op de manifestation, dan staat daar alles keurig in kleine letters–totdat je daadwerkelijk gaat editen, want dan zie je de hoofdletters weer. Dat kan verwarrend zijn.  Voorbeeld:  Dit is wat je kunt zien in het overzicht van manifestations:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225027750-04f7461c-094b-463e-99d7-613e5928561a.png">

En dit is wat je vervolgens ziet als je op de manifestation klikt…
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225027793-fc965038-5d95-46bf-b7a0-555e5994c8f5.png">

…maar als je dan op de edit-knop klikt, krijg je weer hoofdletters te zien:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225027856-81e58cc2-8018-49d1-be6e-e0a6f9d9212b.png">

3)	Weer over <i> tags en manifestations. Het toepassen van een <i> tag kan ervoor zorgen dat hoofdletters schijnbaar verwijderd worden waar ze juist wél horen. Voorbeeld:  Dit is wat je ziet op de manifestation-pagina vóórdat je op edit klikt:   
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225028198-971df686-1365-47fb-9da5-10daaad4981f.png">

En dit is wat je vervolgens ziet als je gaat editen:   
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57531972/225028256-1059e8d2-44e5-4263-8ec9-635428a6dd26.png">

(Ook verwarrend is overigens dat alles nu schuingedrukt lijkt in het edit-veld terwijl alleen het Romeinse cijfer schuingedrukt zou moeten zijn hier)

**Comment by ErwinKomen** [comment]
### Notes
1. The first problem is that some items in `SermonDescr` have a field `title` that contains `<i>`, but no closing `</i>`
    1. Resolution: remove `<i>`, `</i>` everywhere in title field
    2. Do the same for field `postscriptum`
1. The second problem is about the use of capital and small letters. Basically, this is by design
    1. Internally, the field `incipit` and `explicit` contain the literal incipit and explicit, the one that may contain capital and small letters
    2. But the fields `srchincipit` and `srchexplicit` (which serve to search) contain small letters only
1. Third issue: see under (1). Resolved.
