### ISSUE TITLE
Design and lay-out: Footer

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#676]
In de footer (op iedere pagina): de link in “Developed at:[ Radboud University Nijmegen](http://cls.ru.nl/)” is dood. (Zal wel te maken hebben met de nieuwe website van de uni; de juiste link naar CLS is nu https://www.ru.nl/cls/.) Aanvullende vraag: moet dit eigenlijk niet linken naar RICH?

**Comment by ErwinKomen** [comment]
Changed into https://www.ru.nl, since it says "Radboud University Nijmegen"
