### ISSUE TITLE
Montecassino

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#680]
- City and library Montecassino: A manuscript such as this one (https://passim.rich.ru.nl/manuscript/details/7775/) cannot be linked to Montecassino (this name appears in the drop-down list, but changes into 'Cassino (city)' when saved). The connected library is also not correct. There should only be one option in the 'cities' and 'libraries' list to add a manuscript from Montecassino (there are several now). The only correct one should be only Montecassino, not Cassino, Cassino (city), Monte Cassino > these should be deleted from the 'city' list, and the manuscripts linked to them transferred to the correct ‘Montecassino’

- City and library Montecassino: In the list 'libraries' we would need only one library associated with Montecassino: **Biblioteca del Monumento nazionale di Montecassino** (not `Biblioteca della Badia`, `Archivio e Biblioteca dell’Abbazia`, `Biblioteca Statale del Monumento nazionale di Montecassino. Archivio`). If any of these three library names are still present, they can be removed, and the manuscripts linked to them transferred to the correct ‘Biblioteca del Monumento nazionale di Montecassino’. 

- City and library Montecassino: 
    - In Manuscripts > filter > City/Location and filter > Library, users should be able to find and select Montecassino and Biblioteca del Monumento nazionale di Montecassino in the drop-down menu (and none of the other variants for that city/library). 
    - The same goes for the search options in manifestations > filters > manuscript > city/location and > library.

**Comment by ErwinKomen** [comment]
1. The problem with Montecassino is that it is a `monastery`. That `monastery` is part of the city called `Cassino`.
    1. I adapted the name of library id `2662` to read `Biblioteca Statale del Monumento nazionale di Montecassino.`
        1. This does contain the word `Statale`, contrary to what is written above - P.I. can remove that, if needed
    1. There are two other libraries with Montecassino: 2663 and 4933
        1.

**Comment by ErwinKomen** [comment]
Okay, one more extension: the `LibraryOneWidget`  that is used in the Manuscript details page needs to re-define the chosen `lcity` as a choice (logical or) between the `lcity` and `location` fields of libraries.

That can be done in an extension of the method `filter_queryset()`
Okay, I've made and checked that extension now (15/may), and it works good!
