### ISSUE TITLE
Search and filter: Manifestations

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#681]
Filtering manifestations on 'manuscripts' should allow us to search and select manuscripts based on city, library, shelfmark instead of just shelfmark. (for comparison: the search-function to add manuscripts to a DCT is much better; this filter function should work similarly).

**Comment by ThijsRU** [comment]
Not clear what needs to be changed.

**Comment by shariboodts** [comment]
I believe the problem here is that when you type a shelfmark into the shelfmark search field, the dropdown menu lists as matches only the shelfmark without showing the accompanying city and library. This is inefficient, since e.g.,120, as a shelfmark can be used by many different libraries. It would be handier if in the dropdown menu of matches, the full ID for each match is given (City, Library, Shelfmark), so it is immediately apparent to the user which one is the correct match. It is a faster way to search than going through City search, Library search and then shelfmark.

**Comment by ErwinKomen** [comment]
### Implementation
This is  `SermonListView`: filter manuscript > `Shelfmark` - see issue #681 
Action: changed `SermonForm`, field `manuidlist` from widget `ManuidWidget` into using widget `ManuscriptWidget`
