### ISSUE TITLE
Clicking on star to save/unsave item in list view very difficult

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#695]
Trying to save/unsave an item by clicking on the star in the list view is difficult. Often when clicking on it, nothing happens. It does not seem to be related to the careful positioning of the cursor. When it will and will not work seems very random.

**Comment by Irisdenis** [comment]
edit: When testing this, I've found the 'saving' of an item works reasonably well (though the star sometimes needs a moment to 'register' before it turns blue). However, I am having trouble 'unsaving' the blue stars by clicking on them again, even though I'm clicking very specifically (e.g. after zooming in, or after seeing the pop-up text 'remove from your saved items').

**Comment by ErwinKomen** [comment]
Was this related to #678? I tried adding CSS:
```
.sitem-button {
    ...,
    width: 100%;
    display: block;
}
```
But that didn't solve it.
Then I looked at the JS in `ru.dct.js` function `do_saveditem()`. There was an oversight: the correct form-relative `sitemaction` form element is in `$(frm).find("#id_sitemaction")`

Now it works correctly

**Comment by Irisdenis** [comment]
Unfortunately, I now (06-06-2024, 16:00) get a 'Server error (500)' whenever trying to save an item (any item). 
Only after clicking back to the previous page _and_ after reloading the page, is the element in question saved. 
The same server error appears when trying to 'unsave' the item.

**Comment by ErwinKomen** [comment]
I checked, saw in the server log that there was `/saveditem` activity, but there are no errors in the logs.
Are you sure you did Ctrl + F5, to refresh the browser's cache?

I cannot reproduce the error. Do others have it??
