### ISSUE TITLE
PD: editing dataset bug

### ISSUE THREAD

**Issue by Irisdenis** [ErwinKomen/RU-passim#696]
In Personal Datasets, the option to edit/delete a dataset has disappeared (see e.g. https://passim.rich.ru.nl/dataset/private/details/734/). There used to be (and should be) an option to edit the details for each PD, and delete it when necessary.

**Comment by ErwinKomen** [comment]
Well, the option to edit is still there. But somehow only for those with particular parmission.
Going to look into that...
