### ISSUE TITLE
AF details page overhaul (style)

### ISSUE THREAD

**Issue by ThijsRU** [ErwinKomen/RU-passim#708]
This issue contains the leftovers from issue #635 and concerns the style of the presentation of the AF details. Most parts are already placed in sections. 

The PI has been asked earlier to take a look at the details that were not named below and not to be placed in the sections. It may well be possible that they should be placed in the sections. 

Maybe a separate template needs to be constructed for (parts?) of the AF details page. This is why this issues needs to be solved in the last phase of the project.

### This needs to be done:

We would like to change the way that the information on the Authority file details page is presented.

Below the header with the back button and the buttons for the user comments and revision history:

- Page title at the right side
- Immediately following the "save item" star
- At the far left: the item status stoplight
- At the far left for editors: button to add a SG, below that the 'edit' pencil and the delete button

Below this all the Gryson/Clavis/Other codes signature badges connected to the AF (i.e. from the SGs in the equality set), coloured as in the listviews.

Then the Passim code and HUWA ID.

A quick word mock-up of the top:
![image](https://github.com/ErwinKomen/RU-passim/assets/46558447/68d5f9c5-b15a-474a-af6b-e60cbab24753)

**Comment by ErwinKomen** [comment]
### Verification of end result
The instructions above have 'right', where the mock-up shows 'left' (e.g. stoplight shown at right, requested for far left).
So, should the end result look like this:
![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/a7784b69-cba6-4828-97a2-a52950f32b35)

Or should it look like this:

**Comment by shariboodts** [comment]
I prefer the second mock-up, with the traffic light on the left.

**Comment by ErwinKomen** [comment]
### Implementation
1. Add the possibility to provide a different `<h3>` title section
    1. Add switch on `title_template` in `basic_details.html`
    2. Add `seeker/af_title.html` with the alternative heading
    3. Add code to handle `title_template` in views.py `BasicDetails`
1. Add a way to position the delete button not to the right
    1. Add in `basic_details.html` a check for boolean `del_left`
    2. Added specification for `del_left` in view `EqualGoldEdit`
1. Hide the regular status, unless editing is done
    1. Added `'editonly': True` in the specification of the status in `EqualGoldEdit`
