### ISSUE TITLE
HUWA - Doubles

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#712]
Rafael heeft gekeken naar de manuscripten die meermaals in PASSIM zitten als gevolg van HUWA-import . Daaruit blijkt dat een manuscript vaak tweemaal geïmporteerd zijn als deel van HUWA-import (beiden dus met HUWA-project label), 
1. wat is de reden? 
1. Zaten ze al tweemaal in HUWA-database of zijn ze tweemaal geïmporteerd? 
1. Hoe vaak komt dit voor en kan dit automatisch verbeterd worden. 
    1. Bv. als beide manuscripten het HUWA-label hebben, en een van hen is 'leeg', dus zonder manifestaties, kan dit dan automatisch verwijderd worden?

Voorbeelden: 

Parma, Biblioteca Palatina, Palat. 227
[https://passim.rich.ru.nl/manuscript/details/9783/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F9783%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474222940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zSwr8Fx46RtqJ584FelRij2o%2FbGBXY7Y26x37Yu6vvE%3D&reserved=0)
[https://passim.rich.ru.nl/manuscript/details/9784/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F9784%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474222940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=17hNWJf4WcGFkWcP%2FTfWexlUgRw67VrkjXL8Rh0IXE8%3D&reserved=0)

Cambridge, Gonville and Caius College Library, Cod. 240
[https://passim.rich.ru.nl/manuscript/details/11715/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F11715%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474222940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rqSoXL64TCwfKZse7kNK1KNCgCHHeT92HukU40qZ4UA%3D&reserved=0)
[https://passim.rich.ru.nl/manuscript/details/11719/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F11719%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474379245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V7iajG1e2JDcpXVwKKx79Cc7w9XsHXGSFyva9aQPABE%3D&reserved=0)
[https://passim.rich.ru.nl/manuscript/details/11716/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F11716%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474379245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FG5A4ypy6lvMJYMSy8faP%2BLtqSLxBqUj%2Fkj5D3%2Ff7Qc%3D&reserved=0)
[https://passim.rich.ru.nl/manuscript/details/11717/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F11717%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474379245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4l%2FbmhNFfbg0A2WEanNiD5Ga8gpNIVNGSovyLGC1pAs%3D&reserved=0)
[https://passim.rich.ru.nl/manuscript/details/11718/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fmanuscript%2Fdetails%2F11718%2F&data=05%7C02%7Cshari.boodts%40ru.nl%7Cb0c54cdded974a3fc19308dc175db796%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638410938474379245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vY8Q1bpDuxJm0yvJpVgSyZGEM1S1qGPLWizkzH54%2Bdk%3D&reserved=0)

**Comment by ErwinKomen** [comment]
The import of HUWA manuscripts into PASSIM did not check for 'doubles' (not by comparing if a manuscript with a particular city/library/idno had already been imported). The examples above refer to **different** HUWA manuscripts:

Shelfmark | Passim manuscript | HUWA identifier
-- | -- | --
Parma, Biblioteca Palatina, Palat. 227 | 9783 | 2070
Parma, Biblioteca Palatina, Palat. 227 | 9784 | 2071

**Comment by ErwinKomen** [comment]
### Manuscript Codices
It should be possible to combine different codices of one manuscript. Not sure if/why this has not happened, but this can be done.
1. Add code to explore this in adaptations > `adapt_huwadoubles()`

**Comment by shariboodts** [comment]
Hi Erwin,

This looks to be an elegant solution to me - at least the unnecessary doubles are removed and manual checking can be done to merge information within codicological units or eliminate them as needed. I have one correction and one question:

- Correction: right now, if I see correctly, only 1 HUWA ID is listed in the newly merged PASSIM records. It would be better if all HUWA IDs were listed (so, e.g. https://passim.rich.ru.nl/manuscript/details/9783/ has both HUWA ID 2070 and 2071).
- Question: You mentioned Number of multiple-manuscripts: 350 and number of manuscripts now dealt with 308. The 42 remaining manuscripts: What is going on with them? If you can generate a list, we can check and process them manually if needed.

As regards your two to do-questions:
1. Yes, can be combined with 9125
2. These seem to be errors, I will ask Clemens to manually check them in the HUWA database.

Thanks!

**Comment by ErwinKomen** [comment]
I double checked, but could not find any more instances of HUWA-imported manuscripts in Passim with the same library and shelfmark.
