### ISSUE TITLE
Manuscripten met foutieve link stad-bibliotheek

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#714]
Naar aanleiding van mail:

Dag Shari,
 
Ik heb er nog eens fris op maandagochtend naar gekeken.
Ik weet nu precies hoe het gekomen is, welke manuscripten het betreft, en ik heb die 37 manuscripten in een Team Dataset verzameld, zodat ze handmatig gecontroleerd en verbeterd kunnen worden.
Zie: [https://passim.rich.ru.nl/dataset/private/details/1000/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpassim.rich.ru.nl%2Fdataset%2Fprivate%2Fdetails%2F1000%2F&data=05%7C01%7Cshari.boodts%40ru.nl%7Cbc2ea172a7d34c839e3608dbb81f6ccf%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638306217346806218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RETbsQmAb51%2FRUp27Cx%2FHppbkFEsl1gpukSOhoJ7qUE%3D&reserved=0)
 
Goed, nu even wat er precies mis is gegaan.
De software om bij het importeren van een manuscript (bijvoorbeeld vanuit SERMONES) de juiste bibliotheek te zoeken was op zich wel ‘goed’ geschreven, maar er zat één fout in.
Vóórdat heel serieus gekeken werd of de bibliotheek wel automatisch bepaald mocht worden, werd er al een bibliotheek ‘voorbepaald’, en dat gebeurde met het principe van ‘first match’ (de eerste bibliotheek met die naam werd genomen).
Dus “Trinity College” – daarvan werd meteen de verkeerde variant gekozen (we hebben drie varianten van Trinity College, die geen van drieën de juiste uit Dublin zijn, omdat die in Dublin volgens onze db “Trinity College Library” heet).
 
Ik heb de software nu verbeterd: de bibliotheek mag gewoon nooit automatisch ‘voorbepaald’ worden. Alleen wanneer het land, de plaats en de bibliotheeknaam alle drie kloppen, mag de bibliotheek automatisch voor een manuscript worden ingevoerd. Die verbetering staat vandaag online. Maar is alleen van toepassing op het inlezen van nieuwe manuscripten.
 
Ik heb vervolgens gekeken bij welke manuscripten het ‘fout’ is gegaan, en dat zijn er 37.
Die heb ik nu in een Collection gestopt (zie link hierboven).
Wat daar gedaan moet worden, dat weet ik niet precies.
Het kan verschillende kanten op gaan:
1 – de gegevens van de Library zijn niet juist – dan moeten city/country van de library verbeterd worden
2 – de gekozen library is niet de juiste (bijv. “Trinity College” in plaats van “Trinity College Library”)
3 –  de city/country die bij het Manuscript zijn opgeslagen kloppen niet – dan moeten die handmatig worden gewijzigd
 
Hopelijk kun je hier verder mee.
 
Hartelijke groet,
 
Erwin

**Comment by ErwinKomen** [comment]
### P.I.

Rafael heeft deze manuscripten bekeken, maar het corrigeren bleek heel moeilijk te zijn:

Manuscripten waarvan de verkeerde stad verschijnt omdat de link met de bibliotheek foutief is, correctie is heel omslachtig, want verbeteren lukt niet: als je de juiste stad invoert, is er geen bibliotheek zichtbaar in het drop down menu. Creatieve oplossing is een heel nieuw manuscript creëren, voor dat manuscript eerst (proefondervindelijk) de juiste bibliotheek selecteert, dan de stad, dan het land. Waarom deze fout: dat de juiste bibliotheek niet gelinkt is aan de juiste stad, of alleszins niet in het drop down menu verschijnt? Kan dit hersteld worden?

(Rafael kan meer toelichting geven indien nodig)

Zie issue #700

**Comment by ErwinKomen** [comment]
Okay, double checking from the 37-item collection which manuscripts are still 'wrong'...
1. Germany, Aachen, Bischöfliche Diözesanarchiv - those are all okay
1. Ireland, Dublin, Trinity College Library - those are all okay
1. United Kingdom, Cambridge, Trinity College - those are okay
1. Germany, Jena, Thüringer Universitäts- und Landesbibliothek - okay
1.

**Comment by ErwinKomen** [comment]
### While checking
One or two things were found to have gone wrong while checking.
1. The improvement to issue #680 has already been mentioned above.
1. Then there is the disappearance of the "Manuscript filter"
1. The "Collection filters" having been renamed to 'Comparative search', but that label doesn't come across correctly yet

**Comment by shariboodts** [comment]
All checked! I corrected the libraries for Montecassino: it is a single library in the monastery, but they have changed the official name recently, so Biblioteca dell'Abbazia has become Biblioteca Statale... Thus, Biblioteca dell'Abbazia can be removed from the list for Montecassino.
