### ISSUE TITLE
Wrap-up - Check visibility full-text

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#715]
- Full-text of the sermon, under 'transcription' needs to be made invisible for regular users (only these, it can be visible for editors, moderators). The word-count can stay visible to users, it should just not be clickable for them.
- Tools > Online sources is currently only visible to editors, it should be visible to users as well.

**Comment by ErwinKomen** [comment]
### Implementation
1. Transcription visibility
    1. Since word count may remain visible, we just need to adapt `SermonEdit` method `get_transcription()`
