### ISSUE TITLE
Wrap-up - Download options

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#716]
I've checked through my 'regular user'-account, and it seems there are no download options for datasets now. 

Download options to be made available:

- Regular users should be able to download/export small datasets of any type, of max. 1000 items. If the dataset is larger, there should be a message: "Regular users can only download datasets of max. 1000 items. If you would like access to a larger dataset within PASSIM, please contact the moderator" (with link to my email).
- Editors should be able to download/export any dataset, no matter the size, if all items have their own project label (additional project labels on the items are no problem here). For datasets that have items that do not belong to their project, the same 1000-item limit applies

**Comment by ErwinKomen** [comment]
### Implementation
1. Use the functions `download_excel()` and `get_data()` 
    1. Copy them from Bitsebol `BasicList` to Passim `BasicPart` - _ok_
    2. Adapt them - _works_
1. Add the parameter `spec_download` (boolean) to indicate that a download should make use of this facility
1. Check the presence of `specification` in the four relevant collection types:
    1. `M`: yes, is there, and download works
    2. `S`: 
    3. `SG`: 
    4. `SSG`:

**Comment by ErwinKomen** [comment]
Need to make sure that a warning (see above) gets to the user, when downloading is not allowed.

### Implementation
1. Added a test in `download_excel()` to see if there is anything inside `self.arErr`
    1. If there is, then a token `$error$` is added to the Content-Disposition
    2. This is a trigger for the JS `basic.post_download()` to do
        1. Read the contents as a text containing an error message
        2. Show that error message in the `basic_err` location
1. Added information to the error message that indicates which forbidden projects are among the downloaded objects
1. Double checked: 'good' data can still be downloaded (provided the user has the rights)
