### ISSUE TITLE
Wrap up - Functionalities: Search functionalities manuscripts

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#718]
1.	In Manuscripts > Manifestation..., the option to search for Gryson/Clavis/Other code does not work properly. Remove the option to search for ‘Gryson/Clavis/Other code (manual)’ and ‘Gryson/Clavis/Other code (automatic)’ from Manifestation filters.
1.	Instead, add option to search for ‘Gryson/Clavis/Other code’ in Manuscripts > Authority File. There should not be separate fields for automatic and manual Gryson/Clavis/Other codes, just one filter (see issue [#658](https://github.com/ErwinKomen/RU-passim/issues/658), which is not completely accurate anymore).
1.	It should be possible to search for manuscripts linked to AF’s in complex ways, using Boolean operators, e.g. “Give me all manuscripts that contain AF 1 and AF 2 and AF 3” (etc.), or “Give me all manuscripts that contain AF 1 and AF 2 and AF3, but not AF 4”. Now, the selection of multiple AF’s automatically filter all manuscripts linked to AF 1 or AF 2. 
    1.	How to do this (users have two options):
Introduce one AF in search field, click ‘Select new Authority File’, a new search field appears below, with a Boolean operator field between the two search fields. Add more search fields as needed. 
Or: Add immediately multiple AF’s to a single search field (already possible), but (this is new), you can adjust Boolean setting for this groups of AF’s: AND/OR/NOT
    1. So, for the two questions above: 
“Give me all manuscripts that contain AF 1 and AF 2 and AF 3” can be done using field: select multiple AF’s
“Give me all manuscripts that contain AF 1 and AF 2 and AF3 not AF 4” needs to be done by introducing each of the AF’s individually and selecting the correct Boolean operator.

**Comment by ErwinKomen** [comment]
Context: this is the `ManuscriptListView`
See also issue #658

### Actions
1. Out-comment the Sermon > signature lines (two)
1. Add a new line for Gryson/Clavis/Other using filter `filter_authority_file_signature`
1. Define filter search  `authority_file_signature`
1. Add a section in `adapt_search()` to handle the `siglist` field
    1. Calculate the `SermonSignature` qs to represent the same information as the `Signature` qs with which we come
    1. Create a logical-or Q-expression that combines the `Signature` and the `SermonSignature` selections
