### ISSUE TITLE
Search functionalities: smaller changes and bugs

### ISSUE THREAD

**Issue by Irisdenis** [ErwinKomen/RU-passim#719]
**Manifestations list view**
•	Search filter ‘section’ should be ‘section titles’
•	Bible reference > 'John' and '*' gives no results, so there seems to be a bug here. Or do wildcards not work for the 'chapter' field?
•	Manifestations > Manuscript... > Manuscript Type > offers the choice between 'Reconstruction' and 'Manifestation'. 'Manifestation' should be renamed to 'Regular'
•	Rename 'Sermon filters' (left column) to 'Manifestation filters'

**Authority Files listview**
•	column ‘links’ > rename to 'Linked AF’s'
•	Implement issue [#655](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FErwinKomen%2FRU-passim%2Fissues%2F655&data=05%7C02%7Ciris.denis%40ru.nl%7C3b4649eacadb423ab99e08dc20be0eb7%7C084578d9400d4a5aa7c7e76ca47af400%7C1%7C0%7C638421247879643731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=bz%2BqpUf0NhdYBtSgL4tM1bE7BIUxDCFMIXDstZcyhVU%3D&reserved=0).
- Implement #702

**Manuscripts listview**
•	Rename 'Sermon filters' (left column) to 'Manifestation filters'

**Comment by ErwinKomen** [comment]
## Implementation

### Manifestations list view
1. Search filter ‘section’ should be ‘section titles’
1. Bible reference > 'John' and '*' gives no results, so there seems to be a bug here. Or do wildcards not work for the 'chapter' field?
1. Manifestations > Manuscript... > Manuscript Type > offers the choice between 'Reconstruction' and 'Manifestation'. 'Manifestation' should be renamed to 'Regular'
1. Rename 'Sermon filters' (left column) to 'Manifestation filters'

**Comment by ErwinKomen** [comment]
## Implementation

### Authority Files listview

This is: `EqualGoldListView`
1. column ‘links’ > rename to 'Linked AF’s'
1. Implement issue #655

**Comment by ErwinKomen** [comment]
Okay, works
