### ISSUE TITLE
Personal Dataset: small adjustments and a bug

### ISSUE THREAD

**Issue by Irisdenis** [ErwinKomen/RU-passim#720]
**Part 1: Terminology changes for Dataset details**
Example: https://passim.rich.ru.nl/dataset/private/details/1020/

- Listviews > ‘Sermons’ should be called ‘Manifestations…’ (orange button).
- Listviews> ‘Gold…’ should be deleted (grey button)
- Adjust default 'description' and 'type' for each kind of PD: 
    - **PD: AF :** 'Created from a Authority file listview basket' > 'Created from an Authority file listview basket'
    - **PD: Manifestation :** (1) 'Created from a sermo listview basket' > Created from a Manifestation listview basket ; (2) Type = 'sermon' should be 'manifestation'.
    - **PD: Manuscript :** 'Created from a manu listview basket' > Created from a Manuscript listview basket 
- Make sure that, in Datasets listview > column 'type', every 'sermon' is now replaced by 'manifestation'

- Information button (with a + sign):

    - change 'add authority files info' to 'How to add Authority files?'
    - implement the same change for PD's of manuscripts and manifestations ('How to add Manuscripts?' and 'How to add Manifestations?')
    - the green button that is a shortcut to the listview still reads 'Super Sermon Gold', and there is a space missing: adjust to 'Go to Authority files listview'
    - implement the same change for PD's of manuscripts and manifestations ('Go to Manuscripts listview' and 'Go to Manifestation listview')
    - in the explanation under 'Add Sermons info', change all 'Sermons' into 'Manifestations' (example: https://passim.rich.ru.nl/dataset/private/details/918) 

**Part 2: Small bug for private datasets**

In the Datasets listview, I clicked on the number in the column Frequency for a **Private, AF** personal dataset: this gives an error. It should display all AF's in the listview filtered through this dataset. This functionality works properly for  manuscript- and manifestation datasets.

![print](https://github.com/ErwinKomen/RU-passim/assets/57664160/eda65829-93ec-4d34-a08a-69745b252d37)

**Comment by ErwinKomen** [comment]
### Implementation
#### Part 1. Terminology changes for Dataset details
1. Listviews > renamed ‘Sermons’ into ‘Manifestations…’ (orange button).
1. Listviews> removed ‘Gold…’ (grey button)
1. Adjust default 'description' and 'type' for each kind of PD:
    1. PD: AF - done
    2. PD: Manufestation - done
    3. PD: Manuscript - done
1. Make sure that, in Datasets listview > column 'type', every 'sermon' is now replaced by 'manifestation'

**Comment by ErwinKomen** [comment]
#### Part 2. A bug
I corrected the bug, which was in method `get_field_value()` of `CollectionListView`
