### ISSUE TITLE
Functionalities: Project label system

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#722]
At the moment, I don't seem to have the ability to create a new project label within PASSIM. I think it would be useful to have the following in place:

- Create a page with a list view of all project labels, visible to all users, but editable only for PASSIM moderator. In the list view is visible also the number of manuscripts, AF's and manifestations associated with this project label.
- Each project label in the list view is clickable (by all users). Clicking on it opens a page with a short description of the content of project and the contact information of at least one editor of the project (name and email address).
- PASSIM Moderator has the option to create a new project label and modify the name of a project label (I assume it is problematic to include the option to remove a project label altogether, so let's leave that out for now).
- Eventually (but not now), it would be good if on this page project editors could also modify download options for their particular projects/datasets.

In addition to this system, is it possible for you to bulk assign all manuscripts that currently have the keyword 'irrelevant manuscript' (479 manuscripts) to a newly to be created project label: 'PASSIM_Overflow'?

**Comment by ErwinKomen** [comment]
### Implementation

1. Shari, you are one of the moderators. I added the possibility for moderators to add (and view) projects. That goes via Tools > Projects. I tested this, and I was able to create the `Passim overflow` project that way.
1. I have **added** the 479 manuscripts (with label "irrelevant manuscript" ) to the new project "PASSIM_Overflow"
    1. **NOTE**: these manuscripts now have **two** project labels
