### ISSUE TITLE
PASTA and Bible references

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#724]
Gleb has tagged biblical references in part of PASTA. We would like to:

- Export all these references to the field 'Bible reference' on the AF Detail page
- Add a search field 'Bible reference' to the AF search filters (similar in style to the search filter for manifestations) (see issue #702)

(Note: This would create a difference in results if searching for a bible reference from the Manifestations page versus the AF page, correct? Is it easy to have bible references associated with an AF also be associated with all manifestations linked to that AF? If the difference is indeed there, it should be signalled in the user manual)

Gleb will follow up on this issue with Erwin.

**Comment by glsch** [comment]
As far as I can see, the Bible references that I've provided are fully integrated, and the search is working correctly. What I cannot check is whether the quotations from any new .XML files with new texts will be added automatically. If so, there is nothing to add, I suppose. At least, for the moment.
