### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#725]
I would like to keep some statistics on users. Therefore, when registering, the following fields should be made obligatory:

- First name
- Last name
- Affiliation (there should be an option 'not applicable')

For already registered users, there should be a pop-up when they next login, asking them to complete their profile.

**Comment by ErwinKomen** [comment]
### Implementation
1. Sign up:
    1. Added field `affiliation` to the `SignUpForm`
    1. Processing of `affiliation` in view `signup(request)`
    1. Make sure `Profile` is created right in `signup()`
