### ISSUE TITLE
PASTA-topics to keywords

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#728]
For 643 Augustinian sermons, Gleb has done a topic modeling analysis, which yielded ca. 50 topics, present to greater or smaller degree in each of these texts. We want to connect these topics as keywords to the AF's. Actions:

- Create category for keywords: 'Topic'
- Import 53 topics as keywords, under category 'Topic'
- Create contextual help button for 'category search filter' where a pop-up can explain in a few words what the categories mean
- Decide which topics should be attached to which sermons (what is the best cut-off - five/ten topics most present in each sermon, other? - Gleb and Shari will work this out)
- Connect topics to AF's

**Comment by glsch** [comment]
W. r. t. the topic model, the question is whether we have an "official" annotation of topics. I have one of my own (in the files I shared with Shari), but, if I remember correctly, we wanted to produce two of them independently and juxtapose. In any case, it's a question of attaching to each AF a ranked list of 5 most present LDA-topics. Below, a CSV file, where each AU sermon is associated with a distribution over a set of 53 topics. Top 3 or Top 5 can be used as sort of keywords.

**Comment by ErwinKomen** [comment]
### Implementation

1. Create category for keywords: 'Topic'
    1. 
1. Import 53 topics as keywords, under category 'Topic'
1. Create contextual help button for 'category search filter' where a pop-up can explain in a few words what the categories mean
1. Decide which topics should be attached to which sermons (what is the best cut-off - five/ten topics most present in each sermon, other? - Gleb and Shari will work this out)
1. Connect topics to AF's

**Comment by ErwinKomen** [comment]
> The file is [here](https://drive.google.com/file/d/191H4MAZwJoh_rS9ePRXb-0fc-B9mf9c9/view?usp=sharing)

Why is each AF represented more than once? (i.e. rows for particular codes are repeated an arbitrarily? number of times)

**Comment by glsch** [comment]
This is because I sent a version calculated for paragraphs. I'll send the one for entire today.

**Comment by ErwinKomen** [comment]
### Most recent notes:
1. There is a list of signatures (hence SG and hence AFs) that are not (yet) in Passim. Action: **skip these**

**Comment by ErwinKomen** [comment]
Please provide the right wording for the HELP INFORMATION towards the Category filter in Indices > Keywords > Category.
Right now it's like this:

![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/0f95d1a6-436c-44da-bf52-a6f067ef1f05)

**Comment by ErwinKomen** [comment]
Adapted wording:
![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/b6faf8e2-9729-48e3-89d9-7199ec4b04dd)
