### ISSUE TITLE
Check approval rights

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#730]
Before the final launch, do a final check of the editor approval system: 

- Do editors only have access to their own projects?
- When an item with multiple project labels is changed, is the change signalled as pending to editors of the other project?
- Does the interface in MyPASSIM for approving changes work correctly and easily?

To be tested by Shari, Rafael, and Janis - any needed changes will be listed here.

1. HUWA-imported authority files, even those that also have a PASSIM-project label, cannot be changed/edited by PASSIM editors. This should be changed, so that any item (manuscript/authority file/manifestation) can be edited by editors with rights on the project labels attached to these items (voorbeeld: passim.rich.ru.nl/ssg/details/1083/).
2. PASSIM editors cannot now approve (turn green) authority files that also have. HUWA-label. This needs to be changed: editors of any project associated with an item should be able to change the status of that item, pending approval by editors of the other projects associated to that item.
3. When merging data on manuscripts, one from HUWA import, one from PASSIM or other source, if we want to use the PASSIM-item and eliminate the HUWA-item, we need to be able to add the HUWA-id. So, action point: add a field 'HUWA-id' by default to all items when they are assigned the HUWA-project label. If it is easier, add a field 'HUWA-id' to all manuscript items, visible only when there is data in it.

**Comment by ErwinKomen** [comment]
### Notes/implementation

1. HUWA-imported authority files, even those that also have a PASSIM-project label, cannot be changed/edited by PASSIM editors. This should be changed, so that any item (manuscript/authority file/manifestation) can be edited by editors with rights on the project labels attached to these items (voorbeeld: passim.rich.ru.nl/ssg/details/1083/).
    1. Any AF that is connected with **two** projects can only be changed, when both project **approvers** agree
        1. Possible resolution (for you to do): 
            1. have the moderator give someone from the team HUWA project approval rights
            2. make the changes in the HUWA project connected AFs as required
            3. have the moderator remove the person's HUWA project approval rights
    1. Other items (manuscrip/manifestation) do not have this intricate project approval system. So the comment about that is moot, I think.

**Comment by ErwinKomen** [comment]
### Editable HUWA id fields
1. There already are internal tables that hold the connection between an internal Passim object (M, S) and an external object . The implementation depends on the particular model
1. **Authority File**: this is `EqualGold`
    1. externaltype = `huwop`
(e.g. HUWA), so this can be implemented...
    1. The HUWA id is already shown, if someone is a HUWA project approver
        1. Changed that into HUWA project editor
    1. Added `externalid` to the AF form, checked, works
1. **Manuscript**: that is `Manuscript`
1. **Sermon manifestation**: that is `SermonDescr`
