### ISSUE TITLE
Phantom authority files?

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#735]
Sometimes when entering a string into a search field, the dropdown menu offers a hit, but when then clicking 'search', there are no results in the list view. Example:

Search > Authority Files > Explicit > "allegatione confidamus" > Dropdown menu gives matching explicit (sed in aduocati nostri allegatione confidamus qui uiuit … saeculorum amen), but no results are listed in the list view when pressing search.

What could be happening here? This happens also on other occasions, usually when entering incipit or explicit.

**Comment by ErwinKomen** [comment]
### Implementation
The reason for this was that form `SuperSermonGoldForm` used incipit and explicit typeahead from **gold** rather than from **equalgold**.
I corrected this in the form and added necessary API calls in the urls.py and adapted the code in passim.js
