### ISSUE TITLE
Test items clean-up

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#740]
Clean up any test manuscript or so:
1. Remove projects `ErwinTest01`, `ErwinTest02`
1. Remove Manuscripts (incl. manifestations) with shelfmark `ERK` (erwin) 
1. Remove Gryson/Clavis “EK tst 01”
1. Remove Authority file 051.1100 
1. Remove Datasets (Erwin): personal ones (leave the team ones)
1. Remove keyword erwintest
1. Any test HCs?

**Comment by ErwinKomen** [comment]
### Implementation
1. Removed project links with M, S, C, SSG
1. Removed projects `ErwinTest01`, `ErwinTest02`
1. Removed AF 051.1100
1. Removed SG 1347
1. Removed gryson `EK tst 01`
1. Removed manuscript with `ERK` 
1. Removed all private datasets from `erwin` 
1. Removed any HCs from `erwin` 
1. Removed keyword `erwintest`

**Comment by ErwinKomen** [comment]
Double check for project-less items:
1. Manuscripts:
2. Sermons:
3. Collections
4. EqualGold: `[4151, 6090, 6150, 6152, 6153, 6155, 6156, 6158, 6159, 6161, 6162, 6163, 6164, 6166, 6187, 6200, 6201, 6202, 6203, 6320, 6553, 6554, 6555, 6556, 7265, 7269, 7293, 7340]`

**Comment by ErwinKomen** [comment]
### Projectless sermons
1. Somehow the number of sermons without projects had grown to **2945**.
    1. I added `adapt_projectorphans()` in adaptations. This made a lot of repairs
    2. The number has now dereased to **668**, though this is just **261**, if we exclude to `mtype="man"` (actual manifestations, instead of templates, the latter of which there are 407)
    3. These **261** sermons belong to three manuscripts, with the following id's: `[5126, 16203, 16204]`

**Comment by shariboodts** [comment]
Projectless sermons: the three remaining manuscripts were errors/empty manuscripts. I've deleted them, so there should now be no more projectless manifestations.
