### ISSUE TITLE
DCT: bug in specific DCT matches display

### ISSUE THREAD

**Issue by Irisdenis** [ErwinKomen/RU-passim#745]
The number of displayed matches between two manuscripts in a research set, differs in relation to which of the two manuscript is the pivot. This should not happen: i.e. in a DCT of manuscripts A, B and C, there should be the same number of matches between A and B regardless of whether A or B is the pivot. (If C is the pivot, only the matches between C and the other manuscripts should be displayed - that's a different situation).

- **Case in point:** https://passim.rich.ru.nl/dct/details/83/ 
Printscreen 1, with Vat. Lat. 3836 as pivot, only shows one overlapping sermon to Vat. Lat. 3828 (AU s 334 = nr. 88). This is incorrect (there should be more overlapping sermons). If I make Vat. Lat. 3828 the pivot manuscript (printscreen 2), there are 12 overlapping sermons with Vat. Lat. 3836 (which is correct).

- The problem is confined to these manuscripts in this research set; I've not yet encountered it elsewhere. It could be difficult to trace for a user, though, so the cause of the bug should be investigated.

- **Matches only/View all.** The problem is partially 'solved' by clicking 'view all' in the rows display (left upper corner), which shows all items in the pivot manuscript, regardless of matches. With Vat. Lat. 3836 as pivot, there are now 12 matches to Vat. Lat. 3828 displayed (which is correct). If I try to readjust the 'rows' to 'matches only', nothing happens; when reloading the page, we're back to the situation in printscreen 1. So, it seems that the matches are correctly recorded, but not displayed in the default, 'matches only' view (whereas they should be; 'matches only' should show all matches to the pivot manuscript).

- Is this issue perhaps related to the error, signaled in issue #693 ?

 
![image](https://github.com/ErwinKomen/RU-passim/assets/57664160/6db335a4-32c9-45dd-bbca-8f61c471e4fd)

Printscreen 1 (Vat. Lat. 3836 as pivot)

![image](https://github.com/ErwinKomen/RU-passim/assets/57664160/dd644ff7-771d-4ef3-be00-7f4880893d26)

Printscreen 2 (Vat. Lat. 3828 as pivot)

**Comment by ErwinKomen** [comment]
### Observations
When clicking "view all", there is a Javascript error `lst_exclude is undefined` in function `dct_row_combine()`
