### ISSUE TITLE
Datasets visible to all users (even when marked 'private')

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#748]
Currently datasets are visible to all users, even when marked 'private'. Please change so that only datasets marked 'public' are visible to all users. Datasets marked 'private' should only be visible to the person who created the dataset in question.

**Comment by ErwinKomen** [comment]
### Implementation
1. Dataset listview
    1.

**Comment by shariboodts** [comment]
I checked this issue from my 'regular user' account and have noticed:

- Visibility works correctly now: I can only see public datasets.
- When I click on MyDatasets in MyPASSIM, I go to a list view with all public datasets, not a list view of my own (public+private) datasets.

**Comment by ErwinKomen** [comment]
> When I click on MyDatasets in MyPASSIM, I go to a list view with all public datasets, not a list view of my own (public+private) datasets.

That's not true. When I log in with your username, "MyDatasets" leads me to **public + private** datasets.
![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/5f2bdc62-36b4-4c23-bc9c-e95790c946ba)

**Comment by shariboodts** [comment]
Wanneer ik inlog met shariboodts_user (een gewone user, zonder speciale rechten), zie ik enkel public datasets, niet mijn eigen datasets (2 - ik heb er net een nieuwe gecreëerd om het te testen).

**Comment by ErwinKomen** [comment]
Yes, I see now. You're right. I only allowed **public** datasets for non editors. That was wrong...

### Implementation
1. Users-only may see:
    1. their own private + public, if nothing else is specified
    2. Their own private ones, if scope is `priv` 
    3. Public ones, if scope is `publ` (or `team` - which should have no other effect)

### Private dataset viewing
I had not yet addressed the visibility of the details view of private datasets.
That should be changed too, in accordance with:
> ... only datasets marked 'public' are visible to all users. Datasets marked 'private' should only be visible to the person who created the dataset in question.

1. When a user tries to see something that is private to someone else, need to make sure that `permission` is set to false
2. Handled that in `CollAnyEdit` method `add_to_context()`
