### ISSUE TITLE
Ease of use: small corrections

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#752]
1. Listview Historical Collections: collection only opens when you click on the name (left column). Would be easier if it also opened if you clicked on the Author column (it changes colour when you hover over it).
2. HUWA-authority files have a table of editions. Change the column order so it is: Full title, short title, volume, pages (makes more sense to users).

**Comment by ErwinKomen** [comment]
1. Listview HC: added `, 'linkdetails': True` to `self.order_heads` - checked, works
2. HUWA authority files:
    1. This pertains to the view `EqualGoldEdit`
    2. The editions table is shown via template `seeker/huwa_edilit.html`
    3. The column order was: editions, Author, Year, **Short**, **pp**, **Title (series/literature)**, **Vol**, Location, S
    4. The new order is: editions, Author, Year, **Title (series/literature)**, **Short**, **Vol**, **pp**, Location, S
