### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#753]
Add Ger's user guide to the application (PDF and HTML). Wait until June after development is complete and user guide has been reviewed against most recent version of research tool.

**Comment by ErwinKomen** [comment]
### Two approaches
1. We can upload the PDF and add a button (e.g. in the **about** section) to allow users to download it
2. it is also possible to provide for a HTML-based help system on the basis of the Word document, provided we transform it correctly into the correct **markdown** format

**Comment by ErwinKomen** [comment]
### User guide via Sphinx
Okay, I started out with this a little bit. What I've done:
1. Created a Sphinx project under directory `userguide`
2. Added the `introduction` as a separate rst file
3. Figured out how to add images and size them
4. Created a first version (dev env)

**Comment by ErwinKomen** [comment]
A link to the PDF has now been added (by TH)
