### ISSUE TITLE
List view results sorting - restore to default

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#764]
When sorting columns in the list view, they get a number (1, 2, 3) depending on the priority of sorting. When pressing 'Clear' to clear the search filters, the order of sorting of the list views remains in place. Only when exiting the database completely, it is reset to default. 

Create an option to clear the sorting of the list views and restore to default.

**Comment by ErwinKomen** [comment]
Each individual column priority can be removed by pressing the gray up/down symbol left of the sort number:

![image](https://github.com/ErwinKomen/RU-passim/assets/11887269/fae7f20b-8c50-4b89-a57f-86145febad22)


Would it be an option to let the 'Clear' button also reset the list view column priority?
Or else: add a button with `Clear sort order` or something like that?

**Comment by shariboodts** [comment]
I would let the 'clear' button also reset the list view column priority.

**Comment by ErwinKomen** [comment]
> I would let the 'clear' button also reset the list view column priority.

Okay, the `Clear` button now resets the list view column priority **and**, almost by necessity, it also re-loads the listview coming up with a clean slant.

**Comment by ErwinKomen** [comment]
> An additional question: when clicking the sorting button for the Gryson/Clavis code column, I do not see any logic in what happens. Ideally, the sorting would happen alphabetically based on the first Gryson or Clavis code in the field, and then numerically, so:
> 
> AU ci AU s 1 AU s 23 AU s 89 AU s 100 CAE s 20 GREG s 50
> 
> Is that possible? If the numerical is too complex this way, the alphabetical alone would also already be good.

### Implementation
1. The order is Lower case, contents of `siglist` field
1. But the contents of that field are not necessarily in the correct order... 
1. Relates to: `SermonGold`, `SermonDescr`

**Comment by ErwinKomen** [comment]
Okay, works, implemented
