### ISSUE TITLE
Bug - Moving Manifestations

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#768]
When testing the 'moving manifestation' (to merge two manuscripts), I think the following problem arises. Although the transfer of manifestations from ms 1 to ms 2 initially worked fine, the manifestations disappeared when the empty ms 1 was deleted (as in, I think this is what happened). The purpose of the tool is to facilitate easy merging, so this is not what should happen. When moving manifestations, they should become linked to their new location and loose all ties to their old 'manuscript'.

**Comment by ErwinKomen** [comment]
### Testing
I tested this in the development environment, and it is exactly as the PI has noticed:
1. Move manifestations to new manuscript
    1. Old manuscript is now without manifestations - _correct_
    2. New manuscript has the new manifestations - _correct_
1. Remove the old manuscript
    1. **Bad**: The old manuscript's manifestations are now 'deleted' completely!

**Comment by ErwinKomen** [comment]
### Resolution
1. Look at the code in views `SermonMove`
    1. This looks for the last codicological unit of the destination manuscript
    2. And then it does `msitem.move_codico(lastcodico)`
1. Looking at model `MsItem`, method `move_codico()`
    1. Added line to adjust the msitem's `manu` field
