### ISSUE TITLE
My Datasets: Default

### ISSUE THREAD

**Issue by shariboodts** [ErwinKomen/RU-passim#770]
When viewing My Datasets from MyPASSIM, the default setting shows all datasets a user has access to (Private + Public + Team). Please set the default so the list view only shows Private datasets (the scope filter can then be used to view Public and Team datasets).

**Comment by ErwinKomen** [comment]
### Owner or Private?
Right now the 'current size' in MyPassim shows the number of datasets a user is the **owner** of.
In my case, for example, that is `13`.
However, I do not have any `private` datasets.

So what should the `Saved datasets` initially focus on?
1. As the count indicates: all datasets of which the user is the owner
2. It should only point to all the user's **private** datasets, which means that the 'current size' should be adapted

**Comment by ErwinKomen** [comment]
### Implementation
This is the 'default' setting for `/dataset/private/list` = `CollectionListView` with prefix `priv`
Note: the user _should_ still be able to view all he/she has access to (Private, public, team - with the scope filter).

**Comment by ErwinKomen** [comment]
Okay, the 'implementation' above works.
However, it should also be possible to overtly filter on `owner`, then...
