### ISSUE TITLE
Bibliography: manuscript PDF

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#86]
The bibliography should also contain a link to a PDF that contains a list of relevant manuscripts.
This PDF can be 'refreshed' by authorized users and then uploaded.

So it should be in the MEDIA directory of the system?

**Comment by ThijsRU** [comment]
- Separate PDF options for _Editions_ and _Literature_?

**Comment by ThijsRU** [comment]
The functionality to create a pdf with all manuscripts in the PASSIM database is working on the live version of the webapplication.
