### ISSUE TITLE
Manuscript templates: create system

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-passim#89]
Create a manuscript-template system with the following features (which can each be sub-issues in the system):
1. Allows creation of a template based on a `Manuscript` or on a `Collection`
1. A template should be editable, and
    1. Should be given a name
    1. The sermons in a template must be orderable
    1. Sermons in a template must be deletable (to adapte the template)
1. The (manual) creation of a new manuscript should be possible based on a template

**Comment by ThijsRU** [comment]
Linked to #59 ?

**Comment by ErwinKomen** [comment]
Actually: 59==89.
I have added the new information on the manuscript template at #59 , which means that this issue #89 can be marked as resolved (that deletes it)
